
Sys={}
Sys['obs']={}
Sys['exp']={}
Sys['obs']['Cg']=[]
Sys['obs']['Ctg']=[]
Sys['obs']['Cphiq']=[]
Sys['obs']['Ctw']=[]
Sys['obs']['Cug']=[]
Sys['obs']['Ccg']=[]
Sys['exp']['Cg']=[]
Sys['exp']['Ctg']=[]
Sys['exp']['Cphiq']=[]
Sys['exp']['Ctw']=[]
Sys['exp']['Cug']=[]
Sys['exp']['Ccg']=[]

Sys['obs']['Cg'].append('TT_TopMass_')
Sys['obs']['Cg'].append('tw_DS_')
Sys['obs']['Cg'].append('DY_QCD_')
Sys['obs']['Cg'].append('MuonIDScaleFactor_')
Sys['obs']['Cg'].append('is1jet_1bjet_DY_normalisation')
Sys['obs']['Cg'].append('TT_PDF_')
Sys['obs']['Cg'].append('MC_stat')
Sys['obs']['Cg'].append('JetEnergyScale_')
Sys['obs']['Cg'].append('TW_normalisation')
Sys['obs']['Cg'].append('is1jet_0bjet_DY_normalisation')
Sys['obs']['Cg'].append('PileUp_')
Sys['obs']['Cg'].append('FSR_')
Sys['obs']['Cg'].append('is2jet_2bjet_DY_normalisation')
Sys['obs']['Cg'].append('MuonTrackEfficiencyScaleFactor_')
Sys['obs']['Cg'].append('tw_TopMass_')
Sys['obs']['Cg'].append('TT_Tune_')
Sys['obs']['Cg'].append('TT_CR_')
Sys['obs']['Cg'].append('BtagScaleFactor_udsg_')
Sys['obs']['Cg'].append('ElectronReconstructionScaleFactor_')
Sys['obs']['Cg'].append('TT_QCD_')
Sys['obs']['Cg'].append('ISR_')
Sys['obs']['Cg'].append('Luminosity')
Sys['obs']['Cg'].append('is2jet_1bjet_DY_normalisation')
Sys['obs']['Cg'].append('BtagScaleFactor_bc_')
Sys['obs']['Cg'].append('MuonIsoScaleFactor_')
Sys['obs']['Cg'].append('ElectronIDIsoScaleFactor_')
Sys['obs']['Cg'].append('Signal_extra')
Sys['obs']['Cg'].append('Other_normalisation')
Sys['obs']['Cg'].append('tw_MEscale_')
Sys['obs']['Cg'].append('JetEnergyResolution_')
Sys['obs']['Cg'].append('TT_hdamp_')
Sys['obs']['Cg'].append('Jets_normalisation')
Sys['obs']['Cg'].append('TriggerSF_')
Sys['obs']['Cg'].append('DY_PDF_')


Sys['obs']['Cphiq'].append('TT_TopMass_')
Sys['obs']['Cphiq'].append('tw_DS_')
Sys['obs']['Cphiq'].append('DY_QCD_')
Sys['obs']['Cphiq'].append('MuonIDScaleFactor_')
Sys['obs']['Cphiq'].append('UnclusteredEn_')
Sys['obs']['Cphiq'].append('is1jet_1bjet_DY_normalisation')
Sys['obs']['Cphiq'].append('TT_PDF_')
Sys['obs']['Cphiq'].append('MC_stat')
Sys['obs']['Cphiq'].append('JetEnergyScale_')
Sys['obs']['Cphiq'].append('is1jet_0bjet_DY_normalisation')
Sys['obs']['Cphiq'].append('ISR_')
Sys['obs']['Cphiq'].append('FSR_')
Sys['obs']['Cphiq'].append('MuonTrackEfficiencyScaleFactor_')
Sys['obs']['Cphiq'].append('tw_TopMass_')
Sys['obs']['Cphiq'].append('TT_Tune_')
Sys['obs']['Cphiq'].append('Luminosity')
Sys['obs']['Cphiq'].append('BtagScaleFactor_udsg_')
Sys['obs']['Cphiq'].append('ElectronReconstructionScaleFactor_')
Sys['obs']['Cphiq'].append('TT_QCD_')
Sys['obs']['Cphiq'].append('PileUp_')
Sys['obs']['Cphiq'].append('TT_CR_')
Sys['obs']['Cphiq'].append('is2jet_1bjet_DY_normalisation')
Sys['obs']['Cphiq'].append('is2jet_2bjet_DY_normalisation')
Sys['obs']['Cphiq'].append('MuonIsoScaleFactor_')
Sys['obs']['Cphiq'].append('ElectronIDIsoScaleFactor_')
Sys['obs']['Cphiq'].append('TT_normalisation')
Sys['obs']['Cphiq'].append('Other_normalisation')
Sys['obs']['Cphiq'].append('tw_MEscale_')
Sys['obs']['Cphiq'].append('JetEnergyResolution_')
Sys['obs']['Cphiq'].append('TT_hdamp_')
Sys['obs']['Cphiq'].append('BtagScaleFactor_bc_')
Sys['obs']['Cphiq'].append('TriggerSF_')
Sys['obs']['Cphiq'].append('DY_PDF_')
Sys['obs']['Cphiq'].append('Jets_normalisation')

Sys['obs']['Ctw'].append('TT_TopMass_')
Sys['obs']['Ctw'].append('tw_DS_')
Sys['obs']['Ctw'].append('DY_QCD_')
Sys['obs']['Ctw'].append('MuonIDScaleFactor_')
Sys['obs']['Ctw'].append('UnclusteredEn_')
Sys['obs']['Ctw'].append('is1jet_1bjet_DY_normalisation')
Sys['obs']['Ctw'].append('TT_PDF_')
Sys['obs']['Ctw'].append('MC_stat')
Sys['obs']['Ctw'].append('JetEnergyScale_')
Sys['obs']['Ctw'].append('is1jet_0bjet_DY_normalisation')
Sys['obs']['Ctw'].append('ISR_')
Sys['obs']['Ctw'].append('FSR_')
Sys['obs']['Ctw'].append('MuonTrackEfficiencyScaleFactor_')
Sys['obs']['Ctw'].append('tw_TopMass_')
Sys['obs']['Ctw'].append('TT_Tune_')
Sys['obs']['Ctw'].append('Luminosity')
Sys['obs']['Ctw'].append('BtagScaleFactor_udsg_')
Sys['obs']['Ctw'].append('ElectronReconstructionScaleFactor_')
Sys['obs']['Ctw'].append('TT_QCD_')
Sys['obs']['Ctw'].append('PileUp_')
Sys['obs']['Ctw'].append('TT_CR_')
Sys['obs']['Ctw'].append('is2jet_1bjet_DY_normalisation')
Sys['obs']['Ctw'].append('is2jet_2bjet_DY_normalisation')
Sys['obs']['Ctw'].append('MuonIsoScaleFactor_')
Sys['obs']['Ctw'].append('ElectronIDIsoScaleFactor_')
Sys['obs']['Ctw'].append('TT_normalisation')
Sys['obs']['Ctw'].append('Other_normalisation')
Sys['obs']['Ctw'].append('tw_MEscale_')
Sys['obs']['Ctw'].append('JetEnergyResolution_')
Sys['obs']['Ctw'].append('TT_hdamp_')
Sys['obs']['Ctw'].append('BtagScaleFactor_bc_')
Sys['obs']['Ctw'].append('TriggerSF_')
Sys['obs']['Ctw'].append('DY_PDF_')
Sys['obs']['Ctw'].append('Jets_normalisation')

Sys['obs']['Ctg'].append('TT_TopMass_')
Sys['obs']['Ctg'].append('tw_DS_')
Sys['obs']['Ctg'].append('DY_QCD_')
Sys['obs']['Ctg'].append('MuonIDScaleFactor_')
Sys['obs']['Ctg'].append('UnclusteredEn_')
Sys['obs']['Ctg'].append('is1jet_1bjet_DY_normalisation')
Sys['obs']['Ctg'].append('TT_PDF_')
Sys['obs']['Ctg'].append('MC_stat')
Sys['obs']['Ctg'].append('JetEnergyScale_')
Sys['obs']['Ctg'].append('is1jet_0bjet_DY_normalisation')
Sys['obs']['Ctg'].append('PileUp_')
Sys['obs']['Ctg'].append('FSR_')
Sys['obs']['Ctg'].append('MuonTrackEfficiencyScaleFactor_')
Sys['obs']['Ctg'].append('tw_TopMass_')
Sys['obs']['Ctg'].append('TT_Tune_')
Sys['obs']['Ctg'].append('Luminosity')
Sys['obs']['Ctg'].append('BtagScaleFactor_udsg_')
Sys['obs']['Ctg'].append('ElectronReconstructionScaleFactor_')
Sys['obs']['Ctg'].append('TT_QCD_')
Sys['obs']['Ctg'].append('ISR_')
Sys['obs']['Ctg'].append('TT_CR_')
Sys['obs']['Ctg'].append('is2jet_1bjet_DY_normalisation')
Sys['obs']['Ctg'].append('is2jet_2bjet_DY_normalisation')
Sys['obs']['Ctg'].append('MuonIsoScaleFactor_')
Sys['obs']['Ctg'].append('ElectronIDIsoScaleFactor_')
Sys['obs']['Ctg'].append('Other_normalisation')
Sys['obs']['Ctg'].append('tw_MEscale_')
Sys['obs']['Ctg'].append('JetEnergyResolution_')
Sys['obs']['Ctg'].append('TT_hdamp_')
Sys['obs']['Ctg'].append('BtagScaleFactor_bc_')
Sys['obs']['Ctg'].append('TriggerSF_')
Sys['obs']['Ctg'].append('DY_PDF_')
Sys['obs']['Ctg'].append('Jets_normalisation')
#------------ Cug ------------
Sys['obs']['Cug'].append('TT_TopMass_')
Sys['obs']['Cug'].append('isxjet_1bjet_DY_normalisation_Norm')
Sys['obs']['Cug'].append('tw_DS_')
Sys['obs']['Cug'].append('MuonIDScaleFactor_')
Sys['obs']['Cug'].append('UnclusteredEn_')
Sys['obs']['Cug'].append('Jets_normalisation_Norm')
Sys['obs']['Cug'].append('TT_normalisation_Norm')
Sys['obs']['Cug'].append('TT_PDF_')
Sys['obs']['Cug'].append('MC_stat')
Sys['obs']['Cug'].append('TW_normalisation_Norm')
Sys['obs']['Cug'].append('JetEnergyScale_')
Sys['obs']['Cug'].append('FCNC_PDF_')
Sys['obs']['Cug'].append('PileUp_')
Sys['obs']['Cug'].append('FSR_')
Sys['obs']['Cug'].append('MuonTrackEfficiencyScaleFactor_')
Sys['obs']['Cug'].append('tw_TopMass_')
Sys['obs']['Cug'].append('TT_Tune_')
Sys['obs']['Cug'].append('Luminosity')
Sys['obs']['Cug'].append('BtagScaleFactor_udsg_')
Sys['obs']['Cug'].append('FCNC_PS_')
Sys['obs']['Cug'].append('ElectronReconstructionScaleFactor_')
Sys['obs']['Cug'].append('TT_QCD_')
Sys['obs']['Cug'].append('ISR_')
Sys['obs']['Cug'].append('Othernormalisation_Norm')
Sys['obs']['Cug'].append('TT_CR_')
Sys['obs']['Cug'].append('BtagScaleFactor_bc_')
Sys['obs']['Cug'].append('MuonIsoScaleFactor_')
Sys['obs']['Cug'].append('FCNC_QCD_')
Sys['obs']['Cug'].append('ElectronIDIsoScaleFactor_')
Sys['obs']['Cug'].append('tw_MEscale_')
Sys['obs']['Cug'].append('JetEnergyResolution_')
Sys['obs']['Cug'].append('TT_hdamp_')
Sys['obs']['Cug'].append('TriggerSF_')
#------------ Ccg ------------
Sys['obs']['Ccg'].append('TT_TopMass_')
Sys['obs']['Ccg'].append('isxjet_1bjet_DY_normalisation_Norm')
Sys['obs']['Ccg'].append('tw_DS_')
Sys['obs']['Ccg'].append('MuonIDScaleFactor_')
Sys['obs']['Ccg'].append('UnclusteredEn_')
Sys['obs']['Ccg'].append('Jets_normalisation_Norm')
Sys['obs']['Ccg'].append('TT_normalisation_Norm')
Sys['obs']['Ccg'].append('TT_PDF_')
Sys['obs']['Ccg'].append('MC_stat')
Sys['obs']['Ccg'].append('TW_normalisation_Norm')
Sys['obs']['Ccg'].append('JetEnergyScale_')
Sys['obs']['Ccg'].append('FCNC_PDF_')
Sys['obs']['Ccg'].append('PileUp_')
Sys['obs']['Ccg'].append('FSR_')
Sys['obs']['Ccg'].append('MuonTrackEfficiencyScaleFactor_')
Sys['obs']['Ccg'].append('tw_TopMass_')
Sys['obs']['Ccg'].append('TT_Tune_')
Sys['obs']['Ccg'].append('Luminosity')
Sys['obs']['Ccg'].append('BtagScaleFactor_udsg_')
Sys['obs']['Ccg'].append('FCNC_PS_')
Sys['obs']['Ccg'].append('ElectronReconstructionScaleFactor_')
Sys['obs']['Ccg'].append('TT_QCD_')
Sys['obs']['Ccg'].append('ISR_')
Sys['obs']['Ccg'].append('Othernormalisation_Norm')
Sys['obs']['Ccg'].append('TT_CR_')
Sys['obs']['Ccg'].append('BtagScaleFactor_bc_')
Sys['obs']['Ccg'].append('MuonIsoScaleFactor_')
Sys['obs']['Ccg'].append('FCNC_QCD_')
Sys['obs']['Ccg'].append('ElectronIDIsoScaleFactor_')
Sys['obs']['Ccg'].append('tw_MEscale_')
Sys['obs']['Ccg'].append('JetEnergyResolution_')
Sys['obs']['Ccg'].append('TT_hdamp_')
Sys['obs']['Ccg'].append('TriggerSF_')
########## exp ##########
#------------ Cg ------------
Sys['exp']['Cg'].append('TT_TopMass_')
Sys['exp']['Cg'].append('tw_DS_')
Sys['exp']['Cg'].append('DY_QCD_')
Sys['exp']['Cg'].append('MuonIDScaleFactor_')
Sys['exp']['Cg'].append('is1jet_1bjet_DY_normalisation')
Sys['exp']['Cg'].append('TT_PDF_')
Sys['exp']['Cg'].append('MC_stat')
Sys['exp']['Cg'].append('JetEnergyScale_')
Sys['exp']['Cg'].append('TW_normalisation')
Sys['exp']['Cg'].append('is1jet_0bjet_DY_normalisation')
Sys['exp']['Cg'].append('PileUp_')
Sys['exp']['Cg'].append('FSR_')
Sys['exp']['Cg'].append('is2jet_2bjet_DY_normalisation')
Sys['exp']['Cg'].append('MuonTrackEfficiencyScaleFactor_')
Sys['exp']['Cg'].append('tw_TopMass_')
Sys['exp']['Cg'].append('TT_Tune_')
Sys['exp']['Cg'].append('TT_CR_')
Sys['exp']['Cg'].append('BtagScaleFactor_udsg_')
Sys['exp']['Cg'].append('ElectronReconstructionScaleFactor_')
Sys['exp']['Cg'].append('TT_QCD_')
Sys['exp']['Cg'].append('ISR_')
Sys['exp']['Cg'].append('Luminosity')
Sys['exp']['Cg'].append('is2jet_1bjet_DY_normalisation')
Sys['exp']['Cg'].append('BtagScaleFactor_bc_')
Sys['exp']['Cg'].append('MuonIsoScaleFactor_')
Sys['exp']['Cg'].append('ElectronIDIsoScaleFactor_')
Sys['exp']['Cg'].append('Signal_extra')
Sys['exp']['Cg'].append('Other_normalisation')
Sys['exp']['Cg'].append('tw_MEscale_')
Sys['exp']['Cg'].append('JetEnergyResolution_')
Sys['exp']['Cg'].append('TT_hdamp_')
Sys['exp']['Cg'].append('Jets_normalisation')
Sys['exp']['Cg'].append('TriggerSF_')
Sys['exp']['Cg'].append('DY_PDF_')
#------------ Cphiq ------------
Sys['exp']['Cphiq'].append('TT_TopMass_')
Sys['exp']['Cphiq'].append('tw_DS_')
Sys['exp']['Cphiq'].append('DY_QCD_')
Sys['exp']['Cphiq'].append('MuonIDScaleFactor_')
Sys['exp']['Cphiq'].append('UnclusteredEn_')
Sys['exp']['Cphiq'].append('is1jet_1bjet_DY_normalisation')
Sys['exp']['Cphiq'].append('TT_PDF_')
Sys['exp']['Cphiq'].append('MC_stat')
Sys['exp']['Cphiq'].append('JetEnergyScale_')
Sys['exp']['Cphiq'].append('is1jet_0bjet_DY_normalisation')
Sys['exp']['Cphiq'].append('ISR_')
Sys['exp']['Cphiq'].append('FSR_')
Sys['exp']['Cphiq'].append('MuonTrackEfficiencyScaleFactor_')
Sys['exp']['Cphiq'].append('tw_TopMass_')
Sys['exp']['Cphiq'].append('TT_Tune_')
Sys['exp']['Cphiq'].append('Luminosity')
Sys['exp']['Cphiq'].append('BtagScaleFactor_udsg_')
Sys['exp']['Cphiq'].append('ElectronReconstructionScaleFactor_')
Sys['exp']['Cphiq'].append('TT_QCD_')
Sys['exp']['Cphiq'].append('PileUp_')
Sys['exp']['Cphiq'].append('TT_CR_')
Sys['exp']['Cphiq'].append('is2jet_1bjet_DY_normalisation')
Sys['exp']['Cphiq'].append('is2jet_2bjet_DY_normalisation')
Sys['exp']['Cphiq'].append('MuonIsoScaleFactor_')
Sys['exp']['Cphiq'].append('ElectronIDIsoScaleFactor_')
Sys['exp']['Cphiq'].append('TT_normalisation')
Sys['exp']['Cphiq'].append('Other_normalisation')
Sys['exp']['Cphiq'].append('tw_MEscale_')
Sys['exp']['Cphiq'].append('JetEnergyResolution_')
Sys['exp']['Cphiq'].append('TT_hdamp_')
Sys['exp']['Cphiq'].append('BtagScaleFactor_bc_')
Sys['exp']['Cphiq'].append('TriggerSF_')
Sys['exp']['Cphiq'].append('DY_PDF_')
Sys['exp']['Cphiq'].append('Jets_normalisation')
#------------ Ctw ------------
Sys['exp']['Ctw'].append('TT_TopMass_')
Sys['exp']['Ctw'].append('tw_DS_')
Sys['exp']['Ctw'].append('DY_QCD_')
Sys['exp']['Ctw'].append('MuonIDScaleFactor_')
Sys['exp']['Ctw'].append('UnclusteredEn_')
Sys['exp']['Ctw'].append('is1jet_1bjet_DY_normalisation')
Sys['exp']['Ctw'].append('TT_PDF_')
Sys['exp']['Ctw'].append('MC_stat')
Sys['exp']['Ctw'].append('JetEnergyScale_')
Sys['exp']['Ctw'].append('is1jet_0bjet_DY_normalisation')
Sys['exp']['Ctw'].append('ISR_')
Sys['exp']['Ctw'].append('FSR_')
Sys['exp']['Ctw'].append('MuonTrackEfficiencyScaleFactor_')
Sys['exp']['Ctw'].append('tw_TopMass_')
Sys['exp']['Ctw'].append('TT_Tune_')
Sys['exp']['Ctw'].append('Luminosity')
Sys['exp']['Ctw'].append('BtagScaleFactor_udsg_')
Sys['exp']['Ctw'].append('ElectronReconstructionScaleFactor_')
Sys['exp']['Ctw'].append('TT_QCD_')
Sys['exp']['Ctw'].append('PileUp_')
Sys['exp']['Ctw'].append('TT_CR_')
Sys['exp']['Ctw'].append('is2jet_1bjet_DY_normalisation')
Sys['exp']['Ctw'].append('is2jet_2bjet_DY_normalisation')
Sys['exp']['Ctw'].append('MuonIsoScaleFactor_')
Sys['exp']['Ctw'].append('ElectronIDIsoScaleFactor_')
Sys['exp']['Ctw'].append('TT_normalisation')
Sys['exp']['Ctw'].append('Other_normalisation')
Sys['exp']['Ctw'].append('tw_MEscale_')
Sys['exp']['Ctw'].append('JetEnergyResolution_')
Sys['exp']['Ctw'].append('TT_hdamp_')
Sys['exp']['Ctw'].append('BtagScaleFactor_bc_')
Sys['exp']['Ctw'].append('TriggerSF_')
Sys['exp']['Ctw'].append('DY_PDF_')
Sys['exp']['Ctw'].append('Jets_normalisation')
#------------ Ctg ------------
Sys['exp']['Ctg'].append('TT_TopMass_')
Sys['exp']['Ctg'].append('tw_DS_')
Sys['exp']['Ctg'].append('DY_QCD_')
Sys['exp']['Ctg'].append('MuonIDScaleFactor_')
Sys['exp']['Ctg'].append('UnclusteredEn_')
Sys['exp']['Ctg'].append('is1jet_1bjet_DY_normalisation')
Sys['exp']['Ctg'].append('TT_PDF_')
Sys['exp']['Ctg'].append('MC_stat')
Sys['exp']['Ctg'].append('JetEnergyScale_')
Sys['exp']['Ctg'].append('is1jet_0bjet_DY_normalisation')
Sys['exp']['Ctg'].append('PileUp_')
Sys['exp']['Ctg'].append('FSR_')
Sys['exp']['Ctg'].append('MuonTrackEfficiencyScaleFactor_')
Sys['exp']['Ctg'].append('tw_TopMass_')
Sys['exp']['Ctg'].append('TT_Tune_')
Sys['exp']['Ctg'].append('Luminosity')
Sys['exp']['Ctg'].append('BtagScaleFactor_udsg_')
Sys['exp']['Ctg'].append('ElectronReconstructionScaleFactor_')
Sys['exp']['Ctg'].append('TT_QCD_')
Sys['exp']['Ctg'].append('ISR_')
Sys['exp']['Ctg'].append('TT_CR_')
Sys['exp']['Ctg'].append('is2jet_1bjet_DY_normalisation')
Sys['exp']['Ctg'].append('is2jet_2bjet_DY_normalisation')
Sys['exp']['Ctg'].append('MuonIsoScaleFactor_')
Sys['exp']['Ctg'].append('ElectronIDIsoScaleFactor_')
Sys['exp']['Ctg'].append('Other_normalisation')
Sys['exp']['Ctg'].append('tw_MEscale_')
Sys['exp']['Ctg'].append('JetEnergyResolution_')
Sys['exp']['Ctg'].append('TT_hdamp_')
Sys['exp']['Ctg'].append('BtagScaleFactor_bc_')
Sys['exp']['Ctg'].append('TriggerSF_')
Sys['exp']['Ctg'].append('DY_PDF_')
Sys['exp']['Ctg'].append('Jets_normalisation')
#------------ Cug ------------
Sys['exp']['Cug'].append('TT_TopMass_')
Sys['exp']['Cug'].append('isxjet_1bjet_DY_normalisation_Norm')
Sys['exp']['Cug'].append('tw_DS_')
Sys['exp']['Cug'].append('MuonIDScaleFactor_')
Sys['exp']['Cug'].append('UnclusteredEn_')
Sys['exp']['Cug'].append('Jets_normalisation_Norm')
Sys['exp']['Cug'].append('TT_normalisation_Norm')
Sys['exp']['Cug'].append('TT_PDF_')
Sys['exp']['Cug'].append('MC_stat')
Sys['exp']['Cug'].append('TW_normalisation_Norm')
Sys['exp']['Cug'].append('JetEnergyScale_')
Sys['exp']['Cug'].append('FCNC_PDF_')
Sys['exp']['Cug'].append('PileUp_')
Sys['exp']['Cug'].append('FSR_')
Sys['exp']['Cug'].append('MuonTrackEfficiencyScaleFactor_')
Sys['exp']['Cug'].append('tw_TopMass_')
Sys['exp']['Cug'].append('TT_Tune_')
Sys['exp']['Cug'].append('Luminosity')
Sys['exp']['Cug'].append('BtagScaleFactor_udsg_')
Sys['exp']['Cug'].append('FCNC_PS_')
Sys['exp']['Cug'].append('ElectronReconstructionScaleFactor_')
Sys['exp']['Cug'].append('TT_QCD_')
Sys['exp']['Cug'].append('ISR_')
Sys['exp']['Cug'].append('Othernormalisation_Norm')
Sys['exp']['Cug'].append('TT_CR_')
Sys['exp']['Cug'].append('BtagScaleFactor_bc_')
Sys['exp']['Cug'].append('MuonIsoScaleFactor_')
Sys['exp']['Cug'].append('FCNC_QCD_')
Sys['exp']['Cug'].append('ElectronIDIsoScaleFactor_')
Sys['exp']['Cug'].append('tw_MEscale_')
Sys['exp']['Cug'].append('JetEnergyResolution_')
Sys['exp']['Cug'].append('TT_hdamp_')
Sys['exp']['Cug'].append('TriggerSF_')
#------------ Ccg ------------
Sys['exp']['Ccg'].append('TT_TopMass_')
Sys['exp']['Ccg'].append('isxjet_1bjet_DY_normalisation_Norm')
Sys['exp']['Ccg'].append('tw_DS_')
Sys['exp']['Ccg'].append('MuonIDScaleFactor_')
Sys['exp']['Ccg'].append('UnclusteredEn_')
Sys['exp']['Ccg'].append('Jets_normalisation_Norm')
Sys['exp']['Ccg'].append('TT_normalisation_Norm')
Sys['exp']['Ccg'].append('TT_PDF_')
Sys['exp']['Ccg'].append('MC_stat')
Sys['exp']['Ccg'].append('TW_normalisation_Norm')
Sys['exp']['Ccg'].append('JetEnergyScale_')
Sys['exp']['Ccg'].append('FCNC_PDF_')
Sys['exp']['Ccg'].append('PileUp_')
Sys['exp']['Ccg'].append('FSR_')
Sys['exp']['Ccg'].append('MuonTrackEfficiencyScaleFactor_')
Sys['exp']['Ccg'].append('tw_TopMass_')
Sys['exp']['Ccg'].append('TT_Tune_')
Sys['exp']['Ccg'].append('Luminosity')
Sys['exp']['Ccg'].append('BtagScaleFactor_udsg_')
Sys['exp']['Ccg'].append('FCNC_PS_')
Sys['exp']['Ccg'].append('ElectronReconstructionScaleFactor_')
Sys['exp']['Ccg'].append('TT_QCD_')
Sys['exp']['Ccg'].append('ISR_')
Sys['exp']['Ccg'].append('Othernormalisation_Norm')
Sys['exp']['Ccg'].append('TT_CR_')
Sys['exp']['Ccg'].append('BtagScaleFactor_bc_')
Sys['exp']['Ccg'].append('MuonIsoScaleFactor_')
Sys['exp']['Ccg'].append('FCNC_QCD_')
Sys['exp']['Ccg'].append('ElectronIDIsoScaleFactor_')
Sys['exp']['Ccg'].append('tw_MEscale_')
Sys['exp']['Ccg'].append('JetEnergyResolution_')
Sys['exp']['Ccg'].append('TT_hdamp_')
Sys['exp']['Ccg'].append('TriggerSF_')



#############
title={'Cg':'C_{G}/#Lambda^{2} [TeV^{-2}]','Ctg':'C_{tG}/#Lambda^{2} [TeV^{-2}]','Cphiq':'C_{#phi q}/#Lambda^{2} [TeV^{-2}]','Ctw':'C_{tW}/#Lambda^{2} [TeV^{-2}]','Cug':'C_{uG}/#Lambda^{2} [TeV^{-2}]','Ccg':'C_{cG}/#Lambda^{2} [TeV^{-2}]'}
#for cat in ['obs','exp']:
for cat in ['obs']:
#for cat in ['exp']:
    for ic in ['Cg','Ctg','Cphiq','Ctw','Cug','Ccg']:
    #for ic in ['Cg']:
        print '######## %s %s ##############'%(cat,ic)
        str1="python ../../plot1DScan_wx.py  higgsCombineTotal.MultiDimFit.mH120.root --Xtitle '%s' --output '%s_%s'  --others "%(title[ic],cat,ic)
        for i in range(0,len(Sys[cat][ic])-1):## don't include last one, which is already in Freeze_all
            s1 = "'higgsCombine%s.MultiDimFit.mH120.root:Freeze %s:%s'"%(Sys[cat][ic][i],Sys[cat][ic][i],str(i+1))
            str1=str1+' '+s1
        s2 = "'higgsCombine%s.MultiDimFit.mH120.root:%s:%s'"%('Freeze_all','Freeze all',str(len(Sys[cat][ic])+1))
        str1=str1+' '+s2
        str1=str1+' '+'--breakdown '
        for i in range(0,len(Sys[cat][ic])):## here include all
            str1=str1+Sys[cat][ic][i]+','
        str1=str1+'stat'
        print str1













