cd /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/Impact/obs/Cphiq
eval `scramv1 runtime -sh`
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_ee_2jet_1bjet_TW_stat_bin2_ --algo impact --redefineSignalPOIs r -P ee_2jet_1bjet_TW_stat_bin2_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_ee_2jet_1bjet_other_stat_bin1_ --algo impact --redefineSignalPOIs r -P ee_2jet_1bjet_other_stat_bin1_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_ee_2jet_2bjet_TW_stat_bin1_ --algo impact --redefineSignalPOIs r -P ee_2jet_2bjet_TW_stat_bin1_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_emu_2jet_1bjet_TW_stat_bin5_ --algo impact --redefineSignalPOIs r -P emu_2jet_1bjet_TW_stat_bin5_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_emu_2jet_1bjet_other_stat_bin2_ --algo impact --redefineSignalPOIs r -P emu_2jet_1bjet_other_stat_bin2_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_emu_2jet_1bjet_other_stat_bin5_ --algo impact --redefineSignalPOIs r -P emu_2jet_1bjet_other_stat_bin5_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_mumu_1jet_1bjet_TW_stat_bin1_ --algo impact --redefineSignalPOIs r -P mumu_1jet_1bjet_TW_stat_bin1_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_mumu_2jet_1bjet_TW_stat_bin2_ --algo impact --redefineSignalPOIs r -P mumu_2jet_1bjet_TW_stat_bin2_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_mumu_2jet_1bjet_other_stat_bin2_ --algo impact --redefineSignalPOIs r -P mumu_2jet_1bjet_other_stat_bin2_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_mumu_2jet_1bjet_other_stat_bin3_ --algo impact --redefineSignalPOIs r -P mumu_2jet_1bjet_other_stat_bin3_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_mumu_2jet_2bjet_TW_stat_bin1_ --algo impact --redefineSignalPOIs r -P mumu_2jet_2bjet_TW_stat_bin1_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
logsave -a log_resub.txt combine -M MultiDimFit -n _paramFit_Test_mumu_2jet_2bjet_other_stat_bin1_ --algo impact --redefineSignalPOIs r -P mumu_2jet_2bjet_other_stat_bin1_ --floatOtherPOIs 1 --saveInactivePOI 1 --setPhysicsModelParameterRanges r=-4.0,0.0 --robustFit 1 --minimizerTolerance=0.001   -m 125 -d /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/Check_uncert/print_uncertinties/workspace/higgsCombineCphiq.MultiDimFit.mH120.root
