#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_mtop1755_1658_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_TuneCUETP8M2T4down_1423_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TTTo2L2Nu_1122_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampUP_473_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrup_564_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_mtop1755_1027_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_TuneCUETP8M2T4down_2583_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_GluonMoveCRTune_490_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TTTo2L2Nu_295_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_PDF_To2L2Nu_1681_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrup_2132_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrdown_1301_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_TuneCUETP8M2T4up_2614_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrup_1724_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_QCDbasedCRTune_erdON_491_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_GluonMoveCRTune_2038_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampUP_1772_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_mtop1695_1139_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_mtop1695_696_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampDOWN_1007_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrup_1879_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrdown_793_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrup_440_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_erdON_2079_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampDOWN_1253_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampUP_1526_wo_trig.sh
#bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrup_614_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_GluonMoveCRTune_999_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrup_949_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_mtop1755_1273_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_TuneCUETP8M2T4down_1008_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrup_730_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrdown_2139_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_mtop1755_582_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_PDF_To2L2Nu_995_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrup_1570_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_TuneCUETP8M2T4up_2440_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_QCDbasedCRTune_erdON_998_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrdown_1155_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_QCDbasedCRTune_erdON_1976_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrup_2366_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_fsrup_2519_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_PDF_To2L2Nu_2575_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampUP_627_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_TuneCUETP8M2T4down_1677_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_hdampDOWN_32_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrdown_1099_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_isrdown_2746_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_erdON_2452_wo_trig.sh
bash /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/ee_channel/reskim_script/script_perone/reMiniAOD/MC/mc_all/script_TT_PDF_To2L2Nu_3395_wo_trig.sh
echo "AllCompleted"
