// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Mon Jun 26 12:14:32 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA_FastSim/Wtb_mumu
Training events: 120000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0045490265,691.643188477]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.173115968704,634.239318848]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000690460205078,609.917480469]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0066184998,1170.79797363]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.183317109942,0.999995291233]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.255686700344,1121.8059082]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.0108325211331,8.15538978577]
M_l2_j1                       M_l2_j1                       M_l2_j1                       M_l2_j1                                                         'F'    [0.105659998953,2119.86572266]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.180050939322,0.999999284744]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "PT_ll_j1", "deltaR_ll_j1", "M_l2_j1", "C_l1_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.850906013640955;
   fWeightMatrix0to1[1][0] = 0.583672854555757;
   fWeightMatrix0to1[2][0] = 2.06186326281538;
   fWeightMatrix0to1[3][0] = 1.98204290213733;
   fWeightMatrix0to1[4][0] = -3.21650705114269;
   fWeightMatrix0to1[5][0] = 0.41772384922478;
   fWeightMatrix0to1[6][0] = 0.0926408649566497;
   fWeightMatrix0to1[7][0] = 0.990360346409826;
   fWeightMatrix0to1[8][0] = -0.244317971308898;
   fWeightMatrix0to1[9][0] = -1.00863405089916;
   fWeightMatrix0to1[0][1] = -0.435174325313674;
   fWeightMatrix0to1[1][1] = 1.13102461417595;
   fWeightMatrix0to1[2][1] = -0.610303595560341;
   fWeightMatrix0to1[3][1] = -1.00768571086609;
   fWeightMatrix0to1[4][1] = -0.49161012703352;
   fWeightMatrix0to1[5][1] = -3.38173489867189;
   fWeightMatrix0to1[6][1] = 0.624062311152997;
   fWeightMatrix0to1[7][1] = -0.387179320139572;
   fWeightMatrix0to1[8][1] = 1.71087890546975;
   fWeightMatrix0to1[9][1] = 2.0272355431534;
   fWeightMatrix0to1[0][2] = 0.539558029612846;
   fWeightMatrix0to1[1][2] = -0.30299019114863;
   fWeightMatrix0to1[2][2] = 1.2459870384405;
   fWeightMatrix0to1[3][2] = -0.911969735454785;
   fWeightMatrix0to1[4][2] = -0.383860640508673;
   fWeightMatrix0to1[5][2] = 0.629980686319781;
   fWeightMatrix0to1[6][2] = 2.7169401511795;
   fWeightMatrix0to1[7][2] = 0.366592849237422;
   fWeightMatrix0to1[8][2] = -2.37581868174095;
   fWeightMatrix0to1[9][2] = 1.06128860175922;
   fWeightMatrix0to1[0][3] = 1.66417248060459;
   fWeightMatrix0to1[1][3] = -0.664454128502998;
   fWeightMatrix0to1[2][3] = 1.02428890081322;
   fWeightMatrix0to1[3][3] = 0.38968380490275;
   fWeightMatrix0to1[4][3] = 0.570029186388247;
   fWeightMatrix0to1[5][3] = 3.84175990385737;
   fWeightMatrix0to1[6][3] = -0.512748449799267;
   fWeightMatrix0to1[7][3] = 2.21876537726187;
   fWeightMatrix0to1[8][3] = -1.80553486817722;
   fWeightMatrix0to1[9][3] = 0.77384499931489;
   fWeightMatrix0to1[0][4] = 0.930904062997847;
   fWeightMatrix0to1[1][4] = -0.990422762208042;
   fWeightMatrix0to1[2][4] = 1.09315345390946;
   fWeightMatrix0to1[3][4] = 0.752512541755171;
   fWeightMatrix0to1[4][4] = -0.736672208561943;
   fWeightMatrix0to1[5][4] = -0.239731437914024;
   fWeightMatrix0to1[6][4] = 0.185814119328566;
   fWeightMatrix0to1[7][4] = 1.63953525374171;
   fWeightMatrix0to1[8][4] = 1.70343634541432;
   fWeightMatrix0to1[9][4] = 2.33636726246126;
   fWeightMatrix0to1[0][5] = 2.47661215856303;
   fWeightMatrix0to1[1][5] = 4.1723632960637;
   fWeightMatrix0to1[2][5] = -1.01873382633526;
   fWeightMatrix0to1[3][5] = 0.0794584931094597;
   fWeightMatrix0to1[4][5] = -0.900892038638388;
   fWeightMatrix0to1[5][5] = -6.28890183739919;
   fWeightMatrix0to1[6][5] = -0.157934556622052;
   fWeightMatrix0to1[7][5] = -2.85285242798472;
   fWeightMatrix0to1[8][5] = 2.38201285186691;
   fWeightMatrix0to1[9][5] = 1.3271396155313;
   fWeightMatrix0to1[0][6] = -0.622583476529871;
   fWeightMatrix0to1[1][6] = 1.59011259074753;
   fWeightMatrix0to1[2][6] = 0.420955090973843;
   fWeightMatrix0to1[3][6] = 1.2387991819998;
   fWeightMatrix0to1[4][6] = 2.20798568180811;
   fWeightMatrix0to1[5][6] = -2.32005073398437;
   fWeightMatrix0to1[6][6] = 0.861428318443364;
   fWeightMatrix0to1[7][6] = -1.43443207929462;
   fWeightMatrix0to1[8][6] = -0.0956730797437955;
   fWeightMatrix0to1[9][6] = -0.538600605187077;
   fWeightMatrix0to1[0][7] = -0.0817836868399051;
   fWeightMatrix0to1[1][7] = -0.248462229234258;
   fWeightMatrix0to1[2][7] = 1.64485768810138;
   fWeightMatrix0to1[3][7] = 1.00179953098591;
   fWeightMatrix0to1[4][7] = 1.52113914116011;
   fWeightMatrix0to1[5][7] = -3.14527291112984;
   fWeightMatrix0to1[6][7] = -0.666200263092105;
   fWeightMatrix0to1[7][7] = -1.88979746900589;
   fWeightMatrix0to1[8][7] = 1.14593987289166;
   fWeightMatrix0to1[9][7] = 1.20948534853981;
   fWeightMatrix0to1[0][8] = 1.42016052266123;
   fWeightMatrix0to1[1][8] = 0.319782616643469;
   fWeightMatrix0to1[2][8] = 0.0596478640122009;
   fWeightMatrix0to1[3][8] = -0.49206954878001;
   fWeightMatrix0to1[4][8] = 0.0563518840112699;
   fWeightMatrix0to1[5][8] = -0.569821350464242;
   fWeightMatrix0to1[6][8] = 0.847565836877333;
   fWeightMatrix0to1[7][8] = -0.801005473295881;
   fWeightMatrix0to1[8][8] = -1.15395912435163;
   fWeightMatrix0to1[9][8] = -1.65680548606486;
   fWeightMatrix0to1[0][9] = -1.00277921594968;
   fWeightMatrix0to1[1][9] = 0.605900835993045;
   fWeightMatrix0to1[2][9] = 0.278486392624718;
   fWeightMatrix0to1[3][9] = -0.843348879199591;
   fWeightMatrix0to1[4][9] = -1.43396005027791;
   fWeightMatrix0to1[5][9] = -3.2643077028599;
   fWeightMatrix0to1[6][9] = -1.75791572074347;
   fWeightMatrix0to1[7][9] = -2.77679325910822;
   fWeightMatrix0to1[8][9] = -1.22334737219401;
   fWeightMatrix0to1[9][9] = 0.111238231183011;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.538845817901597;
   fWeightMatrix1to2[0][1] = -2.2615953164402;
   fWeightMatrix1to2[0][2] = 0.940911364113225;
   fWeightMatrix1to2[0][3] = 2.18006399335361;
   fWeightMatrix1to2[0][4] = -0.86035891069857;
   fWeightMatrix1to2[0][5] = 4.96938901699619;
   fWeightMatrix1to2[0][6] = 0.0198818478183002;
   fWeightMatrix1to2[0][7] = -1.5034920347505;
   fWeightMatrix1to2[0][8] = 1.26997724983146;
   fWeightMatrix1to2[0][9] = -1.76409704709923;
   fWeightMatrix1to2[0][10] = -4.23739601310907;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0611877441;
   fMax_1[0][0] = 483.105621338;
   fMin_1[1][0] = 25.0045490265;
   fMax_1[1][0] = 691.643188477;
   fMin_1[2][0] = 25.0045490265;
   fMax_1[2][0] = 691.643188477;
   fMin_1[0][1] = 0.789648532867;
   fMax_1[0][1] = 394.065185547;
   fMin_1[1][1] = 0.173115968704;
   fMax_1[1][1] = 634.239318848;
   fMin_1[2][1] = 0.173115968704;
   fMax_1[2][1] = 634.239318848;
   fMin_1[0][2] = 0.0030632019043;
   fMax_1[0][2] = 383.828948975;
   fMin_1[1][2] = 0.000690460205078;
   fMax_1[1][2] = 609.917480469;
   fMin_1[2][2] = 0.000690460205078;
   fMax_1[2][2] = 609.917480469;
   fMin_1[0][3] = 20.0066184998;
   fMax_1[0][3] = 1170.79797363;
   fMin_1[1][3] = 20.0121040344;
   fMax_1[1][3] = 1072.47766113;
   fMin_1[2][3] = 20.0066184998;
   fMax_1[2][3] = 1170.79797363;
   fMin_1[0][4] = 0.186472326517;
   fMax_1[0][4] = 0.999933302402;
   fMin_1[1][4] = 0.183317109942;
   fMax_1[1][4] = 0.999995291233;
   fMin_1[2][4] = 0.183317109942;
   fMax_1[2][4] = 0.999995291233;
   fMin_1[0][5] = 0.789648532867;
   fMax_1[0][5] = 469.497680664;
   fMin_1[1][5] = 0.255686700344;
   fMax_1[1][5] = 1121.8059082;
   fMin_1[2][5] = 0.255686700344;
   fMax_1[2][5] = 1121.8059082;
   fMin_1[0][6] = 0.0229919981211;
   fMax_1[0][6] = 6.99988460541;
   fMin_1[1][6] = 0.0108325211331;
   fMax_1[1][6] = 8.15538978577;
   fMin_1[2][6] = 0.0108325211331;
   fMax_1[2][6] = 8.15538978577;
   fMin_1[0][7] = 0.105659998953;
   fMax_1[0][7] = 978.875549316;
   fMin_1[1][7] = 0.105659998953;
   fMax_1[1][7] = 2119.86572266;
   fMin_1[2][7] = 0.105659998953;
   fMax_1[2][7] = 2119.86572266;
   fMin_1[0][8] = 0.180050939322;
   fMax_1[0][8] = 0.999987065792;
   fMin_1[1][8] = 0.180229574442;
   fMax_1[1][8] = 0.999999284744;
   fMin_1[2][8] = 0.180050939322;
   fMax_1[2][8] = 0.999999284744;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
