bash ./scripts/exp_Ccg_BtagScaleFactor_bc_.sh
bash ./scripts/exp_Ccg_BtagScaleFactor_udsg_.sh
bash ./scripts/exp_Ccg_ElectronIDIsoScaleFactor_.sh
bash ./scripts/exp_Ccg_ElectronReconstructionScaleFactor_.sh
bash ./scripts/exp_Ccg_FCNC_PDF_.sh
bash ./scripts/exp_Ccg_FCNC_PS_.sh
bash ./scripts/exp_Ccg_FCNC_QCD_.sh
bash ./scripts/exp_Ccg_FSR_.sh
bash ./scripts/exp_Ccg_Freeze_all.sh
bash ./scripts/exp_Ccg_ISR_.sh
bash ./scripts/exp_Ccg_JetEnergyResolution_.sh
bash ./scripts/exp_Ccg_JetEnergyScale_.sh
bash ./scripts/exp_Ccg_Jets_normalisation_Norm.sh
bash ./scripts/exp_Ccg_Luminosity.sh
bash ./scripts/exp_Ccg_MC_stat.sh
bash ./scripts/exp_Ccg_MuonIDScaleFactor_.sh
bash ./scripts/exp_Ccg_MuonIsoScaleFactor_.sh
bash ./scripts/exp_Ccg_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/exp_Ccg_Othernormalisation_Norm.sh
bash ./scripts/exp_Ccg_PileUp_.sh
bash ./scripts/exp_Ccg_TT_CR_.sh
bash ./scripts/exp_Ccg_TT_PDF_.sh
bash ./scripts/exp_Ccg_TT_QCD_.sh
bash ./scripts/exp_Ccg_TT_TopMass_.sh
bash ./scripts/exp_Ccg_TT_Tune_.sh
bash ./scripts/exp_Ccg_TT_hdamp_.sh
bash ./scripts/exp_Ccg_TT_normalisation_Norm.sh
bash ./scripts/exp_Ccg_TW_normalisation_Norm.sh
bash ./scripts/exp_Ccg_Total.sh
bash ./scripts/exp_Ccg_TriggerSF_.sh
bash ./scripts/exp_Ccg_UnclusteredEn_.sh
bash ./scripts/exp_Ccg_isxjet_1bjet_DY_normalisation_Norm.sh
bash ./scripts/exp_Ccg_tw_DS_.sh
bash ./scripts/exp_Ccg_tw_MEscale_.sh
bash ./scripts/exp_Ccg_tw_TopMass_.sh
bash ./scripts/exp_Cg_BtagScaleFactor_bc_.sh
bash ./scripts/exp_Cg_BtagScaleFactor_udsg_.sh
bash ./scripts/exp_Cg_DY_PDF_.sh
bash ./scripts/exp_Cg_DY_QCD_.sh
bash ./scripts/exp_Cg_ElectronIDIsoScaleFactor_.sh
bash ./scripts/exp_Cg_ElectronReconstructionScaleFactor_.sh
bash ./scripts/exp_Cg_FSR_.sh
bash ./scripts/exp_Cg_Freeze_all.sh
bash ./scripts/exp_Cg_ISR_.sh
bash ./scripts/exp_Cg_JetEnergyResolution_.sh
bash ./scripts/exp_Cg_JetEnergyScale_.sh
bash ./scripts/exp_Cg_Jets_normalisation.sh
bash ./scripts/exp_Cg_Luminosity.sh
bash ./scripts/exp_Cg_MC_stat.sh
bash ./scripts/exp_Cg_MuonIDScaleFactor_.sh
bash ./scripts/exp_Cg_MuonIsoScaleFactor_.sh
bash ./scripts/exp_Cg_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/exp_Cg_Other_normalisation.sh
bash ./scripts/exp_Cg_PileUp_.sh
bash ./scripts/exp_Cg_Signal_extra.sh
bash ./scripts/exp_Cg_TT_CR_.sh
bash ./scripts/exp_Cg_TT_PDF_.sh
bash ./scripts/exp_Cg_TT_QCD_.sh
bash ./scripts/exp_Cg_TT_TopMass_.sh
bash ./scripts/exp_Cg_TT_Tune_.sh
bash ./scripts/exp_Cg_TT_hdamp_.sh
bash ./scripts/exp_Cg_TW_normalisation.sh
bash ./scripts/exp_Cg_Total.sh
bash ./scripts/exp_Cg_TriggerSF_.sh
bash ./scripts/exp_Cg_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/exp_Cg_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Cg_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Cg_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/exp_Cg_tw_DS_.sh
bash ./scripts/exp_Cg_tw_MEscale_.sh
bash ./scripts/exp_Cg_tw_TopMass_.sh
bash ./scripts/exp_Cphiq_BtagScaleFactor_bc_.sh
bash ./scripts/exp_Cphiq_BtagScaleFactor_udsg_.sh
bash ./scripts/exp_Cphiq_DY_PDF_.sh
bash ./scripts/exp_Cphiq_DY_QCD_.sh
bash ./scripts/exp_Cphiq_ElectronIDIsoScaleFactor_.sh
bash ./scripts/exp_Cphiq_ElectronReconstructionScaleFactor_.sh
bash ./scripts/exp_Cphiq_FSR_.sh
bash ./scripts/exp_Cphiq_Freeze_all.sh
bash ./scripts/exp_Cphiq_ISR_.sh
bash ./scripts/exp_Cphiq_JetEnergyResolution_.sh
bash ./scripts/exp_Cphiq_JetEnergyScale_.sh
bash ./scripts/exp_Cphiq_Jets_normalisation.sh
bash ./scripts/exp_Cphiq_Luminosity.sh
bash ./scripts/exp_Cphiq_MC_stat.sh
bash ./scripts/exp_Cphiq_MuonIDScaleFactor_.sh
bash ./scripts/exp_Cphiq_MuonIsoScaleFactor_.sh
bash ./scripts/exp_Cphiq_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/exp_Cphiq_Other_normalisation.sh
bash ./scripts/exp_Cphiq_PileUp_.sh
bash ./scripts/exp_Cphiq_TT_CR_.sh
bash ./scripts/exp_Cphiq_TT_PDF_.sh
bash ./scripts/exp_Cphiq_TT_QCD_.sh
bash ./scripts/exp_Cphiq_TT_TopMass_.sh
bash ./scripts/exp_Cphiq_TT_Tune_.sh
bash ./scripts/exp_Cphiq_TT_hdamp_.sh
bash ./scripts/exp_Cphiq_TT_normalisation.sh
bash ./scripts/exp_Cphiq_Total.sh
bash ./scripts/exp_Cphiq_TriggerSF_.sh
bash ./scripts/exp_Cphiq_UnclusteredEn_.sh
bash ./scripts/exp_Cphiq_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/exp_Cphiq_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Cphiq_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Cphiq_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/exp_Cphiq_tw_DS_.sh
bash ./scripts/exp_Cphiq_tw_MEscale_.sh
bash ./scripts/exp_Cphiq_tw_TopMass_.sh
bash ./scripts/exp_Ctg_BtagScaleFactor_bc_.sh
bash ./scripts/exp_Ctg_BtagScaleFactor_udsg_.sh
bash ./scripts/exp_Ctg_DY_PDF_.sh
bash ./scripts/exp_Ctg_DY_QCD_.sh
bash ./scripts/exp_Ctg_ElectronIDIsoScaleFactor_.sh
bash ./scripts/exp_Ctg_ElectronReconstructionScaleFactor_.sh
bash ./scripts/exp_Ctg_FSR_.sh
bash ./scripts/exp_Ctg_Freeze_all.sh
bash ./scripts/exp_Ctg_ISR_.sh
bash ./scripts/exp_Ctg_JetEnergyResolution_.sh
bash ./scripts/exp_Ctg_JetEnergyScale_.sh
bash ./scripts/exp_Ctg_Jets_normalisation.sh
bash ./scripts/exp_Ctg_Luminosity.sh
bash ./scripts/exp_Ctg_MC_stat.sh
bash ./scripts/exp_Ctg_MuonIDScaleFactor_.sh
bash ./scripts/exp_Ctg_MuonIsoScaleFactor_.sh
bash ./scripts/exp_Ctg_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/exp_Ctg_Other_normalisation.sh
bash ./scripts/exp_Ctg_PileUp_.sh
bash ./scripts/exp_Ctg_TT_CR_.sh
bash ./scripts/exp_Ctg_TT_PDF_.sh
bash ./scripts/exp_Ctg_TT_QCD_.sh
bash ./scripts/exp_Ctg_TT_TopMass_.sh
bash ./scripts/exp_Ctg_TT_Tune_.sh
bash ./scripts/exp_Ctg_TT_hdamp_.sh
bash ./scripts/exp_Ctg_Total.sh
bash ./scripts/exp_Ctg_TriggerSF_.sh
bash ./scripts/exp_Ctg_UnclusteredEn_.sh
bash ./scripts/exp_Ctg_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/exp_Ctg_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Ctg_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Ctg_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/exp_Ctg_tw_DS_.sh
bash ./scripts/exp_Ctg_tw_MEscale_.sh
bash ./scripts/exp_Ctg_tw_TopMass_.sh
bash ./scripts/exp_Ctw_BtagScaleFactor_bc_.sh
bash ./scripts/exp_Ctw_BtagScaleFactor_udsg_.sh
bash ./scripts/exp_Ctw_DY_PDF_.sh
bash ./scripts/exp_Ctw_DY_QCD_.sh
bash ./scripts/exp_Ctw_ElectronIDIsoScaleFactor_.sh
bash ./scripts/exp_Ctw_ElectronReconstructionScaleFactor_.sh
bash ./scripts/exp_Ctw_FSR_.sh
bash ./scripts/exp_Ctw_Freeze_all.sh
bash ./scripts/exp_Ctw_ISR_.sh
bash ./scripts/exp_Ctw_JetEnergyResolution_.sh
bash ./scripts/exp_Ctw_JetEnergyScale_.sh
bash ./scripts/exp_Ctw_Jets_normalisation.sh
bash ./scripts/exp_Ctw_Luminosity.sh
bash ./scripts/exp_Ctw_MC_stat.sh
bash ./scripts/exp_Ctw_MuonIDScaleFactor_.sh
bash ./scripts/exp_Ctw_MuonIsoScaleFactor_.sh
bash ./scripts/exp_Ctw_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/exp_Ctw_Other_normalisation.sh
bash ./scripts/exp_Ctw_PileUp_.sh
bash ./scripts/exp_Ctw_TT_CR_.sh
bash ./scripts/exp_Ctw_TT_PDF_.sh
bash ./scripts/exp_Ctw_TT_QCD_.sh
bash ./scripts/exp_Ctw_TT_TopMass_.sh
bash ./scripts/exp_Ctw_TT_Tune_.sh
bash ./scripts/exp_Ctw_TT_hdamp_.sh
bash ./scripts/exp_Ctw_TT_normalisation.sh
bash ./scripts/exp_Ctw_Total.sh
bash ./scripts/exp_Ctw_TriggerSF_.sh
bash ./scripts/exp_Ctw_UnclusteredEn_.sh
bash ./scripts/exp_Ctw_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/exp_Ctw_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Ctw_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/exp_Ctw_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/exp_Ctw_tw_DS_.sh
bash ./scripts/exp_Ctw_tw_MEscale_.sh
bash ./scripts/exp_Ctw_tw_TopMass_.sh
bash ./scripts/exp_Cug_BtagScaleFactor_bc_.sh
bash ./scripts/exp_Cug_BtagScaleFactor_udsg_.sh
bash ./scripts/exp_Cug_ElectronIDIsoScaleFactor_.sh
bash ./scripts/exp_Cug_ElectronReconstructionScaleFactor_.sh
bash ./scripts/exp_Cug_FCNC_PDF_.sh
bash ./scripts/exp_Cug_FCNC_PS_.sh
bash ./scripts/exp_Cug_FCNC_QCD_.sh
bash ./scripts/exp_Cug_FSR_.sh
bash ./scripts/exp_Cug_Freeze_all.sh
bash ./scripts/exp_Cug_ISR_.sh
bash ./scripts/exp_Cug_JetEnergyResolution_.sh
bash ./scripts/exp_Cug_JetEnergyScale_.sh
bash ./scripts/exp_Cug_Jets_normalisation_Norm.sh
bash ./scripts/exp_Cug_Luminosity.sh
bash ./scripts/exp_Cug_MC_stat.sh
bash ./scripts/exp_Cug_MuonIDScaleFactor_.sh
bash ./scripts/exp_Cug_MuonIsoScaleFactor_.sh
bash ./scripts/exp_Cug_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/exp_Cug_Othernormalisation_Norm.sh
bash ./scripts/exp_Cug_PileUp_.sh
bash ./scripts/exp_Cug_TT_CR_.sh
bash ./scripts/exp_Cug_TT_PDF_.sh
bash ./scripts/exp_Cug_TT_QCD_.sh
bash ./scripts/exp_Cug_TT_TopMass_.sh
bash ./scripts/exp_Cug_TT_Tune_.sh
bash ./scripts/exp_Cug_TT_hdamp_.sh
bash ./scripts/exp_Cug_TT_normalisation_Norm.sh
bash ./scripts/exp_Cug_TW_normalisation_Norm.sh
bash ./scripts/exp_Cug_Total.sh
bash ./scripts/exp_Cug_TriggerSF_.sh
bash ./scripts/exp_Cug_UnclusteredEn_.sh
bash ./scripts/exp_Cug_isxjet_1bjet_DY_normalisation_Norm.sh
bash ./scripts/exp_Cug_tw_DS_.sh
bash ./scripts/exp_Cug_tw_MEscale_.sh
bash ./scripts/exp_Cug_tw_TopMass_.sh
bash ./scripts/obs_Ccg_BtagScaleFactor_bc_.sh
bash ./scripts/obs_Ccg_BtagScaleFactor_udsg_.sh
bash ./scripts/obs_Ccg_ElectronIDIsoScaleFactor_.sh
bash ./scripts/obs_Ccg_ElectronReconstructionScaleFactor_.sh
bash ./scripts/obs_Ccg_FCNC_PDF_.sh
bash ./scripts/obs_Ccg_FCNC_PS_.sh
bash ./scripts/obs_Ccg_FCNC_QCD_.sh
bash ./scripts/obs_Ccg_FSR_.sh
bash ./scripts/obs_Ccg_Freeze_all.sh
bash ./scripts/obs_Ccg_ISR_.sh
bash ./scripts/obs_Ccg_JetEnergyResolution_.sh
bash ./scripts/obs_Ccg_JetEnergyScale_.sh
bash ./scripts/obs_Ccg_Jets_normalisation_Norm.sh
bash ./scripts/obs_Ccg_Luminosity.sh
bash ./scripts/obs_Ccg_MC_stat.sh
bash ./scripts/obs_Ccg_MuonIDScaleFactor_.sh
bash ./scripts/obs_Ccg_MuonIsoScaleFactor_.sh
bash ./scripts/obs_Ccg_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/obs_Ccg_Othernormalisation_Norm.sh
bash ./scripts/obs_Ccg_PileUp_.sh
bash ./scripts/obs_Ccg_TT_CR_.sh
bash ./scripts/obs_Ccg_TT_PDF_.sh
bash ./scripts/obs_Ccg_TT_QCD_.sh
bash ./scripts/obs_Ccg_TT_TopMass_.sh
bash ./scripts/obs_Ccg_TT_Tune_.sh
bash ./scripts/obs_Ccg_TT_hdamp_.sh
bash ./scripts/obs_Ccg_TT_normalisation_Norm.sh
bash ./scripts/obs_Ccg_TW_normalisation_Norm.sh
bash ./scripts/obs_Ccg_Total.sh
bash ./scripts/obs_Ccg_TriggerSF_.sh
bash ./scripts/obs_Ccg_UnclusteredEn_.sh
bash ./scripts/obs_Ccg_isxjet_1bjet_DY_normalisation_Norm.sh
bash ./scripts/obs_Ccg_tw_DS_.sh
bash ./scripts/obs_Ccg_tw_MEscale_.sh
bash ./scripts/obs_Ccg_tw_TopMass_.sh
bash ./scripts/obs_Cg_BtagScaleFactor_bc_.sh
bash ./scripts/obs_Cg_BtagScaleFactor_udsg_.sh
bash ./scripts/obs_Cg_DY_PDF_.sh
bash ./scripts/obs_Cg_DY_QCD_.sh
bash ./scripts/obs_Cg_ElectronIDIsoScaleFactor_.sh
bash ./scripts/obs_Cg_ElectronReconstructionScaleFactor_.sh
bash ./scripts/obs_Cg_FSR_.sh
bash ./scripts/obs_Cg_Freeze_all.sh
bash ./scripts/obs_Cg_ISR_.sh
bash ./scripts/obs_Cg_JetEnergyResolution_.sh
bash ./scripts/obs_Cg_JetEnergyScale_.sh
bash ./scripts/obs_Cg_Jets_normalisation.sh
bash ./scripts/obs_Cg_Luminosity.sh
bash ./scripts/obs_Cg_MC_stat.sh
bash ./scripts/obs_Cg_MuonIDScaleFactor_.sh
bash ./scripts/obs_Cg_MuonIsoScaleFactor_.sh
bash ./scripts/obs_Cg_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/obs_Cg_Other_normalisation.sh
bash ./scripts/obs_Cg_PileUp_.sh
bash ./scripts/obs_Cg_Signal_extra.sh
bash ./scripts/obs_Cg_TT_CR_.sh
bash ./scripts/obs_Cg_TT_PDF_.sh
bash ./scripts/obs_Cg_TT_QCD_.sh
bash ./scripts/obs_Cg_TT_TopMass_.sh
bash ./scripts/obs_Cg_TT_Tune_.sh
bash ./scripts/obs_Cg_TT_hdamp_.sh
bash ./scripts/obs_Cg_TW_normalisation.sh
bash ./scripts/obs_Cg_Total.sh
bash ./scripts/obs_Cg_TriggerSF_.sh
bash ./scripts/obs_Cg_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/obs_Cg_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Cg_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Cg_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/obs_Cg_tw_DS_.sh
bash ./scripts/obs_Cg_tw_MEscale_.sh
bash ./scripts/obs_Cg_tw_TopMass_.sh
bash ./scripts/obs_Cphiq_BtagScaleFactor_bc_.sh
bash ./scripts/obs_Cphiq_BtagScaleFactor_udsg_.sh
bash ./scripts/obs_Cphiq_DY_PDF_.sh
bash ./scripts/obs_Cphiq_DY_QCD_.sh
bash ./scripts/obs_Cphiq_ElectronIDIsoScaleFactor_.sh
bash ./scripts/obs_Cphiq_ElectronReconstructionScaleFactor_.sh
bash ./scripts/obs_Cphiq_FSR_.sh
bash ./scripts/obs_Cphiq_Freeze_all.sh
bash ./scripts/obs_Cphiq_ISR_.sh
bash ./scripts/obs_Cphiq_JetEnergyResolution_.sh
bash ./scripts/obs_Cphiq_JetEnergyScale_.sh
bash ./scripts/obs_Cphiq_Jets_normalisation.sh
bash ./scripts/obs_Cphiq_Luminosity.sh
bash ./scripts/obs_Cphiq_MC_stat.sh
bash ./scripts/obs_Cphiq_MuonIDScaleFactor_.sh
bash ./scripts/obs_Cphiq_MuonIsoScaleFactor_.sh
bash ./scripts/obs_Cphiq_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/obs_Cphiq_Other_normalisation.sh
bash ./scripts/obs_Cphiq_PileUp_.sh
bash ./scripts/obs_Cphiq_TT_CR_.sh
bash ./scripts/obs_Cphiq_TT_PDF_.sh
bash ./scripts/obs_Cphiq_TT_QCD_.sh
bash ./scripts/obs_Cphiq_TT_TopMass_.sh
bash ./scripts/obs_Cphiq_TT_Tune_.sh
bash ./scripts/obs_Cphiq_TT_hdamp_.sh
bash ./scripts/obs_Cphiq_TT_normalisation.sh
bash ./scripts/obs_Cphiq_Total.sh
bash ./scripts/obs_Cphiq_TriggerSF_.sh
bash ./scripts/obs_Cphiq_UnclusteredEn_.sh
bash ./scripts/obs_Cphiq_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/obs_Cphiq_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Cphiq_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Cphiq_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/obs_Cphiq_tw_DS_.sh
bash ./scripts/obs_Cphiq_tw_MEscale_.sh
bash ./scripts/obs_Cphiq_tw_TopMass_.sh
bash ./scripts/obs_Ctg_BtagScaleFactor_bc_.sh
bash ./scripts/obs_Ctg_BtagScaleFactor_udsg_.sh
bash ./scripts/obs_Ctg_DY_PDF_.sh
bash ./scripts/obs_Ctg_DY_QCD_.sh
bash ./scripts/obs_Ctg_ElectronIDIsoScaleFactor_.sh
bash ./scripts/obs_Ctg_ElectronReconstructionScaleFactor_.sh
bash ./scripts/obs_Ctg_FSR_.sh
bash ./scripts/obs_Ctg_Freeze_all.sh
bash ./scripts/obs_Ctg_ISR_.sh
bash ./scripts/obs_Ctg_JetEnergyResolution_.sh
bash ./scripts/obs_Ctg_JetEnergyScale_.sh
bash ./scripts/obs_Ctg_Jets_normalisation.sh
bash ./scripts/obs_Ctg_Luminosity.sh
bash ./scripts/obs_Ctg_MC_stat.sh
bash ./scripts/obs_Ctg_MuonIDScaleFactor_.sh
bash ./scripts/obs_Ctg_MuonIsoScaleFactor_.sh
bash ./scripts/obs_Ctg_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/obs_Ctg_Other_normalisation.sh
bash ./scripts/obs_Ctg_PileUp_.sh
bash ./scripts/obs_Ctg_TT_CR_.sh
bash ./scripts/obs_Ctg_TT_PDF_.sh
bash ./scripts/obs_Ctg_TT_QCD_.sh
bash ./scripts/obs_Ctg_TT_TopMass_.sh
bash ./scripts/obs_Ctg_TT_Tune_.sh
bash ./scripts/obs_Ctg_TT_hdamp_.sh
bash ./scripts/obs_Ctg_Total.sh
bash ./scripts/obs_Ctg_TriggerSF_.sh
bash ./scripts/obs_Ctg_UnclusteredEn_.sh
bash ./scripts/obs_Ctg_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/obs_Ctg_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Ctg_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Ctg_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/obs_Ctg_tw_DS_.sh
bash ./scripts/obs_Ctg_tw_MEscale_.sh
bash ./scripts/obs_Ctg_tw_TopMass_.sh
bash ./scripts/obs_Ctw_BtagScaleFactor_bc_.sh
bash ./scripts/obs_Ctw_BtagScaleFactor_udsg_.sh
bash ./scripts/obs_Ctw_DY_PDF_.sh
bash ./scripts/obs_Ctw_DY_QCD_.sh
bash ./scripts/obs_Ctw_ElectronIDIsoScaleFactor_.sh
bash ./scripts/obs_Ctw_ElectronReconstructionScaleFactor_.sh
bash ./scripts/obs_Ctw_FSR_.sh
bash ./scripts/obs_Ctw_Freeze_all.sh
bash ./scripts/obs_Ctw_ISR_.sh
bash ./scripts/obs_Ctw_JetEnergyResolution_.sh
bash ./scripts/obs_Ctw_JetEnergyScale_.sh
bash ./scripts/obs_Ctw_Jets_normalisation.sh
bash ./scripts/obs_Ctw_Luminosity.sh
bash ./scripts/obs_Ctw_MC_stat.sh
bash ./scripts/obs_Ctw_MuonIDScaleFactor_.sh
bash ./scripts/obs_Ctw_MuonIsoScaleFactor_.sh
bash ./scripts/obs_Ctw_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/obs_Ctw_Other_normalisation.sh
bash ./scripts/obs_Ctw_PileUp_.sh
bash ./scripts/obs_Ctw_TT_CR_.sh
bash ./scripts/obs_Ctw_TT_PDF_.sh
bash ./scripts/obs_Ctw_TT_QCD_.sh
bash ./scripts/obs_Ctw_TT_TopMass_.sh
bash ./scripts/obs_Ctw_TT_Tune_.sh
bash ./scripts/obs_Ctw_TT_hdamp_.sh
bash ./scripts/obs_Ctw_TT_normalisation.sh
bash ./scripts/obs_Ctw_Total.sh
bash ./scripts/obs_Ctw_TriggerSF_.sh
bash ./scripts/obs_Ctw_UnclusteredEn_.sh
bash ./scripts/obs_Ctw_is1jet_0bjet_DY_normalisation.sh
bash ./scripts/obs_Ctw_is1jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Ctw_is2jet_1bjet_DY_normalisation.sh
bash ./scripts/obs_Ctw_is2jet_2bjet_DY_normalisation.sh
bash ./scripts/obs_Ctw_tw_DS_.sh
bash ./scripts/obs_Ctw_tw_MEscale_.sh
bash ./scripts/obs_Ctw_tw_TopMass_.sh
bash ./scripts/obs_Cug_BtagScaleFactor_bc_.sh
bash ./scripts/obs_Cug_BtagScaleFactor_udsg_.sh
bash ./scripts/obs_Cug_ElectronIDIsoScaleFactor_.sh
bash ./scripts/obs_Cug_ElectronReconstructionScaleFactor_.sh
bash ./scripts/obs_Cug_FCNC_PDF_.sh
bash ./scripts/obs_Cug_FCNC_PS_.sh
bash ./scripts/obs_Cug_FCNC_QCD_.sh
bash ./scripts/obs_Cug_FSR_.sh
bash ./scripts/obs_Cug_Freeze_all.sh
bash ./scripts/obs_Cug_ISR_.sh
bash ./scripts/obs_Cug_JetEnergyResolution_.sh
bash ./scripts/obs_Cug_JetEnergyScale_.sh
bash ./scripts/obs_Cug_Jets_normalisation_Norm.sh
bash ./scripts/obs_Cug_Luminosity.sh
bash ./scripts/obs_Cug_MC_stat.sh
bash ./scripts/obs_Cug_MuonIDScaleFactor_.sh
bash ./scripts/obs_Cug_MuonIsoScaleFactor_.sh
bash ./scripts/obs_Cug_MuonTrackEfficiencyScaleFactor_.sh
bash ./scripts/obs_Cug_Othernormalisation_Norm.sh
bash ./scripts/obs_Cug_PileUp_.sh
bash ./scripts/obs_Cug_TT_CR_.sh
bash ./scripts/obs_Cug_TT_PDF_.sh
bash ./scripts/obs_Cug_TT_QCD_.sh
bash ./scripts/obs_Cug_TT_TopMass_.sh
bash ./scripts/obs_Cug_TT_Tune_.sh
bash ./scripts/obs_Cug_TT_hdamp_.sh
bash ./scripts/obs_Cug_TT_normalisation_Norm.sh
bash ./scripts/obs_Cug_TW_normalisation_Norm.sh
bash ./scripts/obs_Cug_Total.sh
bash ./scripts/obs_Cug_TriggerSF_.sh
bash ./scripts/obs_Cug_UnclusteredEn_.sh
bash ./scripts/obs_Cug_isxjet_1bjet_DY_normalisation_Norm.sh
bash ./scripts/obs_Cug_tw_DS_.sh
bash ./scripts/obs_Cug_tw_MEscale_.sh
bash ./scripts/obs_Cug_tw_TopMass_.sh
