// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Thu Jun  7 17:44:46 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_9_2_6/src/2016_ALL/tW/tw_74/TMVA/Samples_norminal/2j1b
Training events: 547715
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "10" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0005073547,998.587646484]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.0516224987805,970.948669434]
delta_PT_l2_j2                delta_PT_l2_j2                delta_PT_l2_j2                delta_PT_l2_j2                                                  'F'    [-500.947631836,419.442810059]
deltaR_l1_j2                  deltaR_l1_j2                  deltaR_l1_j2                  deltaR_l1_j2                                                    'F'    [0.344126969576,5.69235515594]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.0015413404908,7.65327262878]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [1.11123727038e-05,3.14158844948]
M_l1_j2                       M_l1_j2                       M_l1_j2                       M_l1_j2                                                         'F'    [11.8967847824,1492.41296387]
M_j1_j2                       M_j1_j2                       M_j1_j2                       M_j1_j2                                                         'F'    [13.2539606094,2406.51904297]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_l2_j2", "deltaR_l1_j2", "deltaR_ll_j1", "delta_phi_ll_j1", "M_l1_j2", "M_j1_j2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.341620176651599;
   fWeightMatrix0to1[1][0] = 4.43693685899442;
   fWeightMatrix0to1[2][0] = -0.555056924747594;
   fWeightMatrix0to1[3][0] = 4.33713616860323;
   fWeightMatrix0to1[4][0] = -1.48048774318003;
   fWeightMatrix0to1[5][0] = -0.0773204783722312;
   fWeightMatrix0to1[6][0] = -1.30574509916399;
   fWeightMatrix0to1[7][0] = 2.72560267854903;
   fWeightMatrix0to1[8][0] = 0.222052620752059;
   fWeightMatrix0to1[9][0] = -2.59273508111776;
   fWeightMatrix0to1[0][1] = -0.782001110103666;
   fWeightMatrix0to1[1][1] = -1.43548458149977;
   fWeightMatrix0to1[2][1] = -0.652954910311909;
   fWeightMatrix0to1[3][1] = -2.58865493237208;
   fWeightMatrix0to1[4][1] = -0.776978717261265;
   fWeightMatrix0to1[5][1] = 0.424755036466638;
   fWeightMatrix0to1[6][1] = -1.60047422996204;
   fWeightMatrix0to1[7][1] = 2.18955938064028;
   fWeightMatrix0to1[8][1] = -2.53121158562905;
   fWeightMatrix0to1[9][1] = 2.97352622509271;
   fWeightMatrix0to1[0][2] = -0.595283183376058;
   fWeightMatrix0to1[1][2] = -5.39141466548408;
   fWeightMatrix0to1[2][2] = 8.64410176153049;
   fWeightMatrix0to1[3][2] = -0.736716627935037;
   fWeightMatrix0to1[4][2] = -1.27459188531004;
   fWeightMatrix0to1[5][2] = -0.0603084821943962;
   fWeightMatrix0to1[6][2] = 4.33564912212617;
   fWeightMatrix0to1[7][2] = -1.23928345867157;
   fWeightMatrix0to1[8][2] = -6.71409924011127;
   fWeightMatrix0to1[9][2] = 2.18601185296689;
   fWeightMatrix0to1[0][3] = -0.418007251839946;
   fWeightMatrix0to1[1][3] = 2.65337911702383;
   fWeightMatrix0to1[2][3] = -0.488655332613002;
   fWeightMatrix0to1[3][3] = -3.39957231507711;
   fWeightMatrix0to1[4][3] = 2.90213428491862;
   fWeightMatrix0to1[5][3] = -2.28701630391676;
   fWeightMatrix0to1[6][3] = -0.624754021421215;
   fWeightMatrix0to1[7][3] = 1.47652259453979;
   fWeightMatrix0to1[8][3] = -1.23462495177883;
   fWeightMatrix0to1[9][3] = -4.65716593782138;
   fWeightMatrix0to1[0][4] = 1.64245638012994;
   fWeightMatrix0to1[1][4] = 1.29632642525332;
   fWeightMatrix0to1[2][4] = 3.00418205232759;
   fWeightMatrix0to1[3][4] = 1.12145309896948;
   fWeightMatrix0to1[4][4] = -2.19694747425499;
   fWeightMatrix0to1[5][4] = -3.16187107913519;
   fWeightMatrix0to1[6][4] = 1.11274559994448;
   fWeightMatrix0to1[7][4] = -0.228092312278206;
   fWeightMatrix0to1[8][4] = 0.91937886376404;
   fWeightMatrix0to1[9][4] = 2.53425744533927;
   fWeightMatrix0to1[0][5] = 0.809396689105162;
   fWeightMatrix0to1[1][5] = 1.59179299108093;
   fWeightMatrix0to1[2][5] = -1.99698229678597;
   fWeightMatrix0to1[3][5] = 0.919678196736114;
   fWeightMatrix0to1[4][5] = 0.991316996883527;
   fWeightMatrix0to1[5][5] = -2.81011052637237;
   fWeightMatrix0to1[6][5] = -1.97543977959306;
   fWeightMatrix0to1[7][5] = -1.79304661382773;
   fWeightMatrix0to1[8][5] = -0.327479081035374;
   fWeightMatrix0to1[9][5] = 0.207653810264947;
   fWeightMatrix0to1[0][6] = -2.00353150307146;
   fWeightMatrix0to1[1][6] = 6.89526187033867;
   fWeightMatrix0to1[2][6] = -1.09921953799859;
   fWeightMatrix0to1[3][6] = -0.647626531642867;
   fWeightMatrix0to1[4][6] = 5.847387408733;
   fWeightMatrix0to1[5][6] = 0.916680791279246;
   fWeightMatrix0to1[6][6] = -1.5923522235227;
   fWeightMatrix0to1[7][6] = -0.424398278782353;
   fWeightMatrix0to1[8][6] = 0.172306275121869;
   fWeightMatrix0to1[9][6] = -1.68037282992609;
   fWeightMatrix0to1[0][7] = -0.516384000300704;
   fWeightMatrix0to1[1][7] = -0.611101590307996;
   fWeightMatrix0to1[2][7] = -1.1774321616513;
   fWeightMatrix0to1[3][7] = 2.73718477329412;
   fWeightMatrix0to1[4][7] = 2.20529241257358;
   fWeightMatrix0to1[5][7] = -1.55272497879843;
   fWeightMatrix0to1[6][7] = -3.86374570145264;
   fWeightMatrix0to1[7][7] = -0.74582453533731;
   fWeightMatrix0to1[8][7] = 1.60995788142066;
   fWeightMatrix0to1[9][7] = 2.07099118093628;
   fWeightMatrix0to1[0][8] = 0.616916793322123;
   fWeightMatrix0to1[1][8] = 7.12793163160894;
   fWeightMatrix0to1[2][8] = -1.44487270567111;
   fWeightMatrix0to1[3][8] = -0.96725016347591;
   fWeightMatrix0to1[4][8] = 1.40471920080825;
   fWeightMatrix0to1[5][8] = 1.66564284854317;
   fWeightMatrix0to1[6][8] = -4.30652100408655;
   fWeightMatrix0to1[7][8] = -1.88961759197046;
   fWeightMatrix0to1[8][8] = -0.43173622043721;
   fWeightMatrix0to1[9][8] = -3.90886567572138;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.71240974984223;
   fWeightMatrix1to2[0][1] = 2.66894819925439;
   fWeightMatrix1to2[0][2] = 1.85616955255385;
   fWeightMatrix1to2[0][3] = -4.32346777809278;
   fWeightMatrix1to2[0][4] = -2.45024458592474;
   fWeightMatrix1to2[0][5] = 1.45710110797626;
   fWeightMatrix1to2[0][6] = -3.87745241851927;
   fWeightMatrix1to2[0][7] = -0.499587607970755;
   fWeightMatrix1to2[0][8] = -1.1860328307617;
   fWeightMatrix1to2[0][9] = 3.80064602921919;
   fWeightMatrix1to2[0][10] = -0.587207675147716;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0050544739;
   fMax_1[0][0] = 998.587646484;
   fMin_1[1][0] = 25.0005073547;
   fMax_1[1][0] = 731.804992676;
   fMin_1[2][0] = 25.0005073547;
   fMax_1[2][0] = 998.587646484;
   fMin_1[0][1] = 0.424787640572;
   fMax_1[0][1] = 970.948669434;
   fMin_1[1][1] = 0.0516224987805;
   fMax_1[1][1] = 675.661376953;
   fMin_1[2][1] = 0.0516224987805;
   fMax_1[2][1] = 970.948669434;
   fMin_1[0][2] = -490.501281738;
   fMax_1[0][2] = 263.805358887;
   fMin_1[1][2] = -500.947631836;
   fMax_1[1][2] = 419.442810059;
   fMin_1[2][2] = -500.947631836;
   fMax_1[2][2] = 419.442810059;
   fMin_1[0][3] = 0.411461532116;
   fMax_1[0][3] = 5.4996919632;
   fMin_1[1][3] = 0.344126969576;
   fMax_1[1][3] = 5.69235515594;
   fMin_1[2][3] = 0.344126969576;
   fMax_1[2][3] = 5.69235515594;
   fMin_1[0][4] = 0.0342117697001;
   fMax_1[0][4] = 7.65327262878;
   fMin_1[1][4] = 0.0015413404908;
   fMax_1[1][4] = 7.60103034973;
   fMin_1[2][4] = 0.0015413404908;
   fMax_1[2][4] = 7.65327262878;
   fMin_1[0][5] = 3.05734320136e-05;
   fMax_1[0][5] = 3.14157485962;
   fMin_1[1][5] = 1.11123727038e-05;
   fMax_1[1][5] = 3.14158844948;
   fMin_1[2][5] = 1.11123727038e-05;
   fMax_1[2][5] = 3.14158844948;
   fMin_1[0][6] = 15.4997110367;
   fMax_1[0][6] = 1457.53979492;
   fMin_1[1][6] = 11.8967847824;
   fMax_1[1][6] = 1492.41296387;
   fMin_1[2][6] = 11.8967847824;
   fMax_1[2][6] = 1492.41296387;
   fMin_1[0][7] = 14.1346282959;
   fMax_1[0][7] = 1411.71008301;
   fMin_1[1][7] = 13.2539606094;
   fMax_1[1][7] = 2406.51904297;
   fMin_1[2][7] = 13.2539606094;
   fMax_1[2][7] = 2406.51904297;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
