// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Thu Jun 15 10:34:41 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA/0j0b
Training events: 165453
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "10" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0013332367,620.583190918]
n_Loose_jet                   n_Loose_jet                   n_Loose_jet                   n_Loose_jet                                                     'I'    [0,7]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.056717440486,551.198669434]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000259399414062,548.250854492]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0032939911,1501.83654785]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.169171392918,0.999989390373]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "n_Loose_jet", "PT_ll", "delta_PT_ll", "M_ll", "C_ll" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -7.20683037838119;
   fWeightMatrix0to1[1][0] = 2.48605977085272;
   fWeightMatrix0to1[2][0] = -0.483255063760762;
   fWeightMatrix0to1[3][0] = 3.77203732565687;
   fWeightMatrix0to1[4][0] = -0.521064020019143;
   fWeightMatrix0to1[5][0] = -0.957344020536315;
   fWeightMatrix0to1[6][0] = -0.522605104443544;
   fWeightMatrix0to1[7][0] = 1.86906359638941;
   fWeightMatrix0to1[8][0] = -0.784281929501526;
   fWeightMatrix0to1[9][0] = -1.0081314237661;
   fWeightMatrix0to1[0][1] = -1.77349344066637;
   fWeightMatrix0to1[1][1] = 3.50690723572862;
   fWeightMatrix0to1[2][1] = -4.94277229412633;
   fWeightMatrix0to1[3][1] = -3.55482948858391;
   fWeightMatrix0to1[4][1] = 0.438464498706224;
   fWeightMatrix0to1[5][1] = 3.90854658999759;
   fWeightMatrix0to1[6][1] = 2.26528432377531;
   fWeightMatrix0to1[7][1] = 0.263586695423852;
   fWeightMatrix0to1[8][1] = 1.02290805887795;
   fWeightMatrix0to1[9][1] = 1.26266279813044;
   fWeightMatrix0to1[0][2] = -12.5756987830064;
   fWeightMatrix0to1[1][2] = 0.184380783202932;
   fWeightMatrix0to1[2][2] = 0.727090007716092;
   fWeightMatrix0to1[3][2] = 3.28100057788465;
   fWeightMatrix0to1[4][2] = 0.511841703563352;
   fWeightMatrix0to1[5][2] = -0.379332367753101;
   fWeightMatrix0to1[6][2] = 1.858482394383;
   fWeightMatrix0to1[7][2] = -0.968404072962849;
   fWeightMatrix0to1[8][2] = -1.33868961251257;
   fWeightMatrix0to1[9][2] = 0.208973892499467;
   fWeightMatrix0to1[0][3] = 6.53734294345951;
   fWeightMatrix0to1[1][3] = 0.942594119524905;
   fWeightMatrix0to1[2][3] = -3.08756794233319;
   fWeightMatrix0to1[3][3] = -0.131346394678895;
   fWeightMatrix0to1[4][3] = 1.95701092960874;
   fWeightMatrix0to1[5][3] = 1.2572456052239;
   fWeightMatrix0to1[6][3] = -2.03652866570509;
   fWeightMatrix0to1[7][3] = 0.961103236961619;
   fWeightMatrix0to1[8][3] = -0.306232048114399;
   fWeightMatrix0to1[9][3] = 1.14725958886558;
   fWeightMatrix0to1[0][4] = -8.65807334570642;
   fWeightMatrix0to1[1][4] = -1.04711926765472;
   fWeightMatrix0to1[2][4] = 4.92708313810962;
   fWeightMatrix0to1[3][4] = 2.29273452645979;
   fWeightMatrix0to1[4][4] = 0.754735027275984;
   fWeightMatrix0to1[5][4] = -2.79802471306114;
   fWeightMatrix0to1[6][4] = 0.467391578235382;
   fWeightMatrix0to1[7][4] = -0.172027278898806;
   fWeightMatrix0to1[8][4] = 2.3006154667054;
   fWeightMatrix0to1[9][4] = 1.57102980538935;
   fWeightMatrix0to1[0][5] = 0.170325680332104;
   fWeightMatrix0to1[1][5] = 0.463911957071901;
   fWeightMatrix0to1[2][5] = 0.0515859121307284;
   fWeightMatrix0to1[3][5] = -0.33771702518935;
   fWeightMatrix0to1[4][5] = -1.85708447721829;
   fWeightMatrix0to1[5][5] = -0.275055838538015;
   fWeightMatrix0to1[6][5] = -1.24001419839236;
   fWeightMatrix0to1[7][5] = -3.76936165270717;
   fWeightMatrix0to1[8][5] = 1.96474071538009;
   fWeightMatrix0to1[9][5] = 0.520603410947258;
   fWeightMatrix0to1[0][6] = -23.7048672072829;
   fWeightMatrix0to1[1][6] = 3.40385692317056;
   fWeightMatrix0to1[2][6] = -3.6950456325791;
   fWeightMatrix0to1[3][6] = 2.86874149227657;
   fWeightMatrix0to1[4][6] = -0.163130717293398;
   fWeightMatrix0to1[5][6] = -0.704637094146181;
   fWeightMatrix0to1[6][6] = 0.333749674129175;
   fWeightMatrix0to1[7][6] = -2.10631010957288;
   fWeightMatrix0to1[8][6] = 0.0124296938979908;
   fWeightMatrix0to1[9][6] = -0.9695671280166;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -12.2810192695781;
   fWeightMatrix1to2[0][1] = -2.20943373829626;
   fWeightMatrix1to2[0][2] = -2.50149066455617;
   fWeightMatrix1to2[0][3] = 1.52002181394029;
   fWeightMatrix1to2[0][4] = -0.171551957232439;
   fWeightMatrix1to2[0][5] = -0.0285038569166594;
   fWeightMatrix1to2[0][6] = -0.393744918388868;
   fWeightMatrix1to2[0][7] = -1.32385197283502;
   fWeightMatrix1to2[0][8] = 0.815863989711939;
   fWeightMatrix1to2[0][9] = 0.082758906147621;
   fWeightMatrix1to2[0][10] = 1.30425107750354;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0222377777;
   fMax_1[0][0] = 512.669006348;
   fMin_1[1][0] = 25.0013332367;
   fMax_1[1][0] = 620.583190918;
   fMin_1[2][0] = 25.0013332367;
   fMax_1[2][0] = 620.583190918;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 7;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 0.786144018173;
   fMax_1[0][2] = 364.788787842;
   fMin_1[1][2] = 0.056717440486;
   fMax_1[1][2] = 551.198669434;
   fMin_1[2][2] = 0.056717440486;
   fMax_1[2][2] = 551.198669434;
   fMin_1[0][3] = 0.00424385070801;
   fMax_1[0][3] = 359.307250977;
   fMin_1[1][3] = 0.000259399414062;
   fMax_1[1][3] = 548.250854492;
   fMin_1[2][3] = 0.000259399414062;
   fMax_1[2][3] = 548.250854492;
   fMin_1[0][4] = 20.037935257;
   fMax_1[0][4] = 1080.22216797;
   fMin_1[1][4] = 20.0032939911;
   fMax_1[1][4] = 1501.83654785;
   fMin_1[2][4] = 20.0032939911;
   fMax_1[2][4] = 1501.83654785;
   fMin_1[0][5] = 0.174664929509;
   fMax_1[0][5] = 0.999980330467;
   fMin_1[1][5] = 0.169171392918;
   fMax_1[1][5] = 0.999989390373;
   fMin_1[2][5] = 0.169171392918;
   fMax_1[2][5] = 0.999989390373;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
