mv Step2ee_hist_DYJetsToLL_M10to50_amc.root   ee_hist_DYJetsToLL_M10to50_amc.root 
mv Step2ee_hist_DYJetsToLL_M50_amc.root       ee_hist_DYJetsToLL_M50_amc.root 
mv Step2ee_hist_RunBCDEFGH.root               ee_hist_RunBCDEFGH.root 
mv Step2ee_hist_TTGJets.root                  ee_hist_TTGJets.root 
mv Step2ee_hist_TTTo2L2Nu.root                ee_hist_TTTo2L2Nu.root 
mv Step2ee_hist_TTWJetsToLNu.root             ee_hist_TTWJetsToLNu.root 
mv Step2ee_hist_TTWJetsToQQ.root              ee_hist_TTWJetsToQQ.root 
mv Step2ee_hist_TTZToLLNuNu.root              ee_hist_TTZToLLNuNu.root 
mv Step2ee_hist_TTZToQQ.root                  ee_hist_TTZToQQ.root 
mv Step2ee_hist_TW_antitop.root               ee_hist_TW_antitop.root 
mv Step2ee_hist_TW_top.root                   ee_hist_TW_top.root 
mv Step2ee_hist_WG_LNuG.root                  ee_hist_WG_LNuG.root 
mv Step2ee_hist_WJet_mad.root                 ee_hist_WJet_mad.root 
mv Step2ee_hist_WWTo2L2Nu.root                ee_hist_WWTo2L2Nu.root 
mv Step2ee_hist_WZ_2L2Q.root                  ee_hist_WZ_2L2Q.root 
mv Step2ee_hist_WZ_3LNu.root                  ee_hist_WZ_3LNu.root 
mv Step2ee_hist_ZZTo4L.root                   ee_hist_ZZTo4L.root 
mv Step2ee_hist_ZZ_2L2Nu.root                 ee_hist_ZZ_2L2Nu.root 
mv Step2emu_hist_DYJetsToLL_M10to50_amc.root  emu_hist_DYJetsToLL_M10to50_amc.root   
mv Step2emu_hist_DYJetsToLL_M50_amc.root      emu_hist_DYJetsToLL_M50_amc.root 
mv Step2emu_hist_RunBCDEFGH.root              emu_hist_RunBCDEFGH.root 
mv Step2emu_hist_TTGJets.root                 emu_hist_TTGJets.root 
mv Step2emu_hist_TTTo2L2Nu.root               emu_hist_TTTo2L2Nu.root 
mv Step2emu_hist_TTWJetsToLNu.root            emu_hist_TTWJetsToLNu.root 
mv Step2emu_hist_TTWJetsToQQ.root             emu_hist_TTWJetsToQQ.root 
mv Step2emu_hist_TTZToLLNuNu.root             emu_hist_TTZToLLNuNu.root 
mv Step2emu_hist_TTZToQQ.root                 emu_hist_TTZToQQ.root 
mv Step2emu_hist_TW_antitop.root              emu_hist_TW_antitop.root 
mv Step2emu_hist_TW_top.root                  emu_hist_TW_top.root 
mv Step2emu_hist_WG_LNuG.root                 emu_hist_WG_LNuG.root 
mv Step2emu_hist_WJet_mad.root                emu_hist_WJet_mad.root 
mv Step2emu_hist_WWTo2L2Nu.root               emu_hist_WWTo2L2Nu.root 
mv Step2emu_hist_WZ_2L2Q.root                 emu_hist_WZ_2L2Q.root 
mv Step2emu_hist_WZ_3LNu.root                 emu_hist_WZ_3LNu.root 
mv Step2emu_hist_ZZTo4L.root                  emu_hist_ZZTo4L.root 
mv Step2emu_hist_ZZ_2L2Nu.root                emu_hist_ZZ_2L2Nu.root 
mv Step2mumu_hist_DYJetsToLL_M10to50_amc.root mumu_hist_DYJetsToLL_M10to50_amc.root 
mv Step2mumu_hist_DYJetsToLL_M50_amc.root     mumu_hist_DYJetsToLL_M50_amc.root 
mv Step2mumu_hist_RunBCDEFGH.root             mumu_hist_RunBCDEFGH.root 
mv Step2mumu_hist_TTGJets.root                mumu_hist_TTGJets.root 
mv Step2mumu_hist_TTTo2L2Nu.root              mumu_hist_TTTo2L2Nu.root 
mv Step2mumu_hist_TTWJetsToLNu.root           mumu_hist_TTWJetsToLNu.root 
mv Step2mumu_hist_TTWJetsToQQ.root            mumu_hist_TTWJetsToQQ.root 
mv Step2mumu_hist_TTZToLLNuNu.root            mumu_hist_TTZToLLNuNu.root 
mv Step2mumu_hist_TTZToQQ.root                mumu_hist_TTZToQQ.root 
mv Step2mumu_hist_TW_antitop.root             mumu_hist_TW_antitop.root 
mv Step2mumu_hist_TW_top.root                 mumu_hist_TW_top.root 
mv Step2mumu_hist_WG_LNuG.root                mumu_hist_WG_LNuG.root 
mv Step2mumu_hist_WJet_mad.root               mumu_hist_WJet_mad.root 
mv Step2mumu_hist_WWTo2L2Nu.root              mumu_hist_WWTo2L2Nu.root 
mv Step2mumu_hist_WZ_2L2Q.root                mumu_hist_WZ_2L2Q.root 
mv Step2mumu_hist_WZ_3LNu.root                mumu_hist_WZ_3LNu.root 
mv Step2mumu_hist_ZZTo4L.root                 mumu_hist_ZZTo4L.root 
mv Step2mumu_hist_ZZ_2L2Nu.root               mumu_hist_ZZ_2L2Nu.root 
