// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Mon Jun 26 12:20:14 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA_FastSim/Wtb_emu
Training events: 110000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "10" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0055809021,852.089233398]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.0963261649013,887.121398926]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000289916992188,816.782104492]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.004940033,1418.5065918]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.174523547292,0.999993979931]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.21769297123,1165.82104492]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.0256627257913,8.73527812958]
M_l2_j1                       M_l2_j1                       M_l2_j1                       M_l2_j1                                                         'F'    [0.000510941667017,1629.87402344]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.163817852736,0.999999403954]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "PT_ll_j1", "deltaR_ll_j1", "M_l2_j1", "C_l1_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.674330509386244;
   fWeightMatrix0to1[1][0] = 0.190757661616635;
   fWeightMatrix0to1[2][0] = 1.8775529125297;
   fWeightMatrix0to1[3][0] = 2.01323078248514;
   fWeightMatrix0to1[4][0] = -1.32104765858961;
   fWeightMatrix0to1[5][0] = 0.549998738043418;
   fWeightMatrix0to1[6][0] = 0.0466821791696727;
   fWeightMatrix0to1[7][0] = 1.01266690311897;
   fWeightMatrix0to1[8][0] = -0.902889897795647;
   fWeightMatrix0to1[9][0] = -1.17319514245928;
   fWeightMatrix0to1[0][1] = -0.301489817973973;
   fWeightMatrix0to1[1][1] = 1.24651059075477;
   fWeightMatrix0to1[2][1] = -0.853627682255799;
   fWeightMatrix0to1[3][1] = -0.469348023976628;
   fWeightMatrix0to1[4][1] = 2.66850635239874;
   fWeightMatrix0to1[5][1] = -1.3736889463055;
   fWeightMatrix0to1[6][1] = 0.283575010246115;
   fWeightMatrix0to1[7][1] = 2.21731630445205;
   fWeightMatrix0to1[8][1] = 0.279504637087219;
   fWeightMatrix0to1[9][1] = 1.53283951493238;
   fWeightMatrix0to1[0][2] = 0.452052711170392;
   fWeightMatrix0to1[1][2] = -1.30959891985963;
   fWeightMatrix0to1[2][2] = 1.77282000689106;
   fWeightMatrix0to1[3][2] = 0.288879255360596;
   fWeightMatrix0to1[4][2] = -0.355712643932762;
   fWeightMatrix0to1[5][2] = 0.605249733815784;
   fWeightMatrix0to1[6][2] = 2.41522219244239;
   fWeightMatrix0to1[7][2] = -1.08035294255102;
   fWeightMatrix0to1[8][2] = -1.34807651831993;
   fWeightMatrix0to1[9][2] = 0.107338719068743;
   fWeightMatrix0to1[0][3] = 1.4767256736687;
   fWeightMatrix0to1[1][3] = -0.435311461852091;
   fWeightMatrix0to1[2][3] = 0.59057062486135;
   fWeightMatrix0to1[3][3] = -0.0936037468953375;
   fWeightMatrix0to1[4][3] = 0.105192651827672;
   fWeightMatrix0to1[5][3] = 3.29861143304349;
   fWeightMatrix0to1[6][3] = -0.553042566021526;
   fWeightMatrix0to1[7][3] = 3.66842336518564;
   fWeightMatrix0to1[8][3] = -0.529442419522615;
   fWeightMatrix0to1[9][3] = 1.02874524987063;
   fWeightMatrix0to1[0][4] = 0.883979867976359;
   fWeightMatrix0to1[1][4] = -0.947023630293477;
   fWeightMatrix0to1[2][4] = 0.738399631691663;
   fWeightMatrix0to1[3][4] = 1.58469094347724;
   fWeightMatrix0to1[4][4] = -0.392711341419495;
   fWeightMatrix0to1[5][4] = -0.852097399228107;
   fWeightMatrix0to1[6][4] = 0.635850685759142;
   fWeightMatrix0to1[7][4] = 0.085768561167094;
   fWeightMatrix0to1[8][4] = 1.58834504252892;
   fWeightMatrix0to1[9][4] = 0.818581869129243;
   fWeightMatrix0to1[0][5] = 2.24315883832734;
   fWeightMatrix0to1[1][5] = 3.77991940576658;
   fWeightMatrix0to1[2][5] = -0.965211602958708;
   fWeightMatrix0to1[3][5] = 0.807364965848936;
   fWeightMatrix0to1[4][5] = -0.280563777780227;
   fWeightMatrix0to1[5][5] = -5.00997055406198;
   fWeightMatrix0to1[6][5] = -0.470765333476045;
   fWeightMatrix0to1[7][5] = -5.37050908158271;
   fWeightMatrix0to1[8][5] = 1.69503334614885;
   fWeightMatrix0to1[9][5] = 1.02465922339222;
   fWeightMatrix0to1[0][6] = -0.815574184742288;
   fWeightMatrix0to1[1][6] = 1.51977218503492;
   fWeightMatrix0to1[2][6] = 0.271680573485232;
   fWeightMatrix0to1[3][6] = 0.836307716878563;
   fWeightMatrix0to1[4][6] = 1.41177756204118;
   fWeightMatrix0to1[5][6] = -1.87760034744334;
   fWeightMatrix0to1[6][6] = 0.533689010128547;
   fWeightMatrix0to1[7][6] = -1.07328290299031;
   fWeightMatrix0to1[8][6] = 1.11275428203351;
   fWeightMatrix0to1[9][6] = -0.834895141015968;
   fWeightMatrix0to1[0][7] = 0.254718017050988;
   fWeightMatrix0to1[1][7] = -0.110193661155717;
   fWeightMatrix0to1[2][7] = 1.42209061672742;
   fWeightMatrix0to1[3][7] = 0.721828504826092;
   fWeightMatrix0to1[4][7] = 2.17070899151626;
   fWeightMatrix0to1[5][7] = -1.95770688501585;
   fWeightMatrix0to1[6][7] = -1.04399145777674;
   fWeightMatrix0to1[7][7] = -1.30185090459292;
   fWeightMatrix0to1[8][7] = 1.49137773059248;
   fWeightMatrix0to1[9][7] = 0.77584288170959;
   fWeightMatrix0to1[0][8] = 2.21939849589763;
   fWeightMatrix0to1[1][8] = 0.296263323355218;
   fWeightMatrix0to1[2][8] = -0.342675865164711;
   fWeightMatrix0to1[3][8] = -1.12340182255565;
   fWeightMatrix0to1[4][8] = 1.40924174257295;
   fWeightMatrix0to1[5][8] = -0.310295072336739;
   fWeightMatrix0to1[6][8] = 0.802126606619804;
   fWeightMatrix0to1[7][8] = -0.125951682334932;
   fWeightMatrix0to1[8][8] = -1.94301465246885;
   fWeightMatrix0to1[9][8] = -1.49924733878186;
   fWeightMatrix0to1[0][9] = -0.631507807204221;
   fWeightMatrix0to1[1][9] = 0.6702142219028;
   fWeightMatrix0to1[2][9] = 0.326911362629736;
   fWeightMatrix0to1[3][9] = -1.37285767673212;
   fWeightMatrix0to1[4][9] = 0.373353088417002;
   fWeightMatrix0to1[5][9] = -0.629030822810296;
   fWeightMatrix0to1[6][9] = -1.91265958461923;
   fWeightMatrix0to1[7][9] = -1.44397892239628;
   fWeightMatrix0to1[8][9] = -2.29114591911898;
   fWeightMatrix0to1[9][9] = -0.0161181822529262;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.563470521521286;
   fWeightMatrix1to2[0][1] = -2.69940648452763;
   fWeightMatrix1to2[0][2] = 0.726782747979844;
   fWeightMatrix1to2[0][3] = 1.85673796110435;
   fWeightMatrix1to2[0][4] = -0.758036392481879;
   fWeightMatrix1to2[0][5] = 4.06882514860168;
   fWeightMatrix1to2[0][6] = -0.120095763579117;
   fWeightMatrix1to2[0][7] = -1.80510043469034;
   fWeightMatrix1to2[0][8] = 0.457093843918326;
   fWeightMatrix1to2[0][9] = -0.521647366167487;
   fWeightMatrix1to2[0][10] = -2.86881543676886;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.080581665;
   fMax_1[0][0] = 534.578308105;
   fMin_1[1][0] = 25.0055809021;
   fMax_1[1][0] = 852.089233398;
   fMin_1[2][0] = 25.0055809021;
   fMax_1[2][0] = 852.089233398;
   fMin_1[0][1] = 0.770670294762;
   fMax_1[0][1] = 513.678527832;
   fMin_1[1][1] = 0.0963261649013;
   fMax_1[1][1] = 887.121398926;
   fMin_1[2][1] = 0.0963261649013;
   fMax_1[2][1] = 887.121398926;
   fMin_1[0][2] = 0.00276565551758;
   fMax_1[0][2] = 505.124816895;
   fMin_1[1][2] = 0.000289916992188;
   fMax_1[1][2] = 816.782104492;
   fMin_1[2][2] = 0.000289916992188;
   fMax_1[2][2] = 816.782104492;
   fMin_1[0][3] = 20.0086517334;
   fMax_1[0][3] = 994.935546875;
   fMin_1[1][3] = 20.004940033;
   fMax_1[1][3] = 1418.5065918;
   fMin_1[2][3] = 20.004940033;
   fMax_1[2][3] = 1418.5065918;
   fMin_1[0][4] = 0.177344366908;
   fMax_1[0][4] = 0.99997395277;
   fMin_1[1][4] = 0.174523547292;
   fMax_1[1][4] = 0.999993979931;
   fMin_1[2][4] = 0.174523547292;
   fMax_1[2][4] = 0.999993979931;
   fMin_1[0][5] = 0.70489615202;
   fMax_1[0][5] = 512.372924805;
   fMin_1[1][5] = 0.21769297123;
   fMax_1[1][5] = 1165.82104492;
   fMin_1[2][5] = 0.21769297123;
   fMax_1[2][5] = 1165.82104492;
   fMin_1[0][6] = 0.0625614002347;
   fMax_1[0][6] = 8.73527812958;
   fMin_1[1][6] = 0.0256627257913;
   fMax_1[1][6] = 8.06768989563;
   fMin_1[2][6] = 0.0256627257913;
   fMax_1[2][6] = 8.73527812958;
   fMin_1[0][7] = 0.000510984333232;
   fMax_1[0][7] = 1014.1293335;
   fMin_1[1][7] = 0.000510941667017;
   fMax_1[1][7] = 1629.87402344;
   fMin_1[2][7] = 0.000510941667017;
   fMax_1[2][7] = 1629.87402344;
   fMin_1[0][8] = 0.16845291853;
   fMax_1[0][8] = 0.999997019768;
   fMin_1[1][8] = 0.163817852736;
   fMax_1[1][8] = 0.999999403954;
   fMin_1[2][8] = 0.163817852736;
   fMax_1[2][8] = 0.999999403954;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
