// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Tue Aug  1 12:30:41 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA/Samples_inclusive/SF/1j1b
Training events: 17399
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "800" [Number of training cycles]
HiddenLayers: "12" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
PT_Loose_jet                  PT_Loose_jet                  PT_Loose_jet                  PT_Loose_jet                                                    'F'    [0,29.9969654083]
n_Loose_bjet                  n_Loose_bjet                  n_Loose_bjet                  n_Loose_bjet                                                    'I'    [0,2]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.565062522888,556.56048584]
deltaR_l1_j1                  deltaR_l1_j1                  deltaR_l1_j1                  deltaR_l1_j1                                                    'F'    [0.375886231661,5.15556621552]
deltaR_ll                     deltaR_ll                     deltaR_ll                     deltaR_ll                                                       'F'    [0.303897827864,5.20632982254]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [0.00124875630718,3.1414411068]
C_ll_j1                       C_ll_j1                       C_ll_j1                       C_ll_j1                                                         'F'    [0.189017221332,0.999015450478]
PT_ll_MET_j1                  PT_ll_MET_j1                  PT_ll_MET_j1                  PT_ll_MET_j1                                                    'F'    [0.681292653084,499.406341553]
PT_l1j1                       PT_l1j1                       PT_l1j1                       PT_l1j1                                                         'F'    [0.963986515999,663.920410156]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0043106079,962.546264648]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "PT_Loose_jet", "n_Loose_bjet", "PT_ll_j1", "deltaR_l1_j1", "deltaR_ll", "delta_phi_ll_j1", "C_ll_j1", "PT_ll_MET_j1", "PT_l1j1", "M_ll" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[13][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.023301213257202;
   fWeightMatrix0to1[1][0] = 1.94362583058581;
   fWeightMatrix0to1[2][0] = 1.43172244993596;
   fWeightMatrix0to1[3][0] = 1.91153453689215;
   fWeightMatrix0to1[4][0] = -1.99874479981652;
   fWeightMatrix0to1[5][0] = -1.11025884970651;
   fWeightMatrix0to1[6][0] = -0.763735360937195;
   fWeightMatrix0to1[7][0] = -0.07996597699366;
   fWeightMatrix0to1[8][0] = 0.074869612952539;
   fWeightMatrix0to1[9][0] = -0.736868606672215;
   fWeightMatrix0to1[10][0] = -1.24052217277516;
   fWeightMatrix0to1[11][0] = -1.23224598611462;
   fWeightMatrix0to1[0][1] = -7.45026532138497;
   fWeightMatrix0to1[1][1] = 1.40411329369759;
   fWeightMatrix0to1[2][1] = -0.31896256579783;
   fWeightMatrix0to1[3][1] = 1.13919371551119;
   fWeightMatrix0to1[4][1] = 2.76856247481782;
   fWeightMatrix0to1[5][1] = 4.48535691865677;
   fWeightMatrix0to1[6][1] = 0.770386873979979;
   fWeightMatrix0to1[7][1] = 1.57410077317471;
   fWeightMatrix0to1[8][1] = 0.109683495499244;
   fWeightMatrix0to1[9][1] = 0.125067647509578;
   fWeightMatrix0to1[10][1] = 2.24640620882384;
   fWeightMatrix0to1[11][1] = 1.2969423147148;
   fWeightMatrix0to1[0][2] = 7.78362947328868;
   fWeightMatrix0to1[1][2] = -2.99333492907645;
   fWeightMatrix0to1[2][2] = 5.49201816346609;
   fWeightMatrix0to1[3][2] = 0.906660036351099;
   fWeightMatrix0to1[4][2] = 1.85244146865823;
   fWeightMatrix0to1[5][2] = -0.520533912102255;
   fWeightMatrix0to1[6][2] = 2.24244319516043;
   fWeightMatrix0to1[7][2] = 2.39614625051999;
   fWeightMatrix0to1[8][2] = -0.80118332292471;
   fWeightMatrix0to1[9][2] = 3.3578094406389;
   fWeightMatrix0to1[10][2] = -0.674010410999553;
   fWeightMatrix0to1[11][2] = -8.71058381499601;
   fWeightMatrix0to1[0][3] = 0.427938974091365;
   fWeightMatrix0to1[1][3] = 4.96016741654088;
   fWeightMatrix0to1[2][3] = -1.46990591605769;
   fWeightMatrix0to1[3][3] = 1.8969412252506;
   fWeightMatrix0to1[4][3] = 2.16312411770272;
   fWeightMatrix0to1[5][3] = 2.61549336734761;
   fWeightMatrix0to1[6][3] = 3.35830063071367;
   fWeightMatrix0to1[7][3] = 2.20112846874348;
   fWeightMatrix0to1[8][3] = 3.8029140840649;
   fWeightMatrix0to1[9][3] = 1.29303280452613;
   fWeightMatrix0to1[10][3] = 0.572372853789963;
   fWeightMatrix0to1[11][3] = 3.38631954479468;
   fWeightMatrix0to1[0][4] = 1.23702554044268;
   fWeightMatrix0to1[1][4] = 0.735658265575242;
   fWeightMatrix0to1[2][4] = 1.18356562998839;
   fWeightMatrix0to1[3][4] = 1.20028156842128;
   fWeightMatrix0to1[4][4] = -2.38035602608191;
   fWeightMatrix0to1[5][4] = 3.33672850411044;
   fWeightMatrix0to1[6][4] = -2.32850209768308;
   fWeightMatrix0to1[7][4] = -0.477431583775866;
   fWeightMatrix0to1[8][4] = -2.30789421889971;
   fWeightMatrix0to1[9][4] = -7.08188467308904;
   fWeightMatrix0to1[10][4] = 2.22777765604512;
   fWeightMatrix0to1[11][4] = 1.95186607286454;
   fWeightMatrix0to1[0][5] = -2.00250206407016;
   fWeightMatrix0to1[1][5] = -0.242260831643977;
   fWeightMatrix0to1[2][5] = -0.926698987166357;
   fWeightMatrix0to1[3][5] = -0.921695425971996;
   fWeightMatrix0to1[4][5] = 3.95754126590416;
   fWeightMatrix0to1[5][5] = -0.108590237441751;
   fWeightMatrix0to1[6][5] = 0.669426489937037;
   fWeightMatrix0to1[7][5] = 1.35160452233795;
   fWeightMatrix0to1[8][5] = 0.811155948795783;
   fWeightMatrix0to1[9][5] = -0.459115441511903;
   fWeightMatrix0to1[10][5] = -0.171038943245041;
   fWeightMatrix0to1[11][5] = -0.0303161924892949;
   fWeightMatrix0to1[0][6] = 1.4265634901767;
   fWeightMatrix0to1[1][6] = 2.54874357541023;
   fWeightMatrix0to1[2][6] = -1.59131530712185;
   fWeightMatrix0to1[3][6] = -2.12886888366299;
   fWeightMatrix0to1[4][6] = -1.6061585590364;
   fWeightMatrix0to1[5][6] = 0.202372162652282;
   fWeightMatrix0to1[6][6] = 3.67261104829084;
   fWeightMatrix0to1[7][6] = 3.21631012640725;
   fWeightMatrix0to1[8][6] = 1.20984716948971;
   fWeightMatrix0to1[9][6] = -2.77701808914235;
   fWeightMatrix0to1[10][6] = 1.42044230644845;
   fWeightMatrix0to1[11][6] = 0.273154262715115;
   fWeightMatrix0to1[0][7] = -6.45743968895304;
   fWeightMatrix0to1[1][7] = 0.616783289989797;
   fWeightMatrix0to1[2][7] = 2.24455883359578;
   fWeightMatrix0to1[3][7] = -1.90953352979081;
   fWeightMatrix0to1[4][7] = -0.06799617424933;
   fWeightMatrix0to1[5][7] = 0.521392237525773;
   fWeightMatrix0to1[6][7] = 2.37938400489512;
   fWeightMatrix0to1[7][7] = 1.5128496939961;
   fWeightMatrix0to1[8][7] = 6.25874357884527;
   fWeightMatrix0to1[9][7] = 0.480045976262278;
   fWeightMatrix0to1[10][7] = -0.394180216237815;
   fWeightMatrix0to1[11][7] = 4.55248156341261;
   fWeightMatrix0to1[0][8] = -5.41074683649643;
   fWeightMatrix0to1[1][8] = -2.45055904403669;
   fWeightMatrix0to1[2][8] = -0.940031065316757;
   fWeightMatrix0to1[3][8] = -1.00486833570847;
   fWeightMatrix0to1[4][8] = 1.11286005089935;
   fWeightMatrix0to1[5][8] = -0.379871639589914;
   fWeightMatrix0to1[6][8] = -1.07257221777037;
   fWeightMatrix0to1[7][8] = 2.54637375699501;
   fWeightMatrix0to1[8][8] = -3.69673405150544;
   fWeightMatrix0to1[9][8] = -1.18028798513341;
   fWeightMatrix0to1[10][8] = -1.1389684415513;
   fWeightMatrix0to1[11][8] = 3.84662265815773;
   fWeightMatrix0to1[0][9] = 8.36654865256403;
   fWeightMatrix0to1[1][9] = 1.06746981323651;
   fWeightMatrix0to1[2][9] = -4.48415709376307;
   fWeightMatrix0to1[3][9] = 0.894453872560714;
   fWeightMatrix0to1[4][9] = 1.76745017212765;
   fWeightMatrix0to1[5][9] = -0.567931830427046;
   fWeightMatrix0to1[6][9] = 0.67999582520677;
   fWeightMatrix0to1[7][9] = 2.2233606299273;
   fWeightMatrix0to1[8][9] = 1.6060647267195;
   fWeightMatrix0to1[9][9] = -1.09437284685527;
   fWeightMatrix0to1[10][9] = 5.36898126523863;
   fWeightMatrix0to1[11][9] = -8.31410547205836;
   fWeightMatrix0to1[0][10] = -2.76650840390124;
   fWeightMatrix0to1[1][10] = -4.192381502164;
   fWeightMatrix0to1[2][10] = 1.15626372876368;
   fWeightMatrix0to1[3][10] = 0.730872836961708;
   fWeightMatrix0to1[4][10] = -2.25579124313961;
   fWeightMatrix0to1[5][10] = -0.192559424523385;
   fWeightMatrix0to1[6][10] = -3.25179524800677;
   fWeightMatrix0to1[7][10] = 1.6930058450588;
   fWeightMatrix0to1[8][10] = -3.16370938176141;
   fWeightMatrix0to1[9][10] = -2.71356623891879;
   fWeightMatrix0to1[10][10] = 0.883941436709893;
   fWeightMatrix0to1[11][10] = -7.94916721691748;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.66147940337727;
   fWeightMatrix1to2[0][1] = -2.12773725835682;
   fWeightMatrix1to2[0][2] = -1.94807431933702;
   fWeightMatrix1to2[0][3] = 0.282872328292936;
   fWeightMatrix1to2[0][4] = -4.10467424831592;
   fWeightMatrix1to2[0][5] = 2.91514155988682;
   fWeightMatrix1to2[0][6] = 3.18126727399587;
   fWeightMatrix1to2[0][7] = 4.20402609530833;
   fWeightMatrix1to2[0][8] = 6.85195715129921;
   fWeightMatrix1to2[0][9] = 1.2302270467233;
   fWeightMatrix1to2[0][10] = -2.64338530428303;
   fWeightMatrix1to2[0][11] = -3.23270864808436;
   fWeightMatrix1to2[0][12] = -0.0364868358592745;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 29.9940757751;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 29.9969654083;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 29.9969654083;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 2;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 2;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 2;
   fMin_1[0][2] = 1.60742425919;
   fMax_1[0][2] = 556.56048584;
   fMin_1[1][2] = 0.565062522888;
   fMax_1[1][2] = 362.223083496;
   fMin_1[2][2] = 0.565062522888;
   fMax_1[2][2] = 556.56048584;
   fMin_1[0][3] = 0.418521910906;
   fMax_1[0][3] = 5.15556621552;
   fMin_1[1][3] = 0.375886231661;
   fMax_1[1][3] = 5.08745718002;
   fMin_1[2][3] = 0.375886231661;
   fMax_1[2][3] = 5.15556621552;
   fMin_1[0][4] = 0.303897827864;
   fMax_1[0][4] = 5.20632982254;
   fMin_1[1][4] = 0.317192107439;
   fMax_1[1][4] = 5.09328269958;
   fMin_1[2][4] = 0.303897827864;
   fMax_1[2][4] = 5.20632982254;
   fMin_1[0][5] = 0.00124875630718;
   fMax_1[0][5] = 3.14127492905;
   fMin_1[1][5] = 0.00169087143149;
   fMax_1[1][5] = 3.1414411068;
   fMin_1[2][5] = 0.00124875630718;
   fMax_1[2][5] = 3.1414411068;
   fMin_1[0][6] = 0.199318110943;
   fMax_1[0][6] = 0.999015450478;
   fMin_1[1][6] = 0.189017221332;
   fMax_1[1][6] = 0.994832634926;
   fMin_1[2][6] = 0.189017221332;
   fMax_1[2][6] = 0.999015450478;
   fMin_1[0][7] = 0.681292653084;
   fMax_1[0][7] = 479.40737915;
   fMin_1[1][7] = 0.697438776493;
   fMax_1[1][7] = 499.406341553;
   fMin_1[2][7] = 0.681292653084;
   fMax_1[2][7] = 499.406341553;
   fMin_1[0][8] = 0.963986515999;
   fMax_1[0][8] = 663.920410156;
   fMin_1[1][8] = 0.972103118896;
   fMax_1[1][8] = 460.322723389;
   fMin_1[2][8] = 0.963986515999;
   fMax_1[2][8] = 663.920410156;
   fMin_1[0][9] = 20.0523338318;
   fMax_1[0][9] = 930.746765137;
   fMin_1[1][9] = 20.0043106079;
   fMax_1[1][9] = 962.546264648;
   fMin_1[2][9] = 20.0043106079;
   fMax_1[2][9] = 962.546264648;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
