// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Thu Jun  7 16:52:34 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_9_2_6/src/2016_ALL/tW/tw_74/TMVA/Samples_norminal/0j0b
Training events: 165453
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "700" [Number of training cycles]
HiddenLayers: "15" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0013332367,620.583190918]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.056717440486,551.198669434]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000259399414062,548.250854492]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0032939911,1501.83654785]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.169171392918,0.999989390373]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.550343350300917;
   fWeightMatrix0to1[1][0] = 2.04888105570958;
   fWeightMatrix0to1[2][0] = 0.6582453765644;
   fWeightMatrix0to1[3][0] = 1.42210520666147;
   fWeightMatrix0to1[4][0] = -1.57382578675868;
   fWeightMatrix0to1[5][0] = -0.287339078773927;
   fWeightMatrix0to1[6][0] = -0.0519468780638779;
   fWeightMatrix0to1[7][0] = 2.37525047150879;
   fWeightMatrix0to1[8][0] = -1.98579811136447;
   fWeightMatrix0to1[9][0] = -0.490448019529116;
   fWeightMatrix0to1[10][0] = -7.18566359266364;
   fWeightMatrix0to1[11][0] = 0.232119185181902;
   fWeightMatrix0to1[12][0] = -1.04184674878701;
   fWeightMatrix0to1[13][0] = -0.231307934236601;
   fWeightMatrix0to1[14][0] = -1.659694084335;
   fWeightMatrix0to1[0][1] = 1.9159340385076;
   fWeightMatrix0to1[1][1] = -0.406699118859839;
   fWeightMatrix0to1[2][1] = 1.42782211599321;
   fWeightMatrix0to1[3][1] = 2.08082499994096;
   fWeightMatrix0to1[4][1] = 1.61903094280745;
   fWeightMatrix0to1[5][1] = 0.517675746386528;
   fWeightMatrix0to1[6][1] = -0.240148596211318;
   fWeightMatrix0to1[7][1] = 1.02378695632629;
   fWeightMatrix0to1[8][1] = -2.70643499563805;
   fWeightMatrix0to1[9][1] = -0.974455934229047;
   fWeightMatrix0to1[10][1] = -14.7171775360915;
   fWeightMatrix0to1[11][1] = 1.9923078196843;
   fWeightMatrix0to1[12][1] = -0.687160816699317;
   fWeightMatrix0to1[13][1] = -1.4025129020058;
   fWeightMatrix0to1[14][1] = -2.37010570189495;
   fWeightMatrix0to1[0][2] = 1.09749248781228;
   fWeightMatrix0to1[1][2] = 1.65477275908045;
   fWeightMatrix0to1[2][2] = -0.155824135474565;
   fWeightMatrix0to1[3][2] = -3.52072068700158;
   fWeightMatrix0to1[4][2] = 0.706581753450205;
   fWeightMatrix0to1[5][2] = 1.22587066984995;
   fWeightMatrix0to1[6][2] = -0.870573766898855;
   fWeightMatrix0to1[7][2] = 1.39374783831316;
   fWeightMatrix0to1[8][2] = -1.03726593411522;
   fWeightMatrix0to1[9][2] = 2.07209454384429;
   fWeightMatrix0to1[10][2] = 9.26383461615213;
   fWeightMatrix0to1[11][2] = 1.63148188662377;
   fWeightMatrix0to1[12][2] = 2.36879849299159;
   fWeightMatrix0to1[13][2] = 1.71435046753824;
   fWeightMatrix0to1[14][2] = -0.579028351978762;
   fWeightMatrix0to1[0][3] = -0.42141070891766;
   fWeightMatrix0to1[1][3] = 0.775404569847188;
   fWeightMatrix0to1[2][3] = 0.129996453652945;
   fWeightMatrix0to1[3][3] = 3.14747325372068;
   fWeightMatrix0to1[4][3] = 2.08619315265991;
   fWeightMatrix0to1[5][3] = 2.72713515518918;
   fWeightMatrix0to1[6][3] = 2.15246113367873;
   fWeightMatrix0to1[7][3] = -1.44538078448844;
   fWeightMatrix0to1[8][3] = 1.3940914950663;
   fWeightMatrix0to1[9][3] = -0.994058659373304;
   fWeightMatrix0to1[10][3] = -11.6253868671444;
   fWeightMatrix0to1[11][3] = -0.235987245789838;
   fWeightMatrix0to1[12][3] = -1.71308670076106;
   fWeightMatrix0to1[13][3] = 1.8962965384561;
   fWeightMatrix0to1[14][3] = 0.808015103899698;
   fWeightMatrix0to1[0][4] = -1.57276180045525;
   fWeightMatrix0to1[1][4] = 0.362672777804375;
   fWeightMatrix0to1[2][4] = 0.973437588294297;
   fWeightMatrix0to1[3][4] = -0.429306989480068;
   fWeightMatrix0to1[4][4] = 2.04736030071344;
   fWeightMatrix0to1[5][4] = -0.0976100256506065;
   fWeightMatrix0to1[6][4] = -0.632805657488237;
   fWeightMatrix0to1[7][4] = -1.75820829073721;
   fWeightMatrix0to1[8][4] = -3.80619714525002;
   fWeightMatrix0to1[9][4] = -0.639402555879648;
   fWeightMatrix0to1[10][4] = 0.128342008514138;
   fWeightMatrix0to1[11][4] = -1.04491605225126;
   fWeightMatrix0to1[12][4] = 0.868505073198083;
   fWeightMatrix0to1[13][4] = 0.301488850071483;
   fWeightMatrix0to1[14][4] = 0.351305721554261;
   fWeightMatrix0to1[0][5] = -1.45616345643621;
   fWeightMatrix0to1[1][5] = -1.84489258774226;
   fWeightMatrix0to1[2][5] = -2.01460596204244;
   fWeightMatrix0to1[3][5] = 1.81027133232142;
   fWeightMatrix0to1[4][5] = -0.339846470993547;
   fWeightMatrix0to1[5][5] = 1.03068223022367;
   fWeightMatrix0to1[6][5] = -1.52010624733748;
   fWeightMatrix0to1[7][5] = 1.16525726079799;
   fWeightMatrix0to1[8][5] = -8.44947850722379;
   fWeightMatrix0to1[9][5] = -3.65855668947912;
   fWeightMatrix0to1[10][5] = -24.4742333386824;
   fWeightMatrix0to1[11][5] = -0.455358716184746;
   fWeightMatrix0to1[12][5] = -2.4801242397881;
   fWeightMatrix0to1[13][5] = -1.43430483251177;
   fWeightMatrix0to1[14][5] = -5.09717550095469;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.517215257153581;
   fWeightMatrix1to2[0][1] = -0.57222022459368;
   fWeightMatrix1to2[0][2] = 0.974921696959499;
   fWeightMatrix1to2[0][3] = -0.790855055658151;
   fWeightMatrix1to2[0][4] = 0.447884431976741;
   fWeightMatrix1to2[0][5] = 0.204762765616866;
   fWeightMatrix1to2[0][6] = -0.296558865945;
   fWeightMatrix1to2[0][7] = 0.340623969432228;
   fWeightMatrix1to2[0][8] = -3.15752396318829;
   fWeightMatrix1to2[0][9] = 0.060320297697253;
   fWeightMatrix1to2[0][10] = -13.7905219277781;
   fWeightMatrix1to2[0][11] = -0.702037909523762;
   fWeightMatrix1to2[0][12] = 0.70407998600129;
   fWeightMatrix1to2[0][13] = 1.65444701874346;
   fWeightMatrix1to2[0][14] = -1.88028889584559;
   fWeightMatrix1to2[0][15] = 0.825300882592937;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0222377777;
   fMax_1[0][0] = 512.669006348;
   fMin_1[1][0] = 25.0013332367;
   fMax_1[1][0] = 620.583190918;
   fMin_1[2][0] = 25.0013332367;
   fMax_1[2][0] = 620.583190918;
   fMin_1[0][1] = 0.786144018173;
   fMax_1[0][1] = 364.788787842;
   fMin_1[1][1] = 0.056717440486;
   fMax_1[1][1] = 551.198669434;
   fMin_1[2][1] = 0.056717440486;
   fMax_1[2][1] = 551.198669434;
   fMin_1[0][2] = 0.00424385070801;
   fMax_1[0][2] = 359.307250977;
   fMin_1[1][2] = 0.000259399414062;
   fMax_1[1][2] = 548.250854492;
   fMin_1[2][2] = 0.000259399414062;
   fMax_1[2][2] = 548.250854492;
   fMin_1[0][3] = 20.037935257;
   fMax_1[0][3] = 1080.22216797;
   fMin_1[1][3] = 20.0032939911;
   fMax_1[1][3] = 1501.83654785;
   fMin_1[2][3] = 20.0032939911;
   fMax_1[2][3] = 1501.83654785;
   fMin_1[0][4] = 0.174664929509;
   fMax_1[0][4] = 0.999980330467;
   fMin_1[1][4] = 0.169171392918;
   fMax_1[1][4] = 0.999989390373;
   fMin_1[2][4] = 0.169171392918;
   fMax_1[2][4] = 0.999989390373;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
