// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Mon Jun 19 14:20:46 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA/2j1b
Training events: 547715
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "900" [Number of training cycles]
HiddenLayers: "18" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
n_Loose_jet                   n_Loose_jet                   n_Loose_jet                   n_Loose_jet                                                     'I'    [0,8]
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0005073547,998.587646484]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.0516224987805,970.948669434]
PT_j2                         PT_j2                         PT_j2                         PT_j2                                                           'F'    [30.0000267029,561.957702637]
delta_PT_l2_j2                delta_PT_l2_j2                delta_PT_l2_j2                delta_PT_l2_j2                                                  'F'    [-500.947631836,419.442810059]
deltaR_l1_j2                  deltaR_l1_j2                  deltaR_l1_j2                  deltaR_l1_j2                                                    'F'    [0.344126969576,5.69235515594]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.0015413404908,7.65327262878]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [1.11123727038e-05,3.14158844948]
M_l1_j2                       M_l1_j2                       M_l1_j2                       M_l1_j2                                                         'F'    [11.8967847824,1492.41296387]
M_j1_j2                       M_j1_j2                       M_j1_j2                       M_j1_j2                                                         'F'    [13.2539606094,2406.51904297]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "n_Loose_jet", "leading_pt", "PT_ll", "PT_j2", "delta_PT_l2_j2", "deltaR_l1_j2", "deltaR_ll_j1", "delta_phi_ll_j1", "M_l1_j2", "M_j1_j2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.236977883962978;
   fWeightMatrix0to1[1][0] = 1.17285811428342;
   fWeightMatrix0to1[2][0] = 1.35786355094671;
   fWeightMatrix0to1[3][0] = 1.86619960651351;
   fWeightMatrix0to1[4][0] = -0.972197780564775;
   fWeightMatrix0to1[5][0] = -0.362208331627294;
   fWeightMatrix0to1[6][0] = 0.276348226513803;
   fWeightMatrix0to1[7][0] = 3.63184737054368;
   fWeightMatrix0to1[8][0] = -2.07755845650031;
   fWeightMatrix0to1[9][0] = -0.577747240954555;
   fWeightMatrix0to1[10][0] = -0.875798298915475;
   fWeightMatrix0to1[11][0] = 0.266722542662776;
   fWeightMatrix0to1[12][0] = -1.46146107351408;
   fWeightMatrix0to1[13][0] = 0.308936100444961;
   fWeightMatrix0to1[14][0] = 0.819857125627469;
   fWeightMatrix0to1[15][0] = 1.09957747106009;
   fWeightMatrix0to1[16][0] = -0.15781105914064;
   fWeightMatrix0to1[17][0] = -0.902750373123351;
   fWeightMatrix0to1[0][1] = 0.866314386034129;
   fWeightMatrix0to1[1][1] = 0.928810949240355;
   fWeightMatrix0to1[2][1] = -0.92783949361369;
   fWeightMatrix0to1[3][1] = -3.17147156746728;
   fWeightMatrix0to1[4][1] = 3.7423141579919;
   fWeightMatrix0to1[5][1] = -1.56681452747098;
   fWeightMatrix0to1[6][1] = -0.243522280059528;
   fWeightMatrix0to1[7][1] = 1.01702244299375;
   fWeightMatrix0to1[8][1] = 0.0445738553076347;
   fWeightMatrix0to1[9][1] = -0.578984213327694;
   fWeightMatrix0to1[10][1] = 1.4866784091188;
   fWeightMatrix0to1[11][1] = 0.955996420439335;
   fWeightMatrix0to1[12][1] = -0.0231688319632643;
   fWeightMatrix0to1[13][1] = 4.2622026202555;
   fWeightMatrix0to1[14][1] = -0.472065540316797;
   fWeightMatrix0to1[15][1] = 0.121381746366123;
   fWeightMatrix0to1[16][1] = -0.466487460205732;
   fWeightMatrix0to1[17][1] = 0.449610576575068;
   fWeightMatrix0to1[0][2] = -2.72821849382135;
   fWeightMatrix0to1[1][2] = 1.16449796205122;
   fWeightMatrix0to1[2][2] = -0.918261154138655;
   fWeightMatrix0to1[3][2] = 2.19511030566177;
   fWeightMatrix0to1[4][2] = 0.272976479969616;
   fWeightMatrix0to1[5][2] = 0.0571833975997314;
   fWeightMatrix0to1[6][2] = 2.9703558936956;
   fWeightMatrix0to1[7][2] = 0.835623413456504;
   fWeightMatrix0to1[8][2] = 1.62513896582388;
   fWeightMatrix0to1[9][2] = -1.63785371791739;
   fWeightMatrix0to1[10][2] = 0.752399805190641;
   fWeightMatrix0to1[11][2] = 0.182205722157508;
   fWeightMatrix0to1[12][2] = 3.08853158231354;
   fWeightMatrix0to1[13][2] = -1.74023345200169;
   fWeightMatrix0to1[14][2] = 0.805827712799125;
   fWeightMatrix0to1[15][2] = 2.15333998308133;
   fWeightMatrix0to1[16][2] = -1.62168229457541;
   fWeightMatrix0to1[17][2] = 4.2431288023958;
   fWeightMatrix0to1[0][3] = -2.91080325020075;
   fWeightMatrix0to1[1][3] = -0.869158324316438;
   fWeightMatrix0to1[2][3] = 0.17627819918851;
   fWeightMatrix0to1[3][3] = -1.46030616432429;
   fWeightMatrix0to1[4][3] = 2.35531063728123;
   fWeightMatrix0to1[5][3] = 1.35634981787564;
   fWeightMatrix0to1[6][3] = -0.111037037384208;
   fWeightMatrix0to1[7][3] = 0.0396152673979239;
   fWeightMatrix0to1[8][3] = -1.67712536277271;
   fWeightMatrix0to1[9][3] = 7.08298498506653;
   fWeightMatrix0to1[10][3] = 2.14440876985283;
   fWeightMatrix0to1[11][3] = 1.11127276113075;
   fWeightMatrix0to1[12][3] = 4.99562301589921;
   fWeightMatrix0to1[13][3] = -2.67711959449627;
   fWeightMatrix0to1[14][3] = 3.43417609143397;
   fWeightMatrix0to1[15][3] = -0.268124814693704;
   fWeightMatrix0to1[16][3] = -7.83352976457093;
   fWeightMatrix0to1[17][3] = -2.81898380910258;
   fWeightMatrix0to1[0][4] = 1.40581087865565;
   fWeightMatrix0to1[1][4] = 1.45891088548319;
   fWeightMatrix0to1[2][4] = 1.7281699797022;
   fWeightMatrix0to1[3][4] = 0.832724971917037;
   fWeightMatrix0to1[4][4] = -1.2531231996084;
   fWeightMatrix0to1[5][4] = -0.33949017504128;
   fWeightMatrix0to1[6][4] = 0.529493488378159;
   fWeightMatrix0to1[7][4] = 1.23093174945325;
   fWeightMatrix0to1[8][4] = 3.44828562792605;
   fWeightMatrix0to1[9][4] = -1.82270974283237;
   fWeightMatrix0to1[10][4] = -0.114877191318732;
   fWeightMatrix0to1[11][4] = -0.966514136082443;
   fWeightMatrix0to1[12][4] = -4.01300209815254;
   fWeightMatrix0to1[13][4] = -2.75729135327307;
   fWeightMatrix0to1[14][4] = 0.428279500286467;
   fWeightMatrix0to1[15][4] = -2.32266305694272;
   fWeightMatrix0to1[16][4] = 0.376586451704162;
   fWeightMatrix0to1[17][4] = -0.312960562935827;
   fWeightMatrix0to1[0][5] = 0.80180714963804;
   fWeightMatrix0to1[1][5] = 0.900048020618245;
   fWeightMatrix0to1[2][5] = 3.32757597033335;
   fWeightMatrix0to1[3][5] = -3.59994790699448;
   fWeightMatrix0to1[4][5] = -2.30212947403594;
   fWeightMatrix0to1[5][5] = 4.0140872994697;
   fWeightMatrix0to1[6][5] = -0.689625409321127;
   fWeightMatrix0to1[7][5] = -2.57084018556486;
   fWeightMatrix0to1[8][5] = -3.1327777441164;
   fWeightMatrix0to1[9][5] = 1.06478435250945;
   fWeightMatrix0to1[10][5] = -2.76074432564099;
   fWeightMatrix0to1[11][5] = -2.50069401306662;
   fWeightMatrix0to1[12][5] = 2.4978174826929;
   fWeightMatrix0to1[13][5] = 2.6065904813347;
   fWeightMatrix0to1[14][5] = -1.26604416584399;
   fWeightMatrix0to1[15][5] = 0.447872068432446;
   fWeightMatrix0to1[16][5] = 0.510056755969222;
   fWeightMatrix0to1[17][5] = -2.58806951882435;
   fWeightMatrix0to1[0][6] = -1.38213970643817;
   fWeightMatrix0to1[1][6] = -0.860947281733336;
   fWeightMatrix0to1[2][6] = -1.31480505673833;
   fWeightMatrix0to1[3][6] = 2.0631132116074;
   fWeightMatrix0to1[4][6] = -1.07893000756129;
   fWeightMatrix0to1[5][6] = -0.780466195853742;
   fWeightMatrix0to1[6][6] = -0.930850330940003;
   fWeightMatrix0to1[7][6] = 1.78582280475532;
   fWeightMatrix0to1[8][6] = -0.354554485650232;
   fWeightMatrix0to1[9][6] = -1.31676323156855;
   fWeightMatrix0to1[10][6] = 1.45141397383621;
   fWeightMatrix0to1[11][6] = -0.669304873510429;
   fWeightMatrix0to1[12][6] = 1.35796981711972;
   fWeightMatrix0to1[13][6] = 0.447609003083077;
   fWeightMatrix0to1[14][6] = -1.28211893608962;
   fWeightMatrix0to1[15][6] = 2.77723653167082;
   fWeightMatrix0to1[16][6] = -0.72746016031416;
   fWeightMatrix0to1[17][6] = 0.999168681505235;
   fWeightMatrix0to1[0][7] = 0.544977364109872;
   fWeightMatrix0to1[1][7] = -1.34977069328903;
   fWeightMatrix0to1[2][7] = -2.86447225369938;
   fWeightMatrix0to1[3][7] = 1.4140331788007;
   fWeightMatrix0to1[4][7] = -1.07050557020037;
   fWeightMatrix0to1[5][7] = 0.610639387086503;
   fWeightMatrix0to1[6][7] = 0.0708240122916604;
   fWeightMatrix0to1[7][7] = -0.514205499630675;
   fWeightMatrix0to1[8][7] = 0.609715782419266;
   fWeightMatrix0to1[9][7] = 1.76564709333411;
   fWeightMatrix0to1[10][7] = 2.81945857323443;
   fWeightMatrix0to1[11][7] = -2.38924473215202;
   fWeightMatrix0to1[12][7] = 0.813647054999735;
   fWeightMatrix0to1[13][7] = 1.40411246070704;
   fWeightMatrix0to1[14][7] = 0.433761715775402;
   fWeightMatrix0to1[15][7] = 1.93771304965045;
   fWeightMatrix0to1[16][7] = -1.01078303831874;
   fWeightMatrix0to1[17][7] = -0.164968225170614;
   fWeightMatrix0to1[0][8] = -1.4584376643344;
   fWeightMatrix0to1[1][8] = 3.39450875743549;
   fWeightMatrix0to1[2][8] = 2.58237432226846;
   fWeightMatrix0to1[3][8] = -0.160124194481234;
   fWeightMatrix0to1[4][8] = -3.74021749777279;
   fWeightMatrix0to1[5][8] = 5.58422986962548;
   fWeightMatrix0to1[6][8] = -0.324696597764639;
   fWeightMatrix0to1[7][8] = 0.251402107214816;
   fWeightMatrix0to1[8][8] = 3.04333182961325;
   fWeightMatrix0to1[9][8] = -2.07007035359191;
   fWeightMatrix0to1[10][8] = -0.652544333352296;
   fWeightMatrix0to1[11][8] = 1.08554374927866;
   fWeightMatrix0to1[12][8] = 1.99693252564692;
   fWeightMatrix0to1[13][8] = 6.70131888097421;
   fWeightMatrix0to1[14][8] = -0.494138456519547;
   fWeightMatrix0to1[15][8] = -2.41637598039567;
   fWeightMatrix0to1[16][8] = 0.911443809177269;
   fWeightMatrix0to1[17][8] = 2.75250645581366;
   fWeightMatrix0to1[0][9] = 1.24779266025626;
   fWeightMatrix0to1[1][9] = 0.78020353359053;
   fWeightMatrix0to1[2][9] = 0.868820056023803;
   fWeightMatrix0to1[3][9] = 0.784858066750015;
   fWeightMatrix0to1[4][9] = -0.497273182688761;
   fWeightMatrix0to1[5][9] = 0.839009012774296;
   fWeightMatrix0to1[6][9] = 0.453469050776277;
   fWeightMatrix0to1[7][9] = -0.847034063315209;
   fWeightMatrix0to1[8][9] = 1.3703148478009;
   fWeightMatrix0to1[9][9] = -0.0780554642676827;
   fWeightMatrix0to1[10][9] = 0.999691241117495;
   fWeightMatrix0to1[11][9] = 2.55021371297692;
   fWeightMatrix0to1[12][9] = 1.66919405241963;
   fWeightMatrix0to1[13][9] = -2.12108308026521;
   fWeightMatrix0to1[14][9] = -0.0045687830678588;
   fWeightMatrix0to1[15][9] = -0.342341664595374;
   fWeightMatrix0to1[16][9] = 1.11763859651274;
   fWeightMatrix0to1[17][9] = -0.966121948588254;
   fWeightMatrix0to1[0][10] = -2.97568517266351;
   fWeightMatrix0to1[1][10] = 1.60373227235494;
   fWeightMatrix0to1[2][10] = 1.49254421395407;
   fWeightMatrix0to1[3][10] = -4.08353186549062;
   fWeightMatrix0to1[4][10] = -0.987001296416467;
   fWeightMatrix0to1[5][10] = 2.51158240702187;
   fWeightMatrix0to1[6][10] = -0.924923723678164;
   fWeightMatrix0to1[7][10] = 1.10903675900247;
   fWeightMatrix0to1[8][10] = -1.90298691999641;
   fWeightMatrix0to1[9][10] = 1.4521878849695;
   fWeightMatrix0to1[10][10] = -1.14680823115886;
   fWeightMatrix0to1[11][10] = 0.464662446384542;
   fWeightMatrix0to1[12][10] = 8.17751748003572;
   fWeightMatrix0to1[13][10] = 2.8525271193029;
   fWeightMatrix0to1[14][10] = -0.154624843864802;
   fWeightMatrix0to1[15][10] = -1.57971027417323;
   fWeightMatrix0to1[16][10] = -8.62657465622607;
   fWeightMatrix0to1[17][10] = -0.340051468765444;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.87537324833786;
   fWeightMatrix1to2[0][1] = -2.34671721599879;
   fWeightMatrix1to2[0][2] = -0.904648412625855;
   fWeightMatrix1to2[0][3] = 3.1447254905331;
   fWeightMatrix1to2[0][4] = -1.8776484351898;
   fWeightMatrix1to2[0][5] = -3.49379173464412;
   fWeightMatrix1to2[0][6] = 0.00169144786703414;
   fWeightMatrix1to2[0][7] = -1.58457483194618;
   fWeightMatrix1to2[0][8] = 2.29958599928726;
   fWeightMatrix1to2[0][9] = -0.401003309932587;
   fWeightMatrix1to2[0][10] = -1.95948353704581;
   fWeightMatrix1to2[0][11] = 2.5118391164784;
   fWeightMatrix1to2[0][12] = 2.86549904379263;
   fWeightMatrix1to2[0][13] = 2.78022848852479;
   fWeightMatrix1to2[0][14] = 0.263294551612427;
   fWeightMatrix1to2[0][15] = -1.8459540550984;
   fWeightMatrix1to2[0][16] = 4.12607853587994;
   fWeightMatrix1to2[0][17] = 1.93019898450504;
   fWeightMatrix1to2[0][18] = 1.21862036586365;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 5;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 8;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 8;
   fMin_1[0][1] = 25.0050544739;
   fMax_1[0][1] = 998.587646484;
   fMin_1[1][1] = 25.0005073547;
   fMax_1[1][1] = 731.804992676;
   fMin_1[2][1] = 25.0005073547;
   fMax_1[2][1] = 998.587646484;
   fMin_1[0][2] = 0.424787640572;
   fMax_1[0][2] = 970.948669434;
   fMin_1[1][2] = 0.0516224987805;
   fMax_1[1][2] = 675.661376953;
   fMin_1[2][2] = 0.0516224987805;
   fMax_1[2][2] = 970.948669434;
   fMin_1[0][3] = 30.0008621216;
   fMax_1[0][3] = 530.67010498;
   fMin_1[1][3] = 30.0000267029;
   fMax_1[1][3] = 561.957702637;
   fMin_1[2][3] = 30.0000267029;
   fMax_1[2][3] = 561.957702637;
   fMin_1[0][4] = -490.501281738;
   fMax_1[0][4] = 263.805358887;
   fMin_1[1][4] = -500.947631836;
   fMax_1[1][4] = 419.442810059;
   fMin_1[2][4] = -500.947631836;
   fMax_1[2][4] = 419.442810059;
   fMin_1[0][5] = 0.411461532116;
   fMax_1[0][5] = 5.4996919632;
   fMin_1[1][5] = 0.344126969576;
   fMax_1[1][5] = 5.69235515594;
   fMin_1[2][5] = 0.344126969576;
   fMax_1[2][5] = 5.69235515594;
   fMin_1[0][6] = 0.0342117697001;
   fMax_1[0][6] = 7.65327262878;
   fMin_1[1][6] = 0.0015413404908;
   fMax_1[1][6] = 7.60103034973;
   fMin_1[2][6] = 0.0015413404908;
   fMax_1[2][6] = 7.65327262878;
   fMin_1[0][7] = 3.05734320136e-05;
   fMax_1[0][7] = 3.14157485962;
   fMin_1[1][7] = 1.11123727038e-05;
   fMax_1[1][7] = 3.14158844948;
   fMin_1[2][7] = 1.11123727038e-05;
   fMax_1[2][7] = 3.14158844948;
   fMin_1[0][8] = 15.4997110367;
   fMax_1[0][8] = 1457.53979492;
   fMin_1[1][8] = 11.8967847824;
   fMax_1[1][8] = 1492.41296387;
   fMin_1[2][8] = 11.8967847824;
   fMax_1[2][8] = 1492.41296387;
   fMin_1[0][9] = 14.1346282959;
   fMax_1[0][9] = 1411.71008301;
   fMin_1[1][9] = 13.2539606094;
   fMax_1[1][9] = 2406.51904297;
   fMin_1[2][9] = 13.2539606094;
   fMax_1[2][9] = 2406.51904297;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
