// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Thu Jun  7 17:42:31 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_9_2_6/src/2016_ALL/tW/tw_74/TMVA/Samples_norminal/1j0b
Training events: 298008
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "800" [Number of training cycles]
HiddenLayers: "16" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0000953674,870.969848633]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.309369772673,851.345214844]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000339508056641,833.891601562]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0010871887,1322.63378906]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.17015004158,0.999995052814]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.170274659991,0.99999588728]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [6.50161964586e-05,3.14156150818]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "C_l1_j1", "delta_phi_ll_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.478675487877865;
   fWeightMatrix0to1[1][0] = 2.62114013589083;
   fWeightMatrix0to1[2][0] = 0.7017907720173;
   fWeightMatrix0to1[3][0] = 2.86582875316221;
   fWeightMatrix0to1[4][0] = -0.209757873188875;
   fWeightMatrix0to1[5][0] = -1.80577107716844;
   fWeightMatrix0to1[6][0] = 0.98044141549337;
   fWeightMatrix0to1[7][0] = 2.68900385086136;
   fWeightMatrix0to1[8][0] = -0.116598839349138;
   fWeightMatrix0to1[9][0] = -3.18515168815095;
   fWeightMatrix0to1[10][0] = -1.2872497851279;
   fWeightMatrix0to1[11][0] = 1.32357123955196;
   fWeightMatrix0to1[12][0] = -0.37629933027716;
   fWeightMatrix0to1[13][0] = 0.927512430075493;
   fWeightMatrix0to1[14][0] = 0.101246003196755;
   fWeightMatrix0to1[15][0] = 0.573332989410894;
   fWeightMatrix0to1[0][1] = 0.126293268028083;
   fWeightMatrix0to1[1][1] = 1.2161807945771;
   fWeightMatrix0to1[2][1] = 0.26831370898917;
   fWeightMatrix0to1[3][1] = 3.10368147506841;
   fWeightMatrix0to1[4][1] = 0.862803685776575;
   fWeightMatrix0to1[5][1] = -1.1860235373414;
   fWeightMatrix0to1[6][1] = 1.04708735170825;
   fWeightMatrix0to1[7][1] = 0.787480505532216;
   fWeightMatrix0to1[8][1] = 0.312836258955346;
   fWeightMatrix0to1[9][1] = -9.98674619265091;
   fWeightMatrix0to1[10][1] = 1.86980825961509;
   fWeightMatrix0to1[11][1] = 1.85871093356507;
   fWeightMatrix0to1[12][1] = -2.86830547836913;
   fWeightMatrix0to1[13][1] = 1.17322331947716;
   fWeightMatrix0to1[14][1] = 1.14129193168879;
   fWeightMatrix0to1[15][1] = 3.40698871402059;
   fWeightMatrix0to1[0][2] = 0.440893926626195;
   fWeightMatrix0to1[1][2] = -0.277296513778117;
   fWeightMatrix0to1[2][2] = -0.091619621336834;
   fWeightMatrix0to1[3][2] = -2.18620754051569;
   fWeightMatrix0to1[4][2] = -0.568559127606681;
   fWeightMatrix0to1[5][2] = 1.94591003485663;
   fWeightMatrix0to1[6][2] = 1.25908340862029;
   fWeightMatrix0to1[7][2] = 2.48211624214987;
   fWeightMatrix0to1[8][2] = 2.31184209422758;
   fWeightMatrix0to1[9][2] = 7.26323566915563;
   fWeightMatrix0to1[10][2] = 2.46855986755986;
   fWeightMatrix0to1[11][2] = 3.19173624546719;
   fWeightMatrix0to1[12][2] = 1.52590462555586;
   fWeightMatrix0to1[13][2] = -0.0911360880148735;
   fWeightMatrix0to1[14][2] = 1.50687550679349;
   fWeightMatrix0to1[15][2] = 1.08103803930659;
   fWeightMatrix0to1[0][3] = 2.60836305388257;
   fWeightMatrix0to1[1][3] = 2.41428585412083;
   fWeightMatrix0to1[2][3] = 1.33192642635819;
   fWeightMatrix0to1[3][3] = 0.380537708383597;
   fWeightMatrix0to1[4][3] = 0.430082142537659;
   fWeightMatrix0to1[5][3] = 0.721472075335975;
   fWeightMatrix0to1[6][3] = 0.355006921427391;
   fWeightMatrix0to1[7][3] = -1.83439072191233;
   fWeightMatrix0to1[8][3] = -0.0157086179501054;
   fWeightMatrix0to1[9][3] = -6.64869725817463;
   fWeightMatrix0to1[10][3] = 1.49173556283593;
   fWeightMatrix0to1[11][3] = 1.10772441025041;
   fWeightMatrix0to1[12][3] = -1.86400824838379;
   fWeightMatrix0to1[13][3] = 1.83232158416739;
   fWeightMatrix0to1[14][3] = 0.254310752306898;
   fWeightMatrix0to1[15][3] = -1.74643794974069;
   fWeightMatrix0to1[0][4] = 1.21709133487964;
   fWeightMatrix0to1[1][4] = -0.643445688032075;
   fWeightMatrix0to1[2][4] = 0.138260687113628;
   fWeightMatrix0to1[3][4] = -2.33418584721666;
   fWeightMatrix0to1[4][4] = 0.680155375728316;
   fWeightMatrix0to1[5][4] = -1.53342501171278;
   fWeightMatrix0to1[6][4] = -0.745663505399179;
   fWeightMatrix0to1[7][4] = 0.431321875951141;
   fWeightMatrix0to1[8][4] = 0.116316932533414;
   fWeightMatrix0to1[9][4] = 0.0140570535874764;
   fWeightMatrix0to1[10][4] = 0.857651481689883;
   fWeightMatrix0to1[11][4] = 0.949078692194434;
   fWeightMatrix0to1[12][4] = -0.549649787067265;
   fWeightMatrix0to1[13][4] = -1.44866064329293;
   fWeightMatrix0to1[14][4] = 0.93328509468346;
   fWeightMatrix0to1[15][4] = 2.54984437676852;
   fWeightMatrix0to1[0][5] = 1.18545197380115;
   fWeightMatrix0to1[1][5] = 0.0354061390055785;
   fWeightMatrix0to1[2][5] = 1.16026131025605;
   fWeightMatrix0to1[3][5] = 0.606886380717133;
   fWeightMatrix0to1[4][5] = -0.261336032486743;
   fWeightMatrix0to1[5][5] = 0.949059035158485;
   fWeightMatrix0to1[6][5] = 1.96370082743233;
   fWeightMatrix0to1[7][5] = -0.649978677117025;
   fWeightMatrix0to1[8][5] = -1.5137254212664;
   fWeightMatrix0to1[9][5] = -0.264861207208209;
   fWeightMatrix0to1[10][5] = -0.139967702191993;
   fWeightMatrix0to1[11][5] = -0.828361804954501;
   fWeightMatrix0to1[12][5] = 0.194301751239512;
   fWeightMatrix0to1[13][5] = -1.3790269594788;
   fWeightMatrix0to1[14][5] = -0.554216635327712;
   fWeightMatrix0to1[15][5] = -1.58611357111574;
   fWeightMatrix0to1[0][6] = -0.938636635961831;
   fWeightMatrix0to1[1][6] = -0.799688790349414;
   fWeightMatrix0to1[2][6] = -1.4167764562873;
   fWeightMatrix0to1[3][6] = -1.09615634608697;
   fWeightMatrix0to1[4][6] = -2.24915814437662;
   fWeightMatrix0to1[5][6] = -0.601401640314389;
   fWeightMatrix0to1[6][6] = 0.849413951360779;
   fWeightMatrix0to1[7][6] = 0.811354702435117;
   fWeightMatrix0to1[8][6] = -1.5888497657832;
   fWeightMatrix0to1[9][6] = 1.25908744995899;
   fWeightMatrix0to1[10][6] = -0.319663210216159;
   fWeightMatrix0to1[11][6] = 1.17088162273072;
   fWeightMatrix0to1[12][6] = -1.10800130028699;
   fWeightMatrix0to1[13][6] = -0.928499705134125;
   fWeightMatrix0to1[14][6] = -2.07726994629764;
   fWeightMatrix0to1[15][6] = 3.13891416705419;
   fWeightMatrix0to1[0][7] = -1.08443967805447;
   fWeightMatrix0to1[1][7] = 1.93324774299766;
   fWeightMatrix0to1[2][7] = -1.37923820903211;
   fWeightMatrix0to1[3][7] = 1.99368304245253;
   fWeightMatrix0to1[4][7] = 0.0329760775565359;
   fWeightMatrix0to1[5][7] = -1.05770784587037;
   fWeightMatrix0to1[6][7] = -0.897731935911953;
   fWeightMatrix0to1[7][7] = -0.0831248597733223;
   fWeightMatrix0to1[8][7] = -2.15954360791397;
   fWeightMatrix0to1[9][7] = -13.979399695603;
   fWeightMatrix0to1[10][7] = -0.510378763468146;
   fWeightMatrix0to1[11][7] = 2.35454621760721;
   fWeightMatrix0to1[12][7] = -1.77752521990028;
   fWeightMatrix0to1[13][7] = -1.76604712171065;
   fWeightMatrix0to1[14][7] = -1.15981481007307;
   fWeightMatrix0to1[15][7] = 0.755658106364197;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.420782533685733;
   fWeightMatrix1to2[0][1] = 2.484830242091;
   fWeightMatrix1to2[0][2] = -0.646592412388805;
   fWeightMatrix1to2[0][3] = -2.16830259180289;
   fWeightMatrix1to2[0][4] = -0.953956793319321;
   fWeightMatrix1to2[0][5] = 0.989378982658978;
   fWeightMatrix1to2[0][6] = 1.06350839686241;
   fWeightMatrix1to2[0][7] = 1.0831981444186;
   fWeightMatrix1to2[0][8] = 1.0018210445691;
   fWeightMatrix1to2[0][9] = -7.24129258236262;
   fWeightMatrix1to2[0][10] = 0.64847019970152;
   fWeightMatrix1to2[0][11] = 0.654845106901139;
   fWeightMatrix1to2[0][12] = 2.28668827810202;
   fWeightMatrix1to2[0][13] = 0.678924624606562;
   fWeightMatrix1to2[0][14] = 0.53929370263267;
   fWeightMatrix1to2[0][15] = 0.945378710097151;
   fWeightMatrix1to2[0][16] = -1.32643888245634;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0069923401;
   fMax_1[0][0] = 870.969848633;
   fMin_1[1][0] = 25.0000953674;
   fMax_1[1][0] = 814.667053223;
   fMin_1[2][0] = 25.0000953674;
   fMax_1[2][0] = 870.969848633;
   fMin_1[0][1] = 0.489044517279;
   fMax_1[0][1] = 834.10736084;
   fMin_1[1][1] = 0.309369772673;
   fMax_1[1][1] = 851.345214844;
   fMin_1[2][1] = 0.309369772673;
   fMax_1[2][1] = 851.345214844;
   fMin_1[0][2] = 0.000339508056641;
   fMax_1[0][2] = 833.891601562;
   fMin_1[1][2] = 0.000347137451172;
   fMax_1[1][2] = 761.773071289;
   fMin_1[2][2] = 0.000339508056641;
   fMax_1[2][2] = 833.891601562;
   fMin_1[0][3] = 20.0010871887;
   fMax_1[0][3] = 1161.76989746;
   fMin_1[1][3] = 20.001455307;
   fMax_1[1][3] = 1322.63378906;
   fMin_1[2][3] = 20.0010871887;
   fMax_1[2][3] = 1322.63378906;
   fMin_1[0][4] = 0.17530092597;
   fMax_1[0][4] = 0.999994754791;
   fMin_1[1][4] = 0.17015004158;
   fMax_1[1][4] = 0.999995052814;
   fMin_1[2][4] = 0.17015004158;
   fMax_1[2][4] = 0.999995052814;
   fMin_1[0][5] = 0.172847017646;
   fMax_1[0][5] = 0.999880611897;
   fMin_1[1][5] = 0.170274659991;
   fMax_1[1][5] = 0.99999588728;
   fMin_1[2][5] = 0.170274659991;
   fMax_1[2][5] = 0.99999588728;
   fMin_1[0][6] = 0.000465459888801;
   fMax_1[0][6] = 3.14153122902;
   fMin_1[1][6] = 6.50161964586e-05;
   fMax_1[1][6] = 3.14156150818;
   fMin_1[2][6] = 6.50161964586e-05;
   fMax_1[2][6] = 3.14156150818;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
