// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Thu Jul 27 13:33:04 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA/Samples_inclusive/1j1b
Training events: 27310
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "800" [Number of training cycles]
HiddenLayers: "8" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
PT_Loose_jet                  PT_Loose_jet                  PT_Loose_jet                  PT_Loose_jet                                                    'F'    [0,29.9996795654]
n_Loose_bjet                  n_Loose_bjet                  n_Loose_bjet                  n_Loose_bjet                                                    'I'    [0,2]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.30892547965,778.989562988]
deltaR_l1_j1                  deltaR_l1_j1                  deltaR_l1_j1                  deltaR_l1_j1                                                    'F'    [0.3955989182,5.39544010162]
deltaR_ll                     deltaR_ll                     deltaR_ll                     deltaR_ll                                                       'F'    [0.296238094568,5.51892995834]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [0.000114923554065,3.14148736]
C_ll_j1                       C_ll_j1                       C_ll_j1                       C_ll_j1                                                         'F'    [0.193442597985,0.999692082405]
PT_l1j1                       PT_l1j1                       PT_l1j1                       PT_l1j1                                                         'F'    [0.625802874565,870.782653809]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "PT_Loose_jet", "n_Loose_bjet", "PT_ll_j1", "deltaR_l1_j1", "deltaR_ll", "delta_phi_ll_j1", "C_ll_j1", "PT_l1j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[9][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][9];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 9; fWeights[1] = new double[9]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.232397424857369;
   fWeightMatrix0to1[1][0] = 0.637257738636461;
   fWeightMatrix0to1[2][0] = -0.91708162059265;
   fWeightMatrix0to1[3][0] = -1.41220039447975;
   fWeightMatrix0to1[4][0] = -0.759735611183696;
   fWeightMatrix0to1[5][0] = 0.142409997298614;
   fWeightMatrix0to1[6][0] = -2.05716338233139;
   fWeightMatrix0to1[7][0] = 1.63230498561945;
   fWeightMatrix0to1[0][1] = 0.374061462605192;
   fWeightMatrix0to1[1][1] = -0.374399408315767;
   fWeightMatrix0to1[2][1] = 0.898301675853901;
   fWeightMatrix0to1[3][1] = 7.42971616230864;
   fWeightMatrix0to1[4][1] = 0.0401121922139142;
   fWeightMatrix0to1[5][1] = 0.740648615931038;
   fWeightMatrix0to1[6][1] = -2.29671308131064;
   fWeightMatrix0to1[7][1] = 3.76664446892823;
   fWeightMatrix0to1[0][2] = 1.24965208521112;
   fWeightMatrix0to1[1][2] = 7.04451158127535;
   fWeightMatrix0to1[2][2] = 0.00167488081520792;
   fWeightMatrix0to1[3][2] = -1.07708460348534;
   fWeightMatrix0to1[4][2] = 2.5096867243824;
   fWeightMatrix0to1[5][2] = -0.15943243418269;
   fWeightMatrix0to1[6][2] = 6.61280482679195;
   fWeightMatrix0to1[7][2] = -2.38403781838965;
   fWeightMatrix0to1[0][3] = -5.25985221409001;
   fWeightMatrix0to1[1][3] = -2.30762435599295;
   fWeightMatrix0to1[2][3] = 0.567613587465969;
   fWeightMatrix0to1[3][3] = -1.52382244453021;
   fWeightMatrix0to1[4][3] = -6.52055274740337;
   fWeightMatrix0to1[5][3] = 0.340078968247057;
   fWeightMatrix0to1[6][3] = 4.80647879924691;
   fWeightMatrix0to1[7][3] = 3.04992415805763;
   fWeightMatrix0to1[0][4] = 0.273337700239689;
   fWeightMatrix0to1[1][4] = -1.32427901376614;
   fWeightMatrix0to1[2][4] = 2.82417846174999;
   fWeightMatrix0to1[3][4] = 2.79265603424343;
   fWeightMatrix0to1[4][4] = 0.935298457441876;
   fWeightMatrix0to1[5][4] = 1.4986506946731;
   fWeightMatrix0to1[6][4] = -0.4870367188069;
   fWeightMatrix0to1[7][4] = 3.06450759585072;
   fWeightMatrix0to1[0][5] = -0.880134125757585;
   fWeightMatrix0to1[1][5] = -1.4030179445377;
   fWeightMatrix0to1[2][5] = 2.58020120978385;
   fWeightMatrix0to1[3][5] = 5.97364075013599;
   fWeightMatrix0to1[4][5] = 1.83839387943947;
   fWeightMatrix0to1[5][5] = -1.92055699795731;
   fWeightMatrix0to1[6][5] = 7.00545032482129;
   fWeightMatrix0to1[7][5] = -0.185646557236009;
   fWeightMatrix0to1[0][6] = 3.48598830659385;
   fWeightMatrix0to1[1][6] = 2.31761363615313;
   fWeightMatrix0to1[2][6] = 0.0732055336955374;
   fWeightMatrix0to1[3][6] = 3.0187916823827;
   fWeightMatrix0to1[4][6] = -2.58508300475715;
   fWeightMatrix0to1[5][6] = 1.67614530670742;
   fWeightMatrix0to1[6][6] = -3.13951573153725;
   fWeightMatrix0to1[7][6] = 0.0652308305253832;
   fWeightMatrix0to1[0][7] = 0.138752195274642;
   fWeightMatrix0to1[1][7] = 1.34769503139292;
   fWeightMatrix0to1[2][7] = 6.19190244410332;
   fWeightMatrix0to1[3][7] = -0.9179421525162;
   fWeightMatrix0to1[4][7] = 0.322407148860244;
   fWeightMatrix0to1[5][7] = 0.96895476379733;
   fWeightMatrix0to1[6][7] = 8.18916342959083;
   fWeightMatrix0to1[7][7] = -3.93281750099174;
   fWeightMatrix0to1[0][8] = -4.23938067475028;
   fWeightMatrix0to1[1][8] = 1.99133268159288;
   fWeightMatrix0to1[2][8] = 1.20280755303051;
   fWeightMatrix0to1[3][8] = -2.5091492967988;
   fWeightMatrix0to1[4][8] = -0.962782080107518;
   fWeightMatrix0to1[5][8] = -1.60120632858779;
   fWeightMatrix0to1[6][8] = -1.68879520311938;
   fWeightMatrix0to1[7][8] = -0.159644596604566;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.91109875247675;
   fWeightMatrix1to2[0][1] = -3.33511894338884;
   fWeightMatrix1to2[0][2] = 5.20408787038216;
   fWeightMatrix1to2[0][3] = -1.20184226670149;
   fWeightMatrix1to2[0][4] = -1.15486390095304;
   fWeightMatrix1to2[0][5] = -1.08697124612511;
   fWeightMatrix1to2[0][6] = -3.7445881998469;
   fWeightMatrix1to2[0][7] = -1.28484682510367;
   fWeightMatrix1to2[0][8] = 0.937726634819893;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 29.9988632202;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 29.9996795654;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 29.9996795654;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 2;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 2;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 2;
   fMin_1[0][2] = 0.30892547965;
   fMax_1[0][2] = 778.989562988;
   fMin_1[1][2] = 0.799813389778;
   fMax_1[1][2] = 491.901184082;
   fMin_1[2][2] = 0.30892547965;
   fMax_1[2][2] = 778.989562988;
   fMin_1[0][3] = 0.3955989182;
   fMax_1[0][3] = 5.39544010162;
   fMin_1[1][3] = 0.430148154497;
   fMax_1[1][3] = 5.029961586;
   fMin_1[2][3] = 0.3955989182;
   fMax_1[2][3] = 5.39544010162;
   fMin_1[0][4] = 0.296238094568;
   fMax_1[0][4] = 5.51892995834;
   fMin_1[1][4] = 0.332337528467;
   fMax_1[1][4] = 5.30966854095;
   fMin_1[2][4] = 0.296238094568;
   fMax_1[2][4] = 5.51892995834;
   fMin_1[0][5] = 0.000114923554065;
   fMax_1[0][5] = 3.14148736;
   fMin_1[1][5] = 0.000419487070758;
   fMax_1[1][5] = 3.14135432243;
   fMin_1[2][5] = 0.000114923554065;
   fMax_1[2][5] = 3.14148736;
   fMin_1[0][6] = 0.193466976285;
   fMax_1[0][6] = 0.999692082405;
   fMin_1[1][6] = 0.193442597985;
   fMax_1[1][6] = 0.998063266277;
   fMin_1[2][6] = 0.193442597985;
   fMax_1[2][6] = 0.999692082405;
   fMin_1[0][7] = 0.625802874565;
   fMax_1[0][7] = 870.782653809;
   fMin_1[1][7] = 1.58683693409;
   fMax_1[1][7] = 564.3359375;
   fMin_1[2][7] = 0.625802874565;
   fMax_1[2][7] = 870.782653809;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
