// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Mon Jun 19 12:26:48 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA/1j0b
Training events: 298008
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "800" [Number of training cycles]
HiddenLayers: "16" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0000953674,870.969848633]
n_Loose_jet                   n_Loose_jet                   n_Loose_jet                   n_Loose_jet                                                     'I'    [0,7]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.309369772673,851.345214844]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000339508056641,833.891601562]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0010871887,1322.63378906]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.17015004158,0.999995052814]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.170274659991,0.99999588728]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [6.50161964586e-05,3.14156150818]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "n_Loose_jet", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "C_l1_j1", "delta_phi_ll_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.449145161028153;
   fWeightMatrix0to1[1][0] = 2.48263984771658;
   fWeightMatrix0to1[2][0] = 1.87224966242816;
   fWeightMatrix0to1[3][0] = -1.06205425449811;
   fWeightMatrix0to1[4][0] = -0.220304685802062;
   fWeightMatrix0to1[5][0] = -1.1381723126923;
   fWeightMatrix0to1[6][0] = -0.931858584692885;
   fWeightMatrix0to1[7][0] = 2.61667892418143;
   fWeightMatrix0to1[8][0] = 2.16135713420947;
   fWeightMatrix0to1[9][0] = 0.222512425309395;
   fWeightMatrix0to1[10][0] = -2.09721094811068;
   fWeightMatrix0to1[11][0] = -1.29096177018274;
   fWeightMatrix0to1[12][0] = -1.21169666416959;
   fWeightMatrix0to1[13][0] = 2.06400769251491;
   fWeightMatrix0to1[14][0] = -0.133675686795812;
   fWeightMatrix0to1[15][0] = 0.124337169675538;
   fWeightMatrix0to1[0][1] = 0.496580356440322;
   fWeightMatrix0to1[1][1] = 4.52792851794465;
   fWeightMatrix0to1[2][1] = 0.322856703136552;
   fWeightMatrix0to1[3][1] = -0.25902397033034;
   fWeightMatrix0to1[4][1] = 2.05388523727772;
   fWeightMatrix0to1[5][1] = -0.117570252807359;
   fWeightMatrix0to1[6][1] = 0.486283425069098;
   fWeightMatrix0to1[7][1] = -0.73084613887196;
   fWeightMatrix0to1[8][1] = -0.565624966575485;
   fWeightMatrix0to1[9][1] = 0.536861685380074;
   fWeightMatrix0to1[10][1] = 2.79536152845747;
   fWeightMatrix0to1[11][1] = -5.35843196060142;
   fWeightMatrix0to1[12][1] = -1.92945013073274;
   fWeightMatrix0to1[13][1] = 0.680880561561725;
   fWeightMatrix0to1[14][1] = 1.20203501390103;
   fWeightMatrix0to1[15][1] = 2.30088526950091;
   fWeightMatrix0to1[0][2] = -0.376882893911286;
   fWeightMatrix0to1[1][2] = -0.77154120569006;
   fWeightMatrix0to1[2][2] = 0.204899590585888;
   fWeightMatrix0to1[3][2] = -8.93805155471263;
   fWeightMatrix0to1[4][2] = -0.372813297147474;
   fWeightMatrix0to1[5][2] = 2.03202295180371;
   fWeightMatrix0to1[6][2] = -1.19243047954457;
   fWeightMatrix0to1[7][2] = 2.39819173040745;
   fWeightMatrix0to1[8][2] = 3.99918492942935;
   fWeightMatrix0to1[9][2] = 1.85308989452714;
   fWeightMatrix0to1[10][2] = 4.35194687707478;
   fWeightMatrix0to1[11][2] = 4.40272864550942;
   fWeightMatrix0to1[12][2] = -0.723123533672541;
   fWeightMatrix0to1[13][2] = -1.10623846755903;
   fWeightMatrix0to1[14][2] = 0.957150125368807;
   fWeightMatrix0to1[15][2] = -3.09776956217906;
   fWeightMatrix0to1[0][3] = 2.12827409210076;
   fWeightMatrix0to1[1][3] = 1.29736120344921;
   fWeightMatrix0to1[2][3] = 1.39674696680801;
   fWeightMatrix0to1[3][3] = 5.72805229801182;
   fWeightMatrix0to1[4][3] = 0.0215131524059109;
   fWeightMatrix0to1[5][3] = 1.73421323676505;
   fWeightMatrix0to1[6][3] = -2.36522146921331;
   fWeightMatrix0to1[7][3] = -0.880121907460873;
   fWeightMatrix0to1[8][3] = -2.69391605452204;
   fWeightMatrix0to1[9][3] = -1.22759586048214;
   fWeightMatrix0to1[10][3] = -1.20090369550524;
   fWeightMatrix0to1[11][3] = 0.48338128121442;
   fWeightMatrix0to1[12][3] = -1.56683796180433;
   fWeightMatrix0to1[13][3] = 1.33732404669392;
   fWeightMatrix0to1[14][3] = 0.128551174623852;
   fWeightMatrix0to1[15][3] = 0.981324122862665;
   fWeightMatrix0to1[0][4] = 2.28492842085794;
   fWeightMatrix0to1[1][4] = -2.5659107275993;
   fWeightMatrix0to1[2][4] = 1.73595586327688;
   fWeightMatrix0to1[3][4] = -6.08878120153409;
   fWeightMatrix0to1[4][4] = 2.50159924380083;
   fWeightMatrix0to1[5][4] = -0.594146921135818;
   fWeightMatrix0to1[6][4] = -0.656220555619895;
   fWeightMatrix0to1[7][4] = -0.996561094698545;
   fWeightMatrix0to1[8][4] = 2.45913844260785;
   fWeightMatrix0to1[9][4] = 1.21484419965172;
   fWeightMatrix0to1[10][4] = 1.03254380783838;
   fWeightMatrix0to1[11][4] = 2.08112471247883;
   fWeightMatrix0to1[12][4] = -1.94856716743395;
   fWeightMatrix0to1[13][4] = -0.705992317029356;
   fWeightMatrix0to1[14][4] = 2.11673327776538;
   fWeightMatrix0to1[15][4] = 1.45221459772965;
   fWeightMatrix0to1[0][5] = 2.16869078733252;
   fWeightMatrix0to1[1][5] = 0.852808223451197;
   fWeightMatrix0to1[2][5] = 2.15265381039521;
   fWeightMatrix0to1[3][5] = 0.0502228813878078;
   fWeightMatrix0to1[4][5] = -1.02762910269137;
   fWeightMatrix0to1[5][5] = -0.653534180450852;
   fWeightMatrix0to1[6][5] = 0.779993290125717;
   fWeightMatrix0to1[7][5] = -0.802975348959063;
   fWeightMatrix0to1[8][5] = -0.427215837295306;
   fWeightMatrix0to1[9][5] = -2.43623357130867;
   fWeightMatrix0to1[10][5] = -0.243770873605767;
   fWeightMatrix0to1[11][5] = 1.80751524794011;
   fWeightMatrix0to1[12][5] = 1.62624725516806;
   fWeightMatrix0to1[13][5] = -3.43137233553724;
   fWeightMatrix0to1[14][5] = -1.28397103035423;
   fWeightMatrix0to1[15][5] = 2.66732970051272;
   fWeightMatrix0to1[0][6] = -2.13339966993183;
   fWeightMatrix0to1[1][6] = -1.28683019023342;
   fWeightMatrix0to1[2][6] = -1.02462943254451;
   fWeightMatrix0to1[3][6] = -0.217532691975385;
   fWeightMatrix0to1[4][6] = -0.833206334037976;
   fWeightMatrix0to1[5][6] = -1.70155161126394;
   fWeightMatrix0to1[6][6] = -0.439309114330219;
   fWeightMatrix0to1[7][6] = 0.323124883618239;
   fWeightMatrix0to1[8][6] = -0.050746364765967;
   fWeightMatrix0to1[9][6] = 0.114132528440847;
   fWeightMatrix0to1[10][6] = 0.217712862258569;
   fWeightMatrix0to1[11][6] = -0.822267576431444;
   fWeightMatrix0to1[12][6] = 0.00791517008463407;
   fWeightMatrix0to1[13][6] = -0.708664368284477;
   fWeightMatrix0to1[14][6] = -2.5072285526791;
   fWeightMatrix0to1[15][6] = -1.27882072263006;
   fWeightMatrix0to1[0][7] = 2.59981618305935;
   fWeightMatrix0to1[1][7] = 1.25619672548151;
   fWeightMatrix0to1[2][7] = -0.232431065964739;
   fWeightMatrix0to1[3][7] = 1.03852324228176;
   fWeightMatrix0to1[4][7] = -1.12587469801584;
   fWeightMatrix0to1[5][7] = -0.520413410590819;
   fWeightMatrix0to1[6][7] = -0.384770178873869;
   fWeightMatrix0to1[7][7] = -0.913077645755047;
   fWeightMatrix0to1[8][7] = -0.547280012595737;
   fWeightMatrix0to1[9][7] = -0.0122347520998085;
   fWeightMatrix0to1[10][7] = 0.183864626525968;
   fWeightMatrix0to1[11][7] = 0.703870640143216;
   fWeightMatrix0to1[12][7] = 0.787552828722791;
   fWeightMatrix0to1[13][7] = -0.918302388524996;
   fWeightMatrix0to1[14][7] = -1.29165138164774;
   fWeightMatrix0to1[15][7] = -0.154423256558784;
   fWeightMatrix0to1[0][8] = -2.62746097082146;
   fWeightMatrix0to1[1][8] = 1.45941289001951;
   fWeightMatrix0to1[2][8] = 1.2999476866075;
   fWeightMatrix0to1[3][8] = -11.6992744221694;
   fWeightMatrix0to1[4][8] = -0.756493451666269;
   fWeightMatrix0to1[5][8] = -1.68970507545346;
   fWeightMatrix0to1[6][8] = -0.830453040852266;
   fWeightMatrix0to1[7][8] = 0.523366576029229;
   fWeightMatrix0to1[8][8] = 4.21392388584776;
   fWeightMatrix0to1[9][8] = -2.14482508370475;
   fWeightMatrix0to1[10][8] = 2.8711333495157;
   fWeightMatrix0to1[11][8] = -1.18463583468412;
   fWeightMatrix0to1[12][8] = 1.70681415922566;
   fWeightMatrix0to1[13][8] = -0.935224150885716;
   fWeightMatrix0to1[14][8] = -1.92516935818046;
   fWeightMatrix0to1[15][8] = 0.40370790394693;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.01367146239974;
   fWeightMatrix1to2[0][1] = 1.11615241810083;
   fWeightMatrix1to2[0][2] = 2.19780691628998;
   fWeightMatrix1to2[0][3] = -6.65444611675334;
   fWeightMatrix1to2[0][4] = 1.0663598671572;
   fWeightMatrix1to2[0][5] = 0.634748391196662;
   fWeightMatrix1to2[0][6] = -1.71713580326517;
   fWeightMatrix1to2[0][7] = -0.647021660562285;
   fWeightMatrix1to2[0][8] = -2.02622491600577;
   fWeightMatrix1to2[0][9] = -0.371706294115902;
   fWeightMatrix1to2[0][10] = -2.15214582929886;
   fWeightMatrix1to2[0][11] = 1.14016181529876;
   fWeightMatrix1to2[0][12] = 1.42904596335431;
   fWeightMatrix1to2[0][13] = -0.953700639507091;
   fWeightMatrix1to2[0][14] = 1.93727099158938;
   fWeightMatrix1to2[0][15] = -1.40065450672356;
   fWeightMatrix1to2[0][16] = 2.13204138140485;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0069923401;
   fMax_1[0][0] = 870.969848633;
   fMin_1[1][0] = 25.0000953674;
   fMax_1[1][0] = 814.667053223;
   fMin_1[2][0] = 25.0000953674;
   fMax_1[2][0] = 870.969848633;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 7;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 7;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 0.489044517279;
   fMax_1[0][2] = 834.10736084;
   fMin_1[1][2] = 0.309369772673;
   fMax_1[1][2] = 851.345214844;
   fMin_1[2][2] = 0.309369772673;
   fMax_1[2][2] = 851.345214844;
   fMin_1[0][3] = 0.000339508056641;
   fMax_1[0][3] = 833.891601562;
   fMin_1[1][3] = 0.000347137451172;
   fMax_1[1][3] = 761.773071289;
   fMin_1[2][3] = 0.000339508056641;
   fMax_1[2][3] = 833.891601562;
   fMin_1[0][4] = 20.0010871887;
   fMax_1[0][4] = 1161.76989746;
   fMin_1[1][4] = 20.001455307;
   fMax_1[1][4] = 1322.63378906;
   fMin_1[2][4] = 20.0010871887;
   fMax_1[2][4] = 1322.63378906;
   fMin_1[0][5] = 0.17530092597;
   fMax_1[0][5] = 0.999994754791;
   fMin_1[1][5] = 0.17015004158;
   fMax_1[1][5] = 0.999995052814;
   fMin_1[2][5] = 0.17015004158;
   fMax_1[2][5] = 0.999995052814;
   fMin_1[0][6] = 0.172847017646;
   fMax_1[0][6] = 0.999880611897;
   fMin_1[1][6] = 0.170274659991;
   fMax_1[1][6] = 0.99999588728;
   fMin_1[2][6] = 0.170274659991;
   fMax_1[2][6] = 0.99999588728;
   fMin_1[0][7] = 0.000465459888801;
   fMax_1[0][7] = 3.14153122902;
   fMin_1[1][7] = 6.50161964586e-05;
   fMax_1[1][7] = 3.14156150818;
   fMin_1[2][7] = 6.50161964586e-05;
   fMax_1[2][7] = 3.14156150818;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
