bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_ee_Cphiq_0.25_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_emu_Ctg_0.05_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_combined_Cphiq_0.15_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_mumu_Ctw_0.10.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_combined_Ctg_1.00_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_combined_Ctw_0.02_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_mumu_Ctg_0.10.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_combined_Cphiq_0.05_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_emu_Ctw_0.10.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_emu_Ctg_0.15_opposite.sh
echo "AllCompleted"
echo "AllCompleted"
echo "AllCompleted"
