bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_mumu_Cphiq_0.15_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_mumu_Cphiq_0.05_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_mumu_Ctg_0.10_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_ee_Ctw_0.10_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_emu_Ctw_0.20_opposite.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_ee_Ctg_0.50.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_ee_Ctg_0.20.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_ee_Ctw_0.20.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_combined_Cphiq_0.10.sh
bash /user/wenxing/Limits/CMSSW_7_4_7/src/LimitCode/TOP_EFT_0629/script_create_ws/cws_ee_Cphiq_0.05.sh
echo "AllCompleted"
echo "AllCompleted"
echo "AllCompleted"
