// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Mon Jul 10 20:30:06 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA_FastSim/FCNC
Training events: 330171
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "7" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0026493073,1415.91943359]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.0895055755973,1426.34570312]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [4.57763671875e-05,1215.90722656]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0008735657,2829.07519531]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.165485352278,0.999997079372]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.0549025982618,1219.86889648]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.00443724542856,8.26611614227]
M_l2_j1                       M_l2_j1                       M_l2_j1                       M_l2_j1                                                         'F'    [0.000510656740516,2756.32202148]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.163075685501,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "PT_ll_j1", "deltaR_ll_j1", "M_l2_j1", "C_l1_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[8][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][8];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.901992027289291;
   fWeightMatrix0to1[1][0] = 6.39747834661434;
   fWeightMatrix0to1[2][0] = 6.55583321391282;
   fWeightMatrix0to1[3][0] = 2.48678633955723;
   fWeightMatrix0to1[4][0] = -0.502240235363956;
   fWeightMatrix0to1[5][0] = 6.17332900688161;
   fWeightMatrix0to1[6][0] = -11.3474242357676;
   fWeightMatrix0to1[0][1] = 2.26495404694257;
   fWeightMatrix0to1[1][1] = -2.20030814339227;
   fWeightMatrix0to1[2][1] = -5.30001527239954;
   fWeightMatrix0to1[3][1] = -1.24059057707775;
   fWeightMatrix0to1[4][1] = -0.192863576870797;
   fWeightMatrix0to1[5][1] = -4.15607659274242;
   fWeightMatrix0to1[6][1] = 9.77597323569167;
   fWeightMatrix0to1[0][2] = -1.72977172822688;
   fWeightMatrix0to1[1][2] = -0.468422805427579;
   fWeightMatrix0to1[2][2] = -3.96865448551389;
   fWeightMatrix0to1[3][2] = 1.66890913901413;
   fWeightMatrix0to1[4][2] = 0.70476962003204;
   fWeightMatrix0to1[5][2] = 3.07472108485379;
   fWeightMatrix0to1[6][2] = 3.43197791187471;
   fWeightMatrix0to1[0][3] = -1.04797524060409;
   fWeightMatrix0to1[1][3] = 0.249441419369302;
   fWeightMatrix0to1[2][3] = -1.71209128991993;
   fWeightMatrix0to1[3][3] = -1.0488786916784;
   fWeightMatrix0to1[4][3] = 0.681986277344669;
   fWeightMatrix0to1[5][3] = 2.8164832735105;
   fWeightMatrix0to1[6][3] = -7.93291391172675;
   fWeightMatrix0to1[0][4] = -2.11833733926551;
   fWeightMatrix0to1[1][4] = -0.0315813212292588;
   fWeightMatrix0to1[2][4] = 0.214678227482758;
   fWeightMatrix0to1[3][4] = 1.42686634849499;
   fWeightMatrix0to1[4][4] = -0.78765826261787;
   fWeightMatrix0to1[5][4] = -0.362869719231011;
   fWeightMatrix0to1[6][4] = 0.110774329024802;
   fWeightMatrix0to1[0][5] = -1.35061653480289;
   fWeightMatrix0to1[1][5] = -2.84306532734536;
   fWeightMatrix0to1[2][5] = 6.38160223653145;
   fWeightMatrix0to1[3][5] = -1.89122548979143;
   fWeightMatrix0to1[4][5] = 1.15160431379751;
   fWeightMatrix0to1[5][5] = 3.17957621173344;
   fWeightMatrix0to1[6][5] = 2.83119537714262;
   fWeightMatrix0to1[0][6] = 0.305391084674206;
   fWeightMatrix0to1[1][6] = 2.42903240855588;
   fWeightMatrix0to1[2][6] = 0.0647819247644146;
   fWeightMatrix0to1[3][6] = -1.71691948515684;
   fWeightMatrix0to1[4][6] = 1.42411416580106;
   fWeightMatrix0to1[5][6] = -1.12852945563839;
   fWeightMatrix0to1[6][6] = 0.458026415938857;
   fWeightMatrix0to1[0][7] = 2.71400909003367;
   fWeightMatrix0to1[1][7] = 1.82927497203193;
   fWeightMatrix0to1[2][7] = 2.98907201926591;
   fWeightMatrix0to1[3][7] = -0.972080144973934;
   fWeightMatrix0to1[4][7] = 2.38608049588622;
   fWeightMatrix0to1[5][7] = -5.24601705020978;
   fWeightMatrix0to1[6][7] = 0.780902370214294;
   fWeightMatrix0to1[0][8] = 0.0535148314588482;
   fWeightMatrix0to1[1][8] = 0.254140976327888;
   fWeightMatrix0to1[2][8] = -0.234392965812156;
   fWeightMatrix0to1[3][8] = 0.0711385686278786;
   fWeightMatrix0to1[4][8] = -0.869793530383469;
   fWeightMatrix0to1[5][8] = 0.156516330786548;
   fWeightMatrix0to1[6][8] = -0.00947122633442049;
   fWeightMatrix0to1[0][9] = -0.188468736889907;
   fWeightMatrix0to1[1][9] = 2.96389254597299;
   fWeightMatrix0to1[2][9] = 3.42217096192605;
   fWeightMatrix0to1[3][9] = -0.115400026462603;
   fWeightMatrix0to1[4][9] = -1.61231844764159;
   fWeightMatrix0to1[5][9] = 3.86092798939129;
   fWeightMatrix0to1[6][9] = -4.51622620239881;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.30316878753628;
   fWeightMatrix1to2[0][1] = 2.01299869971453;
   fWeightMatrix1to2[0][2] = 3.46645445473506;
   fWeightMatrix1to2[0][3] = 0.797514223439921;
   fWeightMatrix1to2[0][4] = 1.27048847288397;
   fWeightMatrix1to2[0][5] = 3.09142508690603;
   fWeightMatrix1to2[0][6] = -5.93971099992297;
   fWeightMatrix1to2[0][7] = -3.45335536880884;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0917053223;
   fMax_1[0][0] = 1205.57202148;
   fMin_1[1][0] = 25.0026493073;
   fMax_1[1][0] = 1415.91943359;
   fMin_1[2][0] = 25.0026493073;
   fMax_1[2][0] = 1415.91943359;
   fMin_1[0][1] = 0.785919547081;
   fMax_1[0][1] = 1003.08691406;
   fMin_1[1][1] = 0.0895055755973;
   fMax_1[1][1] = 1426.34570312;
   fMin_1[2][1] = 0.0895055755973;
   fMax_1[2][1] = 1426.34570312;
   fMin_1[0][2] = 0.00962829589844;
   fMax_1[0][2] = 974.199829102;
   fMin_1[1][2] = 4.57763671875e-05;
   fMax_1[1][2] = 1215.90722656;
   fMin_1[2][2] = 4.57763671875e-05;
   fMax_1[2][2] = 1215.90722656;
   fMin_1[0][3] = 20.2093429565;
   fMax_1[0][3] = 2829.07519531;
   fMin_1[1][3] = 20.0008735657;
   fMax_1[1][3] = 2210.83081055;
   fMin_1[2][3] = 20.0008735657;
   fMax_1[2][3] = 2829.07519531;
   fMin_1[0][4] = 0.170676112175;
   fMax_1[0][4] = 0.999972581863;
   fMin_1[1][4] = 0.165485352278;
   fMax_1[1][4] = 0.999997079372;
   fMin_1[2][4] = 0.165485352278;
   fMax_1[2][4] = 0.999997079372;
   fMin_1[0][5] = 0.307442158461;
   fMax_1[0][5] = 940.960327148;
   fMin_1[1][5] = 0.0549025982618;
   fMax_1[1][5] = 1219.86889648;
   fMin_1[2][5] = 0.0549025982618;
   fMax_1[2][5] = 1219.86889648;
   fMin_1[0][6] = 0.0507907941937;
   fMax_1[0][6] = 7.38121557236;
   fMin_1[1][6] = 0.00443724542856;
   fMax_1[1][6] = 8.26611614227;
   fMin_1[2][6] = 0.00443724542856;
   fMax_1[2][6] = 8.26611614227;
   fMin_1[0][7] = 0.000510770711116;
   fMax_1[0][7] = 2756.32202148;
   fMin_1[1][7] = 0.000510656740516;
   fMax_1[1][7] = 2542.94335938;
   fMin_1[2][7] = 0.000510656740516;
   fMax_1[2][7] = 2756.32202148;
   fMin_1[0][8] = 0.163853377104;
   fMax_1[0][8] = 0.999967873096;
   fMin_1[1][8] = 0.163075685501;
   fMax_1[1][8] = 1;
   fMin_1[2][8] = 0.163075685501;
   fMax_1[2][8] = 1;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
