python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_8TeV_Ratio"   -i "iVtb"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_8TeV_Ratio"   -i "iVts"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_8TeV_Ratio"   -i "iVtd"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "100fb" -i "iVtb"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "100fb" -i "iVts"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "100fb" -i "iVtd"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "300fb" -i "iVtb"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "300fb" -i "iVts"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "300fb" -i "iVtd"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "3000fb" -i "iVtb"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "3000fb" -i "iVts"
python /user/wenxing/ST_TW_channel/CMSSW_8_0_25/src/Phynomenological_study/Single_TOP/fit_limit_deltachi2.py -m "dchi2" -e "exp" -c "Diff_13TeV_Ratio"  -L "3000fb" -i "iVtd"
