// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Wed Jul 12 01:41:49 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA_FastSim/FCNC_new
Training events: 330697
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "7" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0003490448,1392.98022461]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.114087618887,1267.29711914]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [0.000507354736328,1244.95861816]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.0010871887,2301.59863281]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.165485352278,0.999997079372]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.0917652025819,1827.99072266]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.000850257347338,7.88028907776]
M_l2_j1                       M_l2_j1                       M_l2_j1                       M_l2_j1                                                         'F'    [0.000510770711116,2228.23339844]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.163075685501,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "PT_ll_j1", "deltaR_ll_j1", "M_l2_j1", "C_l1_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[8][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][8];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.155480595910616;
   fWeightMatrix0to1[1][0] = 7.3611989323359;
   fWeightMatrix0to1[2][0] = 5.97315159453556;
   fWeightMatrix0to1[3][0] = 2.10344696501285;
   fWeightMatrix0to1[4][0] = -0.683703857265621;
   fWeightMatrix0to1[5][0] = 5.56141219831624;
   fWeightMatrix0to1[6][0] = -9.4752676034744;
   fWeightMatrix0to1[0][1] = 2.43218560533958;
   fWeightMatrix0to1[1][1] = -2.61272332130431;
   fWeightMatrix0to1[2][1] = -4.07061863217857;
   fWeightMatrix0to1[3][1] = -1.58901781303038;
   fWeightMatrix0to1[4][1] = -0.0912749419938858;
   fWeightMatrix0to1[5][1] = -4.49118619426609;
   fWeightMatrix0to1[6][1] = 9.60696552312517;
   fWeightMatrix0to1[0][2] = -0.967362387155336;
   fWeightMatrix0to1[1][2] = -0.739770736109477;
   fWeightMatrix0to1[2][2] = -3.4526435331035;
   fWeightMatrix0to1[3][2] = 1.61435897951251;
   fWeightMatrix0to1[4][2] = 0.568764019380861;
   fWeightMatrix0to1[5][2] = 2.89663317842038;
   fWeightMatrix0to1[6][2] = 2.33678466090231;
   fWeightMatrix0to1[0][3] = -0.659494049637344;
   fWeightMatrix0to1[1][3] = -0.241423087116486;
   fWeightMatrix0to1[2][3] = -0.993327468533948;
   fWeightMatrix0to1[3][3] = -1.0598148821021;
   fWeightMatrix0to1[4][3] = 0.542253928271564;
   fWeightMatrix0to1[5][3] = 2.03069596006746;
   fWeightMatrix0to1[6][3] = -9.19701882708856;
   fWeightMatrix0to1[0][4] = -0.943577946929822;
   fWeightMatrix0to1[1][4] = 0.603959139688109;
   fWeightMatrix0to1[2][4] = -0.598850507402446;
   fWeightMatrix0to1[3][4] = 1.64794440137255;
   fWeightMatrix0to1[4][4] = -0.272967499971346;
   fWeightMatrix0to1[5][4] = 0.144015486748572;
   fWeightMatrix0to1[6][4] = -0.0484106877123499;
   fWeightMatrix0to1[0][5] = -0.858753782277319;
   fWeightMatrix0to1[1][5] = -0.243522317691205;
   fWeightMatrix0to1[2][5] = 4.49775604731934;
   fWeightMatrix0to1[3][5] = -1.55195338452074;
   fWeightMatrix0to1[4][5] = 1.01166488397735;
   fWeightMatrix0to1[5][5] = 4.58380195673771;
   fWeightMatrix0to1[6][5] = 3.28580322776014;
   fWeightMatrix0to1[0][6] = 1.1531012137261;
   fWeightMatrix0to1[1][6] = 1.06078987954245;
   fWeightMatrix0to1[2][6] = -0.934573048608453;
   fWeightMatrix0to1[3][6] = -1.38847178219466;
   fWeightMatrix0to1[4][6] = 1.80693591720409;
   fWeightMatrix0to1[5][6] = -0.426291959177258;
   fWeightMatrix0to1[6][6] = 0.188504032529224;
   fWeightMatrix0to1[0][7] = 1.97074876032191;
   fWeightMatrix0to1[1][7] = 1.86842382099702;
   fWeightMatrix0to1[2][7] = 2.38120525363453;
   fWeightMatrix0to1[3][7] = -1.25403129792434;
   fWeightMatrix0to1[4][7] = 2.25330559514402;
   fWeightMatrix0to1[5][7] = -4.78060950042587;
   fWeightMatrix0to1[6][7] = 2.20917110010494;
   fWeightMatrix0to1[0][8] = -0.681647670433375;
   fWeightMatrix0to1[1][8] = -0.0627542886504891;
   fWeightMatrix0to1[2][8] = 0.297662503913549;
   fWeightMatrix0to1[3][8] = 0.960638694835122;
   fWeightMatrix0to1[4][8] = -0.992938304781013;
   fWeightMatrix0to1[5][8] = -0.0642994188262975;
   fWeightMatrix0to1[6][8] = 0.196301188299041;
   fWeightMatrix0to1[0][9] = 0.555159901489894;
   fWeightMatrix0to1[1][9] = 5.0886386481349;
   fWeightMatrix0to1[2][9] = 2.89171067175977;
   fWeightMatrix0to1[3][9] = 0.27835329513262;
   fWeightMatrix0to1[4][9] = -1.36560122737048;
   fWeightMatrix0to1[5][9] = 3.81337834902816;
   fWeightMatrix0to1[6][9] = -3.46951175105404;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.44772202345532;
   fWeightMatrix1to2[0][1] = 2.28913862741467;
   fWeightMatrix1to2[0][2] = 2.9701868499595;
   fWeightMatrix1to2[0][3] = 0.204798092510292;
   fWeightMatrix1to2[0][4] = 1.40396759606071;
   fWeightMatrix1to2[0][5] = 2.88294866426942;
   fWeightMatrix1to2[0][6] = -5.16520945493653;
   fWeightMatrix1to2[0][7] = -2.81062571322651;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0793647766;
   fMax_1[0][0] = 1392.98022461;
   fMin_1[1][0] = 25.0003490448;
   fMax_1[1][0] = 1267.65319824;
   fMin_1[2][0] = 25.0003490448;
   fMax_1[2][0] = 1392.98022461;
   fMin_1[0][1] = 0.545996785164;
   fMax_1[0][1] = 1026.65368652;
   fMin_1[1][1] = 0.114087618887;
   fMax_1[1][1] = 1267.29711914;
   fMin_1[2][1] = 0.114087618887;
   fMax_1[2][1] = 1267.29711914;
   fMin_1[0][2] = 0.00371551513672;
   fMax_1[0][2] = 1014.54559326;
   fMin_1[1][2] = 0.000507354736328;
   fMax_1[1][2] = 1244.95861816;
   fMin_1[2][2] = 0.000507354736328;
   fMax_1[2][2] = 1244.95861816;
   fMin_1[0][3] = 20.0702514648;
   fMax_1[0][3] = 2301.59863281;
   fMin_1[1][3] = 20.0010871887;
   fMax_1[1][3] = 1693.6048584;
   fMin_1[2][3] = 20.0010871887;
   fMax_1[2][3] = 2301.59863281;
   fMin_1[0][4] = 0.167448237538;
   fMax_1[0][4] = 0.999994277954;
   fMin_1[1][4] = 0.165485352278;
   fMax_1[1][4] = 0.999997079372;
   fMin_1[2][4] = 0.165485352278;
   fMax_1[2][4] = 0.999997079372;
   fMin_1[0][5] = 1.13732814789;
   fMax_1[0][5] = 1024.50732422;
   fMin_1[1][5] = 0.0917652025819;
   fMax_1[1][5] = 1827.99072266;
   fMin_1[2][5] = 0.0917652025819;
   fMax_1[2][5] = 1827.99072266;
   fMin_1[0][6] = 0.0187065135688;
   fMax_1[0][6] = 7.54542541504;
   fMin_1[1][6] = 0.000850257347338;
   fMax_1[1][6] = 7.88028907776;
   fMin_1[2][6] = 0.000850257347338;
   fMax_1[2][6] = 7.88028907776;
   fMin_1[0][7] = 0.000510884681717;
   fMax_1[0][7] = 2111.58227539;
   fMin_1[1][7] = 0.000510770711116;
   fMax_1[1][7] = 2228.23339844;
   fMin_1[2][7] = 0.000510770711116;
   fMax_1[2][7] = 2228.23339844;
   fMin_1[0][8] = 0.167195901275;
   fMax_1[0][8] = 0.999998569489;
   fMin_1[1][8] = 0.163075685501;
   fMax_1[1][8] = 1;
   fMin_1[2][8] = 0.163075685501;
   fMax_1[2][8] = 1;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
