// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Wed Jul 19 11:45:00 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_8_0_26_patch1/src/2016_ALL/tW/tw_74/TMVA_FullSim/FCNC_tug
Training events: 300000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "7" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [25.0018844604,2035.8762207]
PT_ll                         PT_ll                         PT_ll                         PT_ll                                                           'F'    [0.0733703002334,1983.8873291]
delta_PT_ll                   delta_PT_ll                   delta_PT_ll                   delta_PT_ll                                                     'F'    [4.19616699219e-05,1535.22277832]
M_ll                          M_ll                          M_ll                          M_ll                                                            'F'    [20.002904892,3212.13476562]
C_ll                          C_ll                          C_ll                          C_ll                                                            'F'    [0.169176399708,0.999996304512]
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.300205260515,1940.24279785]
deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                  deltaR_ll_j1                                                    'F'    [0.00865167565644,8.93086242676]
M_l2_j1                       M_l2_j1                       M_l2_j1                       M_l2_j1                                                         'F'    [0.000510770711116,2904.74121094]
C_l1_j1                       C_l1_j1                       C_l1_j1                       C_l1_j1                                                         'F'    [0.163100197911,0.999999880791]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "leading_pt", "PT_ll", "delta_PT_ll", "M_ll", "C_ll", "PT_ll_j1", "deltaR_ll_j1", "M_l2_j1", "C_l1_j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[8][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][8];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 8; fWeights[1] = new double[8]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 6.77069225684376;
   fWeightMatrix0to1[1][0] = 15.7641022550892;
   fWeightMatrix0to1[2][0] = 12.1501793285999;
   fWeightMatrix0to1[3][0] = 6.1100360925639;
   fWeightMatrix0to1[4][0] = 0.0245695581720229;
   fWeightMatrix0to1[5][0] = 14.3066293573815;
   fWeightMatrix0to1[6][0] = -30.5540742596703;
   fWeightMatrix0to1[0][1] = 7.87822331304502;
   fWeightMatrix0to1[1][1] = -2.35592397468639;
   fWeightMatrix0to1[2][1] = -0.979775131012659;
   fWeightMatrix0to1[3][1] = -3.44361750382927;
   fWeightMatrix0to1[4][1] = -0.177346960568755;
   fWeightMatrix0to1[5][1] = -14.9642648249312;
   fWeightMatrix0to1[6][1] = 20.5049867800928;
   fWeightMatrix0to1[0][2] = -8.85778276548729;
   fWeightMatrix0to1[1][2] = -1.76274304622146;
   fWeightMatrix0to1[2][2] = -5.9630400786483;
   fWeightMatrix0to1[3][2] = 2.56690268420823;
   fWeightMatrix0to1[4][2] = -1.02726567625964;
   fWeightMatrix0to1[5][2] = 4.2262254082989;
   fWeightMatrix0to1[6][2] = 6.26453712274028;
   fWeightMatrix0to1[0][3] = -4.2612954461672;
   fWeightMatrix0to1[1][3] = -0.0902146762312621;
   fWeightMatrix0to1[2][3] = -6.12635713337147;
   fWeightMatrix0to1[3][3] = 1.58338506231743;
   fWeightMatrix0to1[4][3] = 0.71815425993794;
   fWeightMatrix0to1[5][3] = 4.32725433776092;
   fWeightMatrix0to1[6][3] = -7.61766230901968;
   fWeightMatrix0to1[0][4] = -0.713714154792305;
   fWeightMatrix0to1[1][4] = -0.535066583495556;
   fWeightMatrix0to1[2][4] = -0.244110759913407;
   fWeightMatrix0to1[3][4] = -0.372751980673714;
   fWeightMatrix0to1[4][4] = 1.65695981491837;
   fWeightMatrix0to1[5][4] = -0.150061190809089;
   fWeightMatrix0to1[6][4] = -0.00478531772643217;
   fWeightMatrix0to1[0][5] = 3.6070700521802;
   fWeightMatrix0to1[1][5] = -3.40636768633675;
   fWeightMatrix0to1[2][5] = 6.41413211213773;
   fWeightMatrix0to1[3][5] = -0.629135979692385;
   fWeightMatrix0to1[4][5] = 2.69040648618227;
   fWeightMatrix0to1[5][5] = 1.14977877778619;
   fWeightMatrix0to1[6][5] = 0.887358478009338;
   fWeightMatrix0to1[0][6] = 1.16306580931696;
   fWeightMatrix0to1[1][6] = -1.34556839248988;
   fWeightMatrix0to1[2][6] = 1.00079767952497;
   fWeightMatrix0to1[3][6] = -3.39131029592311;
   fWeightMatrix0to1[4][6] = 0.602551380575077;
   fWeightMatrix0to1[5][6] = 0.06413334198522;
   fWeightMatrix0to1[6][6] = -1.6879488105996;
   fWeightMatrix0to1[0][7] = 5.07571795726277;
   fWeightMatrix0to1[1][7] = -4.52402972717406;
   fWeightMatrix0to1[2][7] = 22.6544658433568;
   fWeightMatrix0to1[3][7] = -2.9482530288388;
   fWeightMatrix0to1[4][7] = 3.60895192669125;
   fWeightMatrix0to1[5][7] = -17.7540229423434;
   fWeightMatrix0to1[6][7] = 5.8611405295525;
   fWeightMatrix0to1[0][8] = 0.354473217229152;
   fWeightMatrix0to1[1][8] = -0.493209910777004;
   fWeightMatrix0to1[2][8] = 0.00366117457667146;
   fWeightMatrix0to1[3][8] = -0.557233008360011;
   fWeightMatrix0to1[4][8] = 0.277254694111534;
   fWeightMatrix0to1[5][8] = 0.285569469987183;
   fWeightMatrix0to1[6][8] = -0.286181264296823;
   fWeightMatrix0to1[0][9] = 6.57474719893043;
   fWeightMatrix0to1[1][9] = 3.49107529345246;
   fWeightMatrix0to1[2][9] = 24.906627665455;
   fWeightMatrix0to1[3][9] = -1.27695333849466;
   fWeightMatrix0to1[4][9] = 2.11881588238115;
   fWeightMatrix0to1[5][9] = -9.57841735872974;
   fWeightMatrix0to1[6][9] = -7.44992953352464;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 4.9806051324184;
   fWeightMatrix1to2[0][1] = 2.46369716759464;
   fWeightMatrix1to2[0][2] = 2.55344500178921;
   fWeightMatrix1to2[0][3] = 2.32397272767858;
   fWeightMatrix1to2[0][4] = 3.29941492700225;
   fWeightMatrix1to2[0][5] = 3.36673292181208;
   fWeightMatrix1to2[0][6] = -3.94525829773954;
   fWeightMatrix1to2[0][7] = -3.26193984994129;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 25.0040550232;
   fMax_1[0][0] = 2035.8762207;
   fMin_1[1][0] = 25.0018844604;
   fMax_1[1][0] = 1123.41394043;
   fMin_1[2][0] = 25.0018844604;
   fMax_1[2][0] = 2035.8762207;
   fMin_1[0][1] = 0.186905950308;
   fMax_1[0][1] = 1983.8873291;
   fMin_1[1][1] = 0.0733703002334;
   fMax_1[1][1] = 1099.52282715;
   fMin_1[2][1] = 0.0733703002334;
   fMax_1[2][1] = 1983.8873291;
   fMin_1[0][2] = 0.000186920166016;
   fMax_1[0][2] = 1535.22277832;
   fMin_1[1][2] = 4.19616699219e-05;
   fMax_1[1][2] = 1093.19677734;
   fMin_1[2][2] = 4.19616699219e-05;
   fMax_1[2][2] = 1535.22277832;
   fMin_1[0][3] = 20.0171546936;
   fMax_1[0][3] = 3212.13476562;
   fMin_1[1][3] = 20.002904892;
   fMax_1[1][3] = 1419.63671875;
   fMin_1[2][3] = 20.002904892;
   fMax_1[2][3] = 3212.13476562;
   fMin_1[0][4] = 0.169796615839;
   fMax_1[0][4] = 0.999996304512;
   fMin_1[1][4] = 0.169176399708;
   fMax_1[1][4] = 0.999989449978;
   fMin_1[2][4] = 0.169176399708;
   fMax_1[2][4] = 0.999996304512;
   fMin_1[0][5] = 0.369440406561;
   fMax_1[0][5] = 1940.24279785;
   fMin_1[1][5] = 0.300205260515;
   fMax_1[1][5] = 1178.27905273;
   fMin_1[2][5] = 0.300205260515;
   fMax_1[2][5] = 1940.24279785;
   fMin_1[0][6] = 0.0151038318872;
   fMax_1[0][6] = 8.93086242676;
   fMin_1[1][6] = 0.00865167565644;
   fMax_1[1][6] = 8.02977466583;
   fMin_1[2][6] = 0.00865167565644;
   fMax_1[2][6] = 8.93086242676;
   fMin_1[0][7] = 0.000510770711116;
   fMax_1[0][7] = 2904.74121094;
   fMin_1[1][7] = 0.000510884681717;
   fMax_1[1][7] = 2119.86572266;
   fMin_1[2][7] = 0.000510770711116;
   fMax_1[2][7] = 2904.74121094;
   fMin_1[0][8] = 0.163337036967;
   fMax_1[0][8] = 0.999999880791;
   fMin_1[1][8] = 0.163100197911;
   fMax_1[1][8] = 0.999999463558;
   fMin_1[2][8] = 0.163100197911;
   fMax_1[2][8] = 0.999999880791;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
