// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : xgao
Date           : Fri Jun  8 17:44:23 2018
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/xgao/CMSSW_9_2_6/src/2016_ALL/tW/tw_74/TMVA/Samples_norminal/1j1b
Training events: 140000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "800" [Number of training cycles]
HiddenLayers: "10" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "10" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
PT_ll_j1                      PT_ll_j1                      PT_ll_j1                      PT_ll_j1                                                        'F'    [0.321787536144,944.281005859]
deltaR_l1_j1                  deltaR_l1_j1                  deltaR_l1_j1                  deltaR_l1_j1                                                    'F'    [0.352572113276,5.50419807434]
deltaR_ll                     deltaR_ll                     deltaR_ll                     deltaR_ll                                                       'F'    [0.279165536165,5.49215507507]
delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1               delta_phi_ll_j1                                                 'F'    [3.20014187309e-05,3.14158916473]
C_ll_j1                       C_ll_j1                       C_ll_j1                       C_ll_j1                                                         'F'    [0.180118754506,0.999768972397]
PT_l1j1                       PT_l1j1                       PT_l1j1                       PT_l1j1                                                         'F'    [0.284923136234,996.801757812]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "PT_ll_j1", "deltaR_l1_j1", "deltaR_ll", "delta_phi_ll_j1", "C_ll_j1", "PT_l1j1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.30735080345886;
   fWeightMatrix0to1[1][0] = 7.19401024671836;
   fWeightMatrix0to1[2][0] = 3.12055325683987;
   fWeightMatrix0to1[3][0] = 4.38208735446996;
   fWeightMatrix0to1[4][0] = 1.01410014350699;
   fWeightMatrix0to1[5][0] = -0.104148054502532;
   fWeightMatrix0to1[6][0] = 1.9458804323547;
   fWeightMatrix0to1[7][0] = 3.03983326173064;
   fWeightMatrix0to1[8][0] = -2.13290219294545;
   fWeightMatrix0to1[9][0] = 0.395073349893025;
   fWeightMatrix0to1[0][1] = -2.01260083570956;
   fWeightMatrix0to1[1][1] = -0.788066969623059;
   fWeightMatrix0to1[2][1] = 1.52096530410411;
   fWeightMatrix0to1[3][1] = 0.951962467294717;
   fWeightMatrix0to1[4][1] = -0.206615364701126;
   fWeightMatrix0to1[5][1] = -0.231212124286786;
   fWeightMatrix0to1[6][1] = 1.55210022320996;
   fWeightMatrix0to1[7][1] = 4.74084172623618;
   fWeightMatrix0to1[8][1] = 1.19202819053216;
   fWeightMatrix0to1[9][1] = 1.58259191228172;
   fWeightMatrix0to1[0][2] = -0.108673267339588;
   fWeightMatrix0to1[1][2] = 0.697887206858248;
   fWeightMatrix0to1[2][2] = 1.4873641790019;
   fWeightMatrix0to1[3][2] = 1.92785642168398;
   fWeightMatrix0to1[4][2] = -0.393160755698179;
   fWeightMatrix0to1[5][2] = 0.950699117068567;
   fWeightMatrix0to1[6][2] = 1.15829393685013;
   fWeightMatrix0to1[7][2] = 1.76647641602217;
   fWeightMatrix0to1[8][2] = 0.689227835145497;
   fWeightMatrix0to1[9][2] = 0.797042995684548;
   fWeightMatrix0to1[0][3] = -0.851524042475095;
   fWeightMatrix0to1[1][3] = 0.132242327758013;
   fWeightMatrix0to1[2][3] = -0.764786459424561;
   fWeightMatrix0to1[3][3] = 1.02253438746818;
   fWeightMatrix0to1[4][3] = -1.59340246635663;
   fWeightMatrix0to1[5][3] = 2.61715465048201;
   fWeightMatrix0to1[6][3] = -0.471576436711472;
   fWeightMatrix0to1[7][3] = -1.32915983239166;
   fWeightMatrix0to1[8][3] = -2.93807467284101;
   fWeightMatrix0to1[9][3] = 1.81678418726103;
   fWeightMatrix0to1[0][4] = -1.07583634817722;
   fWeightMatrix0to1[1][4] = -0.519176269504431;
   fWeightMatrix0to1[2][4] = 0.787394403542223;
   fWeightMatrix0to1[3][4] = -0.120955525083423;
   fWeightMatrix0to1[4][4] = -0.998011255154845;
   fWeightMatrix0to1[5][4] = -2.24021184454738;
   fWeightMatrix0to1[6][4] = 0.259681756144052;
   fWeightMatrix0to1[7][4] = 0.817262381425676;
   fWeightMatrix0to1[8][4] = -0.557085902868872;
   fWeightMatrix0to1[9][4] = 2.49178260162005;
   fWeightMatrix0to1[0][5] = 2.98055058963844;
   fWeightMatrix0to1[1][5] = 1.70398358731256;
   fWeightMatrix0to1[2][5] = -1.36596888142746;
   fWeightMatrix0to1[3][5] = 5.14334859486252;
   fWeightMatrix0to1[4][5] = 1.26113708036819;
   fWeightMatrix0to1[5][5] = 0.288783530687219;
   fWeightMatrix0to1[6][5] = -0.674596687206804;
   fWeightMatrix0to1[7][5] = -2.83188933539934;
   fWeightMatrix0to1[8][5] = 1.86340418222201;
   fWeightMatrix0to1[9][5] = 3.25571259565651;
   fWeightMatrix0to1[0][6] = -1.46767829007677;
   fWeightMatrix0to1[1][6] = 6.26963418989743;
   fWeightMatrix0to1[2][6] = -1.45361268284266;
   fWeightMatrix0to1[3][6] = 5.21788999047622;
   fWeightMatrix0to1[4][6] = -1.65830673664149;
   fWeightMatrix0to1[5][6] = -4.36325106546666;
   fWeightMatrix0to1[6][6] = -1.52206037044385;
   fWeightMatrix0to1[7][6] = -0.987581918002532;
   fWeightMatrix0to1[8][6] = -2.70241795167923;
   fWeightMatrix0to1[9][6] = -2.94066376809009;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.2377062640533;
   fWeightMatrix1to2[0][1] = -1.8907887536442;
   fWeightMatrix1to2[0][2] = -1.42159464733347;
   fWeightMatrix1to2[0][3] = 2.95064957770108;
   fWeightMatrix1to2[0][4] = -0.897598049615676;
   fWeightMatrix1to2[0][5] = -1.36573215607603;
   fWeightMatrix1to2[0][6] = -0.641784288377729;
   fWeightMatrix1to2[0][7] = -1.11125524899027;
   fWeightMatrix1to2[0][8] = 1.39134220768683;
   fWeightMatrix1to2[0][9] = 1.51740412001091;
   fWeightMatrix1to2[0][10] = 0.465068334384103;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.685150504112;
   fMax_1[0][0] = 944.281005859;
   fMin_1[1][0] = 0.321787536144;
   fMax_1[1][0] = 509.195343018;
   fMin_1[2][0] = 0.321787536144;
   fMax_1[2][0] = 944.281005859;
   fMin_1[0][1] = 0.374742239714;
   fMax_1[0][1] = 5.42305660248;
   fMin_1[1][1] = 0.352572113276;
   fMax_1[1][1] = 5.50419807434;
   fMin_1[2][1] = 0.352572113276;
   fMax_1[2][1] = 5.50419807434;
   fMin_1[0][2] = 0.302169948816;
   fMax_1[0][2] = 5.49215507507;
   fMin_1[1][2] = 0.279165536165;
   fMax_1[1][2] = 5.45479106903;
   fMin_1[2][2] = 0.279165536165;
   fMax_1[2][2] = 5.49215507507;
   fMin_1[0][3] = 3.20014187309e-05;
   fMax_1[0][3] = 3.14158844948;
   fMin_1[1][3] = 9.43251870922e-05;
   fMax_1[1][3] = 3.14158916473;
   fMin_1[2][3] = 3.20014187309e-05;
   fMax_1[2][3] = 3.14158916473;
   fMin_1[0][4] = 0.187668606639;
   fMax_1[0][4] = 0.999753773212;
   fMin_1[1][4] = 0.180118754506;
   fMax_1[1][4] = 0.999768972397;
   fMin_1[2][4] = 0.180118754506;
   fMax_1[2][4] = 0.999768972397;
   fMin_1[0][5] = 0.309950172901;
   fMax_1[0][5] = 996.801757812;
   fMin_1[1][5] = 0.284923136234;
   fMax_1[1][5] = 695.276062012;
   fMin_1[2][5] = 0.284923136234;
   fMax_1[2][5] = 996.801757812;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
